### ISSUE TITLE
NoSuchMethodError: No virtual method getDeclaredAnnotation on Android API level <24

### ISSUE THREAD

**Issue by brewin** [Kotlin/kotlinx.serialization#1010]
**Describe the bug**
```Kotlin
java.lang.NoSuchMethodError: No virtual method getDeclaredAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /system/framework/core-libart.jar)
        at kotlinx.serialization.internal.PlatformKt.polymorphicSerializer(Platform.kt:70)
        at kotlinx.serialization.internal.PlatformKt.constructSerializerForGivenTypeArgs(Platform.kt:53)
        at kotlinx.serialization.internal.PlatformKt.compiledSerializerImpl(Platform.kt:23)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerOrNull(Serializers.kt:129)
        at kotlinx.serialization.SerializersKt.serializerOrNull(Unknown Source)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:65)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:51)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
        at kotlinx.serialization.SerializersKt__SerializersKt.builtinSerializerOrNull$SerializersKt__SerializersKt(Serializers.kt:76)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:66)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:51)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:17)
```

[Related issue with resolution](https://github.com/FasterXML/jackson-module-kotlin/issues/176)

**To Reproduce**
On Android API level <24:
```Kotlin
Json.decodeFromString<List<Int>>("[0,1,2,3]")
```

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM (Android)
 - Gradle version: 6.1.1

**Comment by slavonnet** [comment]
+1 need on next rc

**Comment by webfrea-k** [comment]
Is there any version with this fix available yet (even dev would be great)?

**Comment by sandwwraith** [comment]
@webfrea-k We plan to release RC2 with this fix soon

**Comment by stramek** [comment]
Is there any approx ETA by a chance for the RC2?

**Comment by qwwdfsad** [comment]
~this week

**Comment by slavonnet** [comment]
7 days ago..... i want migrade from gson but android 23....

**Comment by iNdieboyjeff** [comment]
Yes, an ETA for RC2 would be very helpful as the fix is needed very urgently

**Comment by qwwdfsad** [comment]
We are in the process of releasing it but are encountering problems with build infrastructure. Either today or tomorrow it should be released

**Comment by sandwwraith** [comment]
The `1.0.0-RC2` is out now and should be available on JCenter
