### ISSUE TITLE
Kotlinx.serialization stopped working with version upgrade

### ISSUE THREAD

**Issue by adam-arold** [Kotlin/kotlinx.serialization#1023]
I was using `kotlinx.serialization` for a while and when I upgraded to Kotlin `1.4.0` it stopped working. I get the following exception:

```
SomeClass.write$Self(LSomeClass;Lkotlinx/serialization/encoding/CompositeEncoder;Lkotlinx/serialization/descriptors/SerialDescriptor;)V
java.lang.NoSuchMethodError: SomeClass.write$Self(LSomeClass;Lkotlinx/serialization/encoding/CompositeEncoder;Lkotlinx/serialization/descriptors/SerialDescriptor;)V
	at SomeClass$$serializer.serialize(SomeClass.kt)
	at SomeClass$$serializer.serialize(SomeClass.kt:4)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:223)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:73)
	at SerializationTest.test(SerializationTest.kt:17)
```

**To Reproduce**

Test:
```kotlin
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.junit.Test

class SerializationTest {

    private val json = Json {}

    @Test
    fun test() {
        val result = json.encodeToString(SomeClass("bar"))
        val someClass = json.decodeFromString<SomeClass>(result)
    }
}
```

SomeClass:
```kotlin
import kotlinx.serialization.Serializable

@Serializable
data class SomeClass(
        val xul: String
)
```

This is how my `build.gradle.kts` looks like:

```kotlin
plugins {
    kotlin("multiplatform") version "1.4.0"
    application
    kotlin("plugin.serialization") version "1.4.0"
}

kotlin {
    jvm {
        withJava()
    }
    sourceSets {
        val kotlinx_serialization_version: String by project

        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common"))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$kotlinx_serialization_version")
                // ...
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }

        val jvmMain by getting {
            dependencies {
                // ...
            }
        }
}
```

What am I doing wrong?

**Expected behavior**

I expect it to work.

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: jvm (multiplatform)
 - Gradle version: 6.6.1
 - IDE version: not related (fails from CLI)
 - Other relevant context: I'm on Windows (WSL)

**Comment by adam-arold** [comment]
I had the wrong Ktor version! Upgraded it to `1.4.0` and now it works.
