### ISSUE TITLE
Script containing Serialization cannot be built when a certain other library is installed

### ISSUE THREAD

**Issue by CaptainZidgel** [Kotlin/kotlinx.serialization#1030]
Hello, sorry to bother you with this tech support request which may very well be outside the scope of issue reports, but I have been racking my brain trying to solve this so I can continue writing my program.

**Describe the bug**
Attempting to build a Kotlin/JS program with serialization works, until another library (Plotlykt) is installed with Gradle (If you're wondering why I am not reporting this for Plotlykt, I don't know. Nothing about the bug suggests much about the actual issue. Since it is my file with serialization that fails to compile, I thought I'd start here.)
Here is the error trace:
```
e: org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: '<An entire file, whose only imports are from kotlinx.serialization>' at (1,1) in Z:/Projects/onelasttry/src/main/kotlin/Logs.kt
	at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:385)
	at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:336)
	at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:305)
	at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.kt:162)
	at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.kt:107)
	at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits$default(K2JSTranslator.kt:91)
	at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.kt:81)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:165)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:307)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:173)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:70)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:240)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:39)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:546)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1721)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.NoSuchElementException: Sequence contains no element matching the predicate.
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator$generateSave$1.invoke(SerializerJsTranslator.kt:388)
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator$generateSave$1.invoke(SerializerJsTranslator.kt:33)
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.JsCodegenUtilKt.buildFunction(JsCodegenUtil.kt:85)
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator.generateFunction$kotlinx_serialization_compiler_plugin(SerializerJsTranslator.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator.generateSave(SerializerJsTranslator.kt:153)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generateSaveIfNeeded(SerializerCodegen.kt:105)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generate(SerializerCodegen.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator$Companion.translate(SerializerJsTranslator.kt:374)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationJsExtension.generateClassSyntheticParts(SerializationJsExtension.kt:30)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.generateClassSyntheticParts(ClassTranslator.kt:158)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:111)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:607)
	at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.generateClassOrObject(DeclarationBodyVisitor.kt:57)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:108)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:611)
	at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:42)
	at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.visitClassOrObject(DeclarationBodyVisitor.kt:45)
	at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.visitClassOrObject(DeclarationBodyVisitor.kt:32)
	at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
	at org.jetbrains.kotlin.js.translate.general.TranslatorVisitor.traverseContainer(TranslatorVisitor.java:43)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:92)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
	at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:611)
	at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:42)
	at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:35)
	at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
	at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:377)
	... 38 more

```

Here is my Gradle build script:
```
plugins {
    id 'org.jetbrains.kotlin.js' version '1.4.0'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.4.0'
}

group 'org.example'
version '1.0-SNAPSHOT'

def serialization_version = "1.0.0-RC"

repositories {
    jcenter()
    mavenLocal()

    //these are for plotlykt
    maven { url "https://dl.bintray.com/mipt-npm/dataforge" }
    maven { url "https://dl.bintray.com/mipt-npm/scientifik" }
    maven { url "https://dl.bintray.com/mipt-npm/kscience" }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-js"
    testImplementation "org.jetbrains.kotlin:kotlin-test-js"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:$serialization_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.3.9"

    implementation 'kscience.plotlykt:plotlykt-core:0.2.0'
}

kotlin.target.browser { }
```

**Expected behavior**
The expected behavior, and the way it behaves when the last implementation line is removed, is to build.

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JS for browser
 - Gradle version: 6.5

**Comment by qwwdfsad** [comment]
Hi, could you please provide a sample project that reproduces the problem?

**Comment by sandwwraith** [comment]
Does the plotly itself contains a dependency on kotlinx.serialization? If so, this transitive dependency may be obsolete (0.20.0 instead of 1.0.0-RC) and incompatible with 1.4 compiler

**Comment by CaptainZidgel** [comment]
> 
> 
> Hi, could you please provide a sample project that reproduces the problem? It's good to have gradle build script, but sources that trigger compilation failure would be even better

I did not include this before because it seemed to not be a script problem but here is the entire IntelliJ project: https://github.com/CaptainZidgel/Erroring_Project
The script that the error message references a failed-to-compile fragment is here: https://github.com/CaptainZidgel/Erroring_Project/blob/master/src/main/kotlin/Logs.kt


> 
> 
> Does the plotly itself contains a dependency on kotlinx.serialization? If so, this transitive dependency may be obsolete (0.20.0 instead of 1.0.0-RC) and incompatible with 1.4 compiler

Don't think so. Their build script is [here](https://github.com/mipt-npm/plotly.kt/blob/master/plotlykt-core/build.gradle.kts), and I even sniffed around some of their own dependencies for serialization and didn't see any.

I appreciate both of you taking the time to check in on what is a tangential-at-best issue.
If nothing else jumps out at you to suggest this issue could be on kotlinx.serialization's side, I will move try posting this issue for plotlykt.

**Comment by altavir** [comment]
Yes, current version of plotly.kt (0.2.0) exposes old serialization runtime libraries. Furthermore, it does not support kotlin 1.4 and IR mode for now. The next version will support 1.4 and IR, but will drop legacy mode support. As for serialization, I am not sure if I should leave it as is or encaplsulate it. I use json API in some public functions.
