### ISSUE TITLE
Unexpected SerializationException in custom serializer

### ISSUE THREAD

**Issue by vganin** [Kotlin/kotlinx.serialization#1041]
I'm trying to write a custom `KSerializer` that omits all serialization exceptions and converting them to `null`s. Unfortunately try/catch in serializer doesn't work - the exception still occurs with somewhat cryptic stacktrace which doesn't contain my custom serializer.

**To Reproduce**
```kotlin
fun main() {
    val input = """
        {"a":"a", "b":"b", "c":69}
    """.trimIndent()

    assertEquals(
            expected = Test(
                    a = StringOrNull("a"),
                    b = StringOrNull("b"),
                    c = StringOrNull(null)
            ),
            actual = Json.decodeFromString(input)
    )
}

@Serializable
data class Test(
        val a: StringOrNull,
        val b: StringOrNull,
        val c: StringOrNull,
)

@Serializable(with = SafeSerializer::class)
data class StringOrNull(val value: String?)

object SafeSerializer : KSerializer<StringOrNull> {

    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(StringOrNull::class.simpleName!!, PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): StringOrNull {
        return try {
            val string = decoder.decodeString()
            StringOrNull(string)
        } catch (e: SerializationException) {
            // Ignore exception
            StringOrNull(null)
        }
    }

    override fun serialize(encoder: Encoder, value: StringOrNull) {
        throw UnsupportedOperationException("Not implemented")
    }
}
```

**Expected behavior**
The program runs with no errors.

**Actual behavior**
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 23: Expected string literal with quotes.
Use 'isLenient = true' in 'Json {}` builder to accept non-compliant JSON.
JSON input: {"a":"a", "b":"b", "c":69}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:30)
	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329)
	at kotlinx.serialization.json.internal.JsonReader.takeStringQuoted(JsonReader.kt:165)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:219)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:137)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:95)
	at Test$$serializer.deserialize(Main.kt)
	at Test$$serializer.deserialize(Main.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:62)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:40)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
	at MainKt.main(Main.kt:56)
	at MainKt.main(Main.kt)
```

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0-RC
 - Kotlin platforms: tested on JVM
 - Gradle version: 6.3

**Comment by tom5079** [comment]
The exception is self-explanatory. You specified to `decodeString` but there was no string literal with quotes in the input.
Set `isLenient = true` to enable weak typing.

**Comment by qwwdfsad** [comment]
Hi, this is expected behaviour and a missing part of our documentation.

Currently, if encoder/decoder throws an exception, it becomes unusable for further decode/encode methods.
In your particular example, `decoder.decodeString()` throws an exception because `69`, but internal state of the JSON decoder does not progress (why should it?). The very next operation of `Test` deserializer observes `69` and fails because it expects either end of an object or the next string key.

But for JSON, the [JSON-specific approach](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#under-the-hood-experimental) can be taken:

```
override fun deserialize(decoder: Decoder): StringOrNull {
    val jsonDecoder = decoder as? JsonDecoder ?: fail("Only JSON format is expected")
    val json = jsonDecoder.decodeJsonElement()
    if (json is JsonPrimitive && json.isString) {
        return StringOrNull(json.content)
    }
    return StringOrNull(null)
}
```

Does it solve your problem?

**Comment by vganin** [comment]
Yes, it does, thank you.

**Comment by i-am-the-slime** [comment]
Why does it crash at runtime? How do I avoid this?
