### ISSUE TITLE
JS compiler crash due Option or Transient annotations on fields

### ISSUE THREAD

**Issue by neworld** [Kotlin/kotlinx.serialization#107]
I have an issue for JVM, it serializes class properties. For example this class:
```kotlin
data class Foo(val a: Int) {
    val bar: String
        get() = "bar"
}
```
makes: `{a: 42, bar: "bar"}`. The same behavior is with Jackson. I am not able to parse it due #104 in JVM. So, I am adding transient annotations:

```kotlin
data class Foo(val a: Int) {
    @Transient
    val bar: String
        get() = "bar"
}
```

It works well on JVM side, but compileKotlin2Js fails:
```
org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment:
<my code>
 at (1,1) in /Users/neworld/projects/game/neworldwar/engine/src/main/kotlin/com/neworldwar/objects/Planet.kt
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:390)
        at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:299)
        at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:261)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.java:134)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.java:96)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:150)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:278)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:82)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:395)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:97)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:909)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:97)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:939)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:908)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:394)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: transient without an initializer
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:79)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:38)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.JsCodegenUtilKt.buildFunction(JsCodegenUtil.kt:84)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator.generateInternalConstructor(SerializableJsTranslator.kt:52)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:33)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$Companion.translate(SerializableJsTranslator.kt:101)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationJsExtension.generateClassSyntheticParts(SerializationJsExtension.kt:31)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.generateClassSyntheticParts(ClassTranslator.kt:153)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:111)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:568)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:44)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:37)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:34)
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:382)
        ... 34 more
```

**Comment by sandwwraith** [comment]
For workaround, see #2 and #104
