### ISSUE TITLE
ConcurrentModificationException after migration to 1.0.0-RC

### ISSUE THREAD

**Issue by azabost** [Kotlin/kotlinx.serialization#1071]
When I tried to switch to Kotlin 1.4.10 and kotlinx.serialization 1.0.0-RC, I started getting build errors on TeamCity. They didn't occur on my MacBook though.

```
[11:46:28]
[Step 1/2] e: java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation
[11:46:28]
[Step 1/2] > Task :menuManagement:menuManagementApi:compileReleaseKotlin FAILED
[11:46:28]
[Step 1/2] 
[11:46:28]
[Step 1/2] > Task :common:commonAndroid:commonAndroidInformationDialog:kaptGenerateStubsReleaseKotlin
[11:46:28]
[Step 1/2] File being compiled: file:///opt/buildagent/work/be85ffafd7928362/menuManagement/menuManagementApi/src/main/java/com/example/app/menumanagement/api/MenuManagementApi.kt
[11:46:28]
[Step 1/2] The root cause java.util.ConcurrentModificationException was thrown at: java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:78)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:616)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:203)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:346)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:102)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:240)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:39)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:81)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:93)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:601)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1633)
[11:46:28]
[Step 1/2] 	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
[11:46:28]
[Step 1/2] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:46:28]
[Step 1/2] 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:46:28]
[Step 1/2] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.Transport$1.run(Transport.java:200)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.Transport$1.run(Transport.java:197)
[11:46:28]
[Step 1/2] 	at java.security.AccessController.doPrivileged(Native Method)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
[11:46:28]
[Step 1/2] 	at java.security.AccessController.doPrivileged(Native Method)
[11:46:28]
[Step 1/2] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
[11:46:28]
[Step 1/2] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:46:28]
[Step 1/2] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:46:28]
[Step 1/2] 	at java.lang.Thread.run(Thread.java:748)
[11:46:28]
[Step 1/2] Caused by: java.util.ConcurrentModificationException
[11:46:28]
[Step 1/2] 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
[11:46:28]
[Step 1/2] 	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
[11:46:28]
[Step 1/2] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
[11:46:28]
[Step 1/2] 	at java.util.ArrayList.<init>(ArrayList.java:178)
[11:46:28]
[Step 1/2] 	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1283)
[11:46:28]
[Step 1/2] 	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1264)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.serialization.DescriptorSerializer$Companion.create(DescriptorSerializer.kt:789)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.serialization.DescriptorSerializer.create(DescriptorSerializer.kt)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.<init>(ImplementationBodyCodegen.java:119)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:301)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:285)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
[11:46:28]
[Step 1/2] 	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
[11:46:28]
[Step 1/2] 	... 35 more
```

Environment
 - Kotlin version: 1.4.10
 - Library version: 1.0.0-RC
 - Kotlin platforms: Android
 - Gradle version: 6.6.1

Since the project is very large and closed-source, I'm afraid I won't be able to provide the sources to reproduce it.

Please let me know if there is anything else I can do to help you.

**Comment by azabost** [comment]
Update: Just noticed the same issue when building locally on MacBook which means I was just lucky before. Triggering the build again usually helps but I guess it could possibly fail a few times in a row.

**Comment by ekimmel-ta** [comment]
https://youtrack.jetbrains.com/issue/KT-41857 has some more details for what the root issue may be.  Since it appears to originate in DescriptorSerializer, I would assume this fix lies in this project somewhere.
