### ISSUE TITLE
IllegalAccessError when deserializing sealed subclass

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.serialization#112]
Here is the minimum code to reproduce the error:

```
sealed class Exp
@Serializable class Var(val id: String) : Exp() 

fun main(args: Array<String>) {
    val s1 = JSON.stringify(Var("a"))   //{"id":"a"}
    val v2: Var = JSON.parse(s1)   //throws IllegalAccessError
}
```

And here is the full stack trace:

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access method serDemo.Exp.<init>()V from class serDemo.Var
        at serDemo.Var.<init>(Exp.kt)
        at serDemo.Var$$serializer.load(Exp.kt)
        at serDemo.Var$$serializer.load(Exp.kt:11)
        at kotlinx.serialization.KInput.read(Serialization.kt:209)
        at kotlinx.serialization.json.JSON.parse(JSON.kt:47)
        at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:57)
        at org.smartsoft.konfigurator.ExpKt.main(Exp.kt:35)
```

Attached is a complete gradle project to reproduce the error.

[kser1.zip](https://github.com/Kotlin/kotlinx.serialization/files/1929428/kser1.zip)

Also, where can I access the generated code for serDemo.Var$$serializer.load(Exp.kt)?

**Comment by sandwwraith** [comment]
Current workaround is to specify `Exp` also as `Serializable`. However, this indeed should work even if `Exp` is not serializable.
