### ISSUE TITLE
Caused by m.a.f: Serializer for class 'a' is not found. - And I don't have any 'a' class.

### ISSUE THREAD

**Issue by FrancescoBonizzi** [Kotlin/kotlinx.serialization#1133]
**Describe the bug**
Automatic tests on Google Play Console reveal this error:

```
Caused by m.a.f: Serializer for class 'a' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
       at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform_commonKt.java:23)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:23)
       at kotlinx.serialization.SerializersKt.serializer(SerializersKt.java:23)
       at com.francescobonizzi.invoiceEstimateReceiptMaker.storage.JsonAppConfigurationRepository.<init>(JsonAppConfigurationRepository.java:7)
       at com.francescobonizzi.invoiceEstimateReceiptMaker.di.DependenciesKt$appDependencies$1$2.invoke(DependenciesKt.java:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.java:9)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.java)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.java:2)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:3)
       at org.koin.core.scope.Scope.resolveInstance(Scope.java:3)
       at org.koin.core.scope.Scope.get(Scope.java:9)
       at com.francescobonizzi.invoiceEstimateReceiptMaker.pages.InvoicesFragment$$special$$inlined$inject$3.invoke(InvoicesFragment.java:2)
       at kotlin.UnsafeLazyImpl.getValue(UnsafeLazyImpl.java)
       at com.francescobonizzi.invoiceEstimateReceiptMaker.pages.InvoicesFragment.get_appConfigurationRepository(InvoicesFragment.java:1)
       at com.francescobonizzi.invoiceEstimateReceiptMaker.pages.InvoicesFragment.onResume(InvoicesFragment.java:2)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:52)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:52)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:52)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onSupportInvalidateOptionsMenu(FragmentActivity.java)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:55)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:55)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:55)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onSupportInvalidateOptionsMenu(FragmentActivity.java)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:3)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:3)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:3)
       at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java)
       at android.app.Activity.performResume(Activity.java:6800)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

I really don't have any 'a' class!

**To Reproduce**
I cannot reproduce it, I get it only on the automatic Google Play Console tests. 
In this case it happened on an Android 7 emulated device.

**Environment**
 - Kotlin version: 1.4.10
 - Library version: org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.0-RC
 - Kotlin platforms: Android
 - Gradle version: 4.0.0
 - Other relevant context: happened on Android 7 emulated device.

**Comment by hfhbd** [comment]
You don't have a `m` class also, do you? Your class names are shorted by R8 (or Proguard), so you have to find the real class name, normally R8 or Proguard create a mapper file, see https://developer.android.com/studio/build/shrink-code#decode-stack-trace

**Comment by FrancescoBonizzi** [comment]
Many thanks. I didn't know about the shortening. I'm new to Android programming.

**Comment by sandwwraith** [comment]
Probably you need these proguard rules — https://github.com/Kotlin/kotlinx.serialization#android
