### ISSUE TITLE
Calling decoder.decodeString() twice leads to JsonDecodingException

### ISSUE THREAD

**Issue by teyyihan** [Kotlin/kotlinx.serialization#1141]
**Describe the bug**
In my project I use DHPublicKey from javax.crypto.interfaces . Since Kotlinx Serialization doesn't serialize by default, I had to provide a custom Serializer. Here it is:

    object PublicSerial : KSerializer<DHPublicKey> {
       override val descriptor: SerialDescriptor =
                 PrimitiveSerialDescriptor("DHPublicKey", PrimitiveKind.STRING)

       override fun deserialize(decoder: Decoder): DHPublicKey {
        val str = decoder.decodeString()
        // val str1 = decoder.decodeString()  if I uncomment this line it crashes. But if I don't it works
        val publicKeyBytes = Base64.decode(str,Base64.DEFAULT)
        val factory: KeyFactory = KeyFactory.getInstance("DH")
        return factory.generatePublic(X509EncodedKeySpec(publicKeyBytes)) as DHPublicKey
    }

    override fun serialize(encoder: Encoder, value: DHPublicKey) {
        encoder.encodeString(Base64.encodeToString(value.encoded,Base64.DEFAULT))
    }
    }

**To Reproduce**
Attach a code snippet or test data if possible.
When I try to assign `decoder.decodeString()` to a variable or call it in a log (basically when calling twice), It crashes. Here is the stacktrace:

```Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1148: Expected string literal with quotes.
    Use 'isLenient = true' in 'Json {}` builder to accept non-compliant JSON.
    JSON input: .....5g6ljnvj1\nmht1isxW7Ubv74Y=\n"}
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:333)
        at kotlinx.serialization.json.internal.JsonReader.takeStringQuoted(JsonReader.kt:165)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:212)
        at com.teyyihan.marathon_test.PublicSerial.deserialize(MainActivity.kt:120)
        at com.teyyihan.marathon_test.PublicSerial.deserialize(MainActivity.kt:111)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at com.teyyihan.marathon_test.UserModel$$serializer.deserialize(Unknown Source:68)
        at com.teyyihan.marathon_test.UserModel$$serializer.deserialize(UserModel.kt:8)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at com.teyyihan.marathon_test.MainActivity.testUser(MainActivity.kt:133)
        at com.teyyihan.marathon_test.MainActivity.onCreate(MainActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
        	... 11 more
```

**Expected behavior**
**Disclaimer**: Like stacktrace says ``Use 'isLenient = true' in 'Json {}` builder to accept non-compliant JSON``, I've used `isLenient = true` in my Json Builder but it is still the same.
I don't know if it's intentional or bug so I created this issue. I can basically use `.copy()` but it looks like a bug.

**Environment**
 - Kotlin version: 1.4.10
 - Library version: org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.0
 - Kotlin platforms: Android
 - Gradle version:6.1.1
 - IDE version (if bug is related to the IDE) Android Studio 4.1
 - Other relevant context Windows 10 64bit

**Comment by qwwdfsad** [comment]
Please check out our [guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md) regarding custom serializers.

`decodeString` tries to decode the _next_ string value which is not present in the data. Our hints try to make an educated guess about what went wrong and how to fix it, but in this case, it was unsuccessful.

Effectively, if you are invoking, let's say, `encodeString` *once* during a serialization, then the corresponding `decodeString` can also be invoked only once.

Thinking in implementation details: how should implementation know when `decodeString` have to return previously read value and when to read a new one?
