### ISSUE TITLE
[Question] Probably I somehow incorrectly configure the application, but when I get it I get an error

### ISSUE THREAD

**Issue by BorzdeG** [Kotlin/kotlinx.serialization#115]
source: https://github.com/BorzdeG/samples-kotlin-subprojects/tree/kotlinx.serialization

```
Exception in thread "main" java.lang.IllegalArgumentException: JSON at 5: Expected '{, kind: CLASS'
	at kotlinx.serialization.json.JSON$Companion.fail(JSON.kt:190)
	at kotlinx.serialization.json.JSON$Companion.require(JSON.kt:186)
	at kotlinx.serialization.json.JSON$Companion.access$require(JSON.kt:54)
	at kotlinx.serialization.json.JSON$JsonInput.readBegin(JSON.kt:349)
	at demo.common.ChildModelSerializer.load(ChildModel.kt:25)
	at demo.common.ChildModelSerializer.load(ChildModel.kt:9)
	at kotlinx.serialization.KInput.readSerializableValue(Serialization.kt:243)
	at kotlinx.serialization.ElementValueInput.readSerializableElementValue(Serialization.kt:438)
	at demo.common.ParentModelSerializer.load(ParentModel.kt:35)
	at demo.common.ParentModelSerializer.load(ParentModel.kt:15)
	at kotlinx.serialization.KInput.read(Serialization.kt:209)
	at kotlinx.serialization.json.JSON.parse(JSON.kt:47)
	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:57)
	at demo.client.jvm.ClientJvmKt.main(ClientJvm.kt:28)
```

**Comment by sandwwraith** [comment]
The correct approach to write deserializing code manually is to use `input` returned from `readBegin`. Also you always need to call `readElement` to determine current element to read (in json, they can go in other order comparing to what you have in class) So code for your `ChildModel` will look like this:

```kotlin
override fun load(input: KInput): ChildModel {
		val newInput = input.readBegin(serialClassDesc)
                val i = newInput.readElement(serialClassDesc)
                check(i == 0) // if you have more than on field, make "when" here
		val cf = newInput.readStringElementValue(serialClassDesc, 0)
		newInput.readEnd(serialClassDesc)
		return ChildModel(cf = cf)
	}
```

**Comment by sandwwraith** [comment]
But I'm wondering why you're trying to write the same code that plugin will generate for you...

**Comment by JoaquimLey** [comment]
It might not be the case for @BorzdeG, but I got a similar error and writing this trying to help others.

In my case, I was trying to parse my object from an empty `String`, so make sure your `String` is not null and that in fact, the `String` you are receiving matches your `Model.class` 

**e.g:**

```kotlin
class Model(name: String)
```

Is updated to  

```kotlin
class Model(firstName: String, lastName: String)
```

If the model you have stored/ trying to parse doesn't match 1-to-1, this is the logical error to be thrown, so watch out for that.
