### ISSUE TITLE
Got JsonDecodingException with my custom kserializer

### ISSUE THREAD

**Issue by iamthevoid** [Kotlin/kotlinx.serialization#1151]
Trying to parse json object with nullable date strings and deserialize they to Date?. Wrote KSerializer like this

```kotlin
internal object DateSerializer : KSerializer<Date?> {
    private val df: DateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")

    private val delegate = String.serializer().nullable

    override val descriptor: SerialDescriptor
        get() = delegate.descriptor

    override fun deserialize(decoder: Decoder): Date? {
        val string = delegate.deserialize(decoder)
        return string?.let(df::parse)
    }

    override fun serialize(encoder: Encoder, value: Date?) {
        if (value == null) {
            delegate.serialize(encoder,null)
        } else {
            delegate.serialize(encoder,value.let(df::format))
        }
    }
}
```
i wait that `nullable string serializer` correctly handle standart case with nullable string (which works perfectly for String fields in Serializable class), but i getting JsonDecodingException

```
E/MetricsViewModel: Network
    kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 6081: Expected string or non-null literal
    JSON input: .....       "devices": [
              {
                "check_at": null.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:333)
        at kotlinx.serialization.json.internal.JsonReader.takeString(JsonReader.kt:147)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:210)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:140)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:137)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
        at iam.thevoid.test.compose.data.data.json.serializer.DateSerializer.deserialize(DateSerializer.kt:26)
        at iam.thevoid.test.compose.data.data.json.serializer.DateSerializer.deserialize(DateSerializer.kt:17)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$Room$$serializer.deserialize(Unknown Source:164)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$Room$$serializer.deserialize(MetricsResponse.kt:154)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
E/MetricsViewModel:     at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$Data$$serializer.deserialize(Unknown Source:243)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$Data$$serializer.deserialize(MetricsResponse.kt:12)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$$serializer.deserialize(Unknown Source:48)
        at iam.thevoid.test.compose.data.data.response.MetricsResponse$$serializer.deserialize(MetricsResponse.kt:9)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:30)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Maybe it is stupid question, but i cannot find proper documentation, how to deserialize nulls. Seems like `nullable` should return `NullableDeserailizer` that wraps `Stringdeserializer`, that correctly handle null case and then my deserializer could use result optional value. 

I use it in serializable class like that (removed all unnecessary stuff)
```kotlin
@Serializable
class MetricsResponse(@SerialName("data") val data: Data) {

    @Serializable
    class Data(
        @SerialName("room")
        val room: List<Room>,
    )


    @Serializable
    data class Room(
        @SerialName("devices")
        val devices: List<Device?>,
    ) {

        @Serializable(with = DateSerializer::class)
        data class Device(
            @SerialName("check_at")
            val checkAt: Date?,
        )
    }
}
```

I use 
Android
kotlin 1.4.10
plugin 'kotlinx-serialization' 1.4.10
and retrofit with com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0

**Comment by pdvrieze** [comment]
Basically your date serializer serializes your date as a primitive (not a struct). As such it is not the DateSerializer that can (or should) handle nulls, (remember it is a glorified StringSerializer). It is the user of the dateserializer that handles nulls, not the dateserializer itself. Iow if you remove all nullable stuff/null handling stuff in the serializer it should work.

**Comment by qwwdfsad** [comment]
Serializers do not compose this way, unfortunately.

To fix your problem, please rewrite deserialize method in the following way:
```
override fun deserialize(decoder: Decoder): Date? {
    if (decoder.decodeNotNullMark()) {
        return Date(decoder.decodeString())
    }
    return decoder.decodeNull()
}
```

**Comment by qwwdfsad** [comment]
Your serializable application doesn't pass type-checker, it will be an error in Kotlin 1.4.20: #830

You have to use the following code instead:
```
@Serializable
data class Device(
    @SerialName("check_at")
    @Serializable(with = DateSerializer::class) val checkAt: Date?
)
```

And if you want to have your `Device` class to be flattened into outer class, you have to write your custom serializer in terms of `Device` type, not `Date`
