### ISSUE TITLE
Serialize a string?

### ISSUE THREAD

**Issue by helikopterodaktyl** [Kotlin/kotlinx.serialization#119]
I'm trying to learn how this library works, and came across this weird behavior:

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON

@Serializable
data class Foo(var i: Int)

fun main(args: Array<String>) {
    var v = Foo(10)
    System.out.println(JSON.stringify(v))
    var s = "hello"
    System.out.println(JSON.stringify(s))
}

```

Output:

```
{"i":10}
Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate default serializer for class class kotlin.String
	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:23)
	at MainKt.main(Main.kt:76)
```

Is serializing strings supported?

lib versions:
```
    ext.kotlin_version = '1.2.41'
    ext.serialization_version = '0.5.0'
```

**Comment by hastebrot** [comment]
Currently, you need to explictly pass the `KSerializer` to `JSON.stringify()`.

~~~kt
import kotlinx.serialization.internal.StringSerializer
import kotlinx.serialization.json.JSON

fun main(args: Array<String>) {
    val s = "hello"
    System.out.println(JSON.stringify(StringSerializer, s))
}
~~~

**Comment by sandwwraith** [comment]
Indeed, default serializers for primitives and collections on root-level cannot be inferred automatically for now.

**Comment by sandwwraith** [comment]
Fixed by https://github.com/Kotlin/kotlinx.serialization/commit/48b97e201c0a2b089e32d358489be468e94a162f
