### ISSUE TITLE
Can't serialize generic class in sealed class

### ISSUE THREAD

**Issue by camdenorrb** [Kotlin/kotlinx.serialization#1271]
**Describe the bug**

**To Reproduce**
```Kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.protobuf.ProtoBuf

@Serializable
sealed class Message {

    @Serializable
    data class Blob<M : Message>(
        val messages: List<M> = emptyList()
    ) : Message()

    @Serializable
    data class Test(
        val text: String
    ) : Message()

}

object RandomTest {

    @JvmStatic
    fun main(args: Array<String>) {

        val testMessage = Message.Blob(listOf(Message.Test("Meow")))

        val encoded = ProtoBuf.encodeToByteArray(Message.serializer(), testMessage)
        val decoded = ProtoBuf.decodeFromByteArray(Message.serializer(), encoded)

        check(testMessage == decoded)
    }

}
```

Error:
```Kotlin
Exception in thread "main" kotlinx.serialization.SerializationException: Class 'Test' is not registered for polymorphic serialization in the scope of 'Message'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:103)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.serialize(AbstractPolymorphicSerializer.kt:32)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:123)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:114)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:123)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:114)
	at me.camdenorrb.generaltesting.breakinkotlin.Message$Blob.write$Self(SerializationBug1.kt:11)
	at me.camdenorrb.generaltesting.breakinkotlin.Message$Blob$$serializer.serialize(SerializationBug1.kt)
	at me.camdenorrb.generaltesting.breakinkotlin.Message$Blob$$serializer.serialize(SerializationBug1.kt:10)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:123)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:114)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.serialize(AbstractPolymorphicSerializer.kt:35)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:123)
	at kotlinx.serialization.protobuf.ProtoBuf.encodeToByteArray(ProtoBuf.kt:130)
	at me.camdenorrb.generaltesting.breakinkotlin.RandomTest.main(SerializationBug1.kt:28)

Process finished with exit code 1
```

**Environment**
 - Kotlin version: 1.4.20
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.7.1

**Comment by sandwwraith** [comment]
It seems that when we take upper-bound of the generic argument, we do not check if it is sealed, we only enable/disable polymorphism. You can workaround this by registering all serializers explicitly in module, as if `Message` was abstract, not sealed, class

**Comment by shanshin** [comment]
Duplicates #613
