### ISSUE TITLE
Fail to use custom UByteArray Serializer to Deserialize 

### ISSUE THREAD

**Issue by Jaspion18** [Kotlin/kotlinx.serialization#1311]
I created a custom Serializer to convert between base64 and UByteArray. 
At the moment I add this Serializer in the class I get an exception while trying to deserialize, even if it's not used. Serialization works as expected.

If I change type of the field to ByteArray the exception is gone. 
(Android project)

Code to reproduce (based on [here](https://github.com/Kotlin/kotlinx.serialization#introduction-and-references)):
```kotlin
package com.jaspion.newsettingsfragment

import android.os.Bundle
import java.util.Base64
import androidx.appcompat.app.AppCompatActivity
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.*

class MainActivity : AppCompatActivity() {

    @ExperimentalSerializationApi
    @ExperimentalUnsignedTypes
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // Serializing objects
        val data = Project("kotlinx.serialization", "Kotlin")
        val string = Json.encodeToString(data)
        println(string) // {"name":"kotlinx.serialization","language":"Kotlin"}
        // Deserializing back into objects - Not even using 'UByteArrayBase64Serializer' 
        val obj = Json.decodeFromString<Project>(string)
        println(obj) // Project(name=kotlinx.serialization, language=Kotlin)
    }
}


@Serializable
data class Project constructor(val name: String, val language: String, @Serializable(with = UByteArrayBase64Serializer::class) val test:UByteArray? = null)

//Changing this class to work with ByteArray instead of UByteArray doesn't help - I get the same exception
@Serializer(forClass = UByteArray::class)
object UByteArrayBase64Serializer : KSerializer<UByteArray> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("UByteArrayBase64Serializer", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: UByteArray) {
        //encoder.encodeString(Base64.encodeToString(value.toByteArray(), Base64.NO_WRAP))
        encoder.encodeString(Base64.getEncoder().encodeToString(value.toByteArray()))
    }

    override fun deserialize(decoder: Decoder): UByteArray {
        val text = decoder.decodeString()
        //return Base64.decode(text, Base64.NO_WRAP).toUByteArray()
        return Base64.getDecoder().decode(text).toUByteArray()
    }
}
```
 Exception got:
I/System.out: {"name":"kotlinx.serialization","language":"Kotlin"}
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jaspion.newsettingsfragment, PID: 28108
    java.lang.IllegalAccessError: Method 'void com.jaspion.newsettingsfragment.Project.<init>(int, java.lang.String, java.lang.String, byte[], kotlinx.serialization.internal.SerializationConstructorMarker)' is inaccessible to class 'com.jaspion.newsettingsfragment.Project$$serializer' (declaration of 'com.jaspion.newsettingsfragment.Project$$serializer' appears in /data/app/com.jaspion.newsettingsfragment-lv00bXppXA-6aArZgNt64g==/base.apk!classes2.dex)
        at com.jaspion.newsettingsfragment.Project$$serializer.deserialize(Unknown Source:109)
        at com.jaspion.newsettingsfragment.Project$$serializer.deserialize(MainActivity.kt:48)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at com.jaspion.newsettingsfragment.MainActivity.onCreate(MainActivity.kt:104)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by sandwwraith** [comment]
It looks like the `UByteArray` is an inline class, and we do not support serializable inline classes even with custom serializers (yet)

**Comment by Jaspion18** [comment]
Ok Thanks!
