### ISSUE TITLE
1.1.0-RC internal compiler error when using IR compiler 1.4.30 and Java enum class as field type

### ISSUE THREAD

**Issue by tnleeuw** [Kotlin/kotlinx.serialization#1334]
**Describe the bug**
Using Kotlin 1.4.30 and KotlinX Serialisation 1.1.0-RC with the IR compiler plugin, there is an internal compiler error on compiling a data class which contains a Java enum field:

```
Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.30:compile (compile) on project mainModule: Compilation failure
java.lang.AssertionError: Enum class does not have .values() function
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.findEnumValuesMethod(GeneratorHelpers.kt:507)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.findEnumValuesMethod(SerializerIrGenerator.kt:47)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:714)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.serializerInstance(SerializerIrGenerator.kt:47)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:586)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.serializerInstance(SerializerIrGenerator.kt:47)
```

**To Reproduce**
Java Enum:
```
public enum AJavaEnum {
    A, B
}
```
Kotlin class:
```
import kotlinx.serialization.Serializable

@Serializable
data class SerzTestClass constructor(
    val thisBreaks: AJavaEnum,
    val thisWorks: AKotlinEnum,
)
```

**Expected behavior**
Expect this to compile fine like it does with the non-IR plugin. ;)

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.1.0-RC
 - Kotlin platforms: JVM
 - Maven version: 3.3.6
 - JDK 11

**Attached**
Maven project demonstrating the problem:
- [kotlinx-serz-crash.zip](https://github.com/Kotlin/kotlinx.serialization/files/5958560/kotlinx-serz-crash.zip)

Full maven output
- [kotinz-serz-crash-maven-output.log](https://github.com/Kotlin/kotlinx.serialization/files/5958588/kotinz-serz-crash-maven-output.log)

**Comment by sandwwraith** [comment]
May be related to #1059

**Comment by tnleeuw** [comment]
May I ask in which version you expect this fix to be released? :)
