### ISSUE TITLE
Error when deserializing nested JSON objects with custom List<MyClass> deserializer

### ISSUE THREAD

**Issue by mi-ast** [Kotlin/kotlinx.serialization#1346]
I need custom deserializer to skip new types of sealed children. In example i tried to write just working serializer and faced the error mentioned below. If you know any workarounds for my problem, feel free to point them.
**To Reproduce**
This is the minimal reproduction example, so if you remove sealed class or make level of nested deserialization < 2, then serializer will work as expected.
```kotlin
@Serializable
sealed class A {
    @Serializable
    @SerialName("B")
    data class B(
        @Serializable(ASerializer::class)
        val children: List<A>
    ) : A()
}

@OptIn(ExperimentalSerializationApi::class)
object ASerializer : KSerializer<List<A>> {

    private val elementSerializer = A.serializer()

    override val descriptor: SerialDescriptor = listSerialDescriptor<A>()

    override fun deserialize(decoder: Decoder): List<A> {
        val result = mutableListOf<A>()
        val compositeDecoder = decoder.beginStructure(descriptor)
        while (true) {
            val index = compositeDecoder.decodeElementIndex(descriptor)
            if (index == CompositeDecoder.DECODE_DONE) {
                break
            }
            result.add(decoder.decodeSerializableValue(elementSerializer))
        }
        compositeDecoder.endStructure(descriptor)
        return result
    }

    override fun serialize(encoder: Encoder, value: List<A>) {
        val composite = encoder.beginCollection(descriptor, value.size)
        val iterator = value.iterator()
        for (index in value.indices) {
            composite.encodeSerializableElement(descriptor, index, elementSerializer, iterator.next())
        }
        composite.endStructure(descriptor)
    }
}

internal class ASerializerTest {
    @Test
    fun testDeserialization() {
        val aJsonString = """
            {
                "type" : "B",
                "children" : [
                    {
                        "type" : "B",
                        "children" : [
                            {
                                "type" : "B",
                                "children" : []
                            }
                        ]
                    }
                ]
            }
        """
        val json = Json { ignoreUnknownKeys = true }
        val deserialized = json.decodeFromString<A.B>(aJsonString)
        assertEquals(deserialized, A.B(listOf(A.B(listOf(A.B(emptyList()))))))
    }
}
```

**Error**
```
kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject as the serialized body of my.fancy.package.A, but had class kotlinx.serialization.json.JsonArray

	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:84)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at my.fancy.package.ASerializer.deserialize(KotlinSerializationEtudes.kt:42)
	at my.fancy.package.ASerializer.deserialize(KotlinSerializationEtudes.kt:28)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:191)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:256)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:273)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:256)
	at my.fancy.package.A$B$$serializer.deserialize(KotlinSerializationEtudes.kt)
	at my.fancy.package.A$B$$serializer.deserialize(KotlinSerializationEtudes.kt:21)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readPolymorphicJson(TreeJsonDecoder.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:73)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at my.fancy.package.ASerializer.deserialize(KotlinSerializationEtudes.kt:42)
	at my.fancy.package.ASerializer.deserialize(KotlinSerializationEtudes.kt:28)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at my.fancy.package.A$B$$serializer.deserialize(KotlinSerializationEtudes.kt)
	at my.fancy.package.A$B$$serializer.deserialize(KotlinSerializationEtudes.kt:21)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
	at my.fancy.package.ASerializerTest.testDeserialization(ASerializerTest.kt:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```
**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.7

Also tested with kotlin 1.4.30 and kotlin serialization 1.1.0-RC, but no luck there

**Comment by mi-ast** [comment]
Well, there is an error in the example. I used wrong decoder inside deserializing loop:
```kotlin
result.add(decoder.decodeSerializableValue(elementSerializer))
```
instead of
```kotlin
result.add(compositeDecoder.decodeSerializableElement(descriptor, index, elementSerializer))
```
With this fix deserialization pipeline works as expected.
