### ISSUE TITLE
Updated to version 1.1.0, but still cannot serialize unsigned type

### ISSUE THREAD

**Issue by loongtail** [Kotlin/kotlinx.serialization#1350]
I defined a class like below in a new Android Project with only one Activity:

```
@Serializable
class MatlInfo
{
    var cCode:String? = ""
    var cName:String? = ""
    var iTotal: UInt = 0u
}

```

But build failed with error:

```
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated
   L0
    ICONST_0
    DUP
    ILOAD 1
    IAND
    IF_ICMPEQ L1
    ILOAD 1
    ICONST_0
    GETSTATIC com/ees/originbna/MatlInfo$$serializer.INSTANCE : Lcom/ees/originbna/MatlInfo$$serializer;
    CHECKCAST kotlinx/serialization/KSerializer
    INVOKEINTERFACE kotlinx/serialization/KSerializer.getDescriptor ()Lkotlinx/serialization/descriptors/SerialDescriptor; (itf)
    INVOKESTATIC kotlinx/serialization/internal/PluginExceptionsKt.throwMissingFieldException (IILkotlinx/serialization/descriptors/SerialDescriptor;)V
   L1
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ILOAD 1
    ICONST_1
    IAND
    ICONST_0
    IF_ICMPEQ L2
    ALOAD 0
    ALOAD 2
    PUTFIELD com/ees/originbna/MatlInfo.cCode : Ljava/lang/String;
    GOTO L3
   L2
    LINENUMBER 8 L2
    ALOAD 0
    LDC ""
    PUTFIELD com/ees/originbna/MatlInfo.cCode : Ljava/lang/String;
   L3
    ILOAD 1
    ICONST_2
    IAND
    ICONST_0
    IF_ICMPEQ L4
    ALOAD 0
    ALOAD 3
    PUTFIELD com/ees/originbna/MatlInfo.cName : Ljava/lang/String;
    GOTO L5
   L4
    LINENUMBER 9 L4
    ALOAD 0
    LDC ""
    PUTFIELD com/ees/originbna/MatlInfo.cName : Ljava/lang/String;
   L5
    ILOAD 1
    ICONST_4
    IAND
    ICONST_0
    IF_ICMPEQ L6
    ALOAD 0
    ILOAD 4
    PUTFIELD com/ees/originbna/MatlInfo.iTotal : I
    GOTO L7
   L6
    LINENUMBER 10 L6
    ALOAD 0
    ICONST_0
    PUTFIELD com/ees/originbna/MatlInfo.iTotal : I
   L7
    RETURN
   L8
    LOCALVARIABLE this Lcom/ees/originbna/MatlInfo; L0 L8 0
    LOCALVARIABLE seen1 I L0 L8 1
    LOCALVARIABLE cCode Ljava/lang/String; L0 L8 2
    LOCALVARIABLE cName Ljava/lang/String; L0 L8 3
    LOCALVARIABLE iTotal Lkotlin/UInt; L0 L8 4
    LOCALVARIABLE serializationConstructorMarker Lkotlinx/serialization/internal/SerializationConstructorMarker; L0 L8 5
    MAXSTACK = 3
    MAXLOCALS = 6

File being compiled: (5,1) in C:/Users/loong/AndroidStudioProjects/originbna/app/src/main/java/com/ees/originbna/test.kt
The root cause org.jetbrains.kotlin.codegen.CompilationException was thrown at: org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:968)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:498)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:260)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:165)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt.generateMethod(JVMCodegenUtil.kt:144)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.generateInternalConstructor(SerializableCodegenImpl.kt:86)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:29)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl$Companion.generateSerializableExtensions(SerializableCodegenImpl.kt:53)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationCodegenExtension.generateClassSyntheticParts(SerializationCodegenExtension.kt:29)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:448)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:132)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:77)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:62)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:595)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:211)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:386)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:110)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:286)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:111)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
<init> (ILjava/lang/String;Ljava/lang/String;Lkotlin/UInt;Lkotlinx/serialization/internal/SerializationConstructorMarker;)V:
   L0
    ICONST_0
    DUP
    ILOAD 1
    IAND
    IF_ICMPEQ L1
    ILOAD 1
    ICONST_0
    GETSTATIC com/ees/originbna/MatlInfo$$serializer.INSTANCE : Lcom/ees/originbna/MatlInfo$$serializer;
    CHECKCAST kotlinx/serialization/KSerializer
    INVOKEINTERFACE kotlinx/serialization/KSerializer.getDescriptor ()Lkotlinx/serialization/descriptors/SerialDescriptor; (itf)
    INVOKESTATIC kotlinx/serialization/internal/PluginExceptionsKt.throwMissingFieldException (IILkotlinx/serialization/descriptors/SerialDescriptor;)V
   L1
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ILOAD 1
    ICONST_1
    IAND
    ICONST_0
    IF_ICMPEQ L2
    ALOAD 0
    ALOAD 2
    PUTFIELD com/ees/originbna/MatlInfo.cCode : Ljava/lang/String;
    GOTO L3
   L2
    LINENUMBER 8 L2
    ALOAD 0
    LDC ""
    PUTFIELD com/ees/originbna/MatlInfo.cCode : Ljava/lang/String;
   L3
    ILOAD 1
    ICONST_2
    IAND
    ICONST_0
    IF_ICMPEQ L4
    ALOAD 0
    ALOAD 3
    PUTFIELD com/ees/originbna/MatlInfo.cName : Ljava/lang/String;
    GOTO L5
   L4
    LINENUMBER 9 L4
    ALOAD 0
    LDC ""
    PUTFIELD com/ees/originbna/MatlInfo.cName : Ljava/lang/String;
   L5
    ILOAD 1
    ICONST_4
    IAND
    ICONST_0
    IF_ICMPEQ L6
    ALOAD 0
    ILOAD 4
    PUTFIELD com/ees/originbna/MatlInfo.iTotal : I
    GOTO L7
   L6
    LINENUMBER 10 L6
    ALOAD 0
    ICONST_0
    PUTFIELD com/ees/originbna/MatlInfo.iTotal : I
   L7
    RETURN
   L8
    LOCALVARIABLE this Lcom/ees/originbna/MatlInfo; L0 L8 0
    LOCALVARIABLE seen1 I L0 L8 1
    LOCALVARIABLE cCode Ljava/lang/String; L0 L8 2
    LOCALVARIABLE cName Ljava/lang/String; L0 L8 3
    LOCALVARIABLE iTotal Lkotlin/UInt; L0 L8 4
    LOCALVARIABLE serializationConstructorMarker Lkotlinx/serialization/internal/SerializationConstructorMarker; L0 L8 5
    MAXSTACK = 3
    MAXLOCALS = 6

File is unknown
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:961)
	... 52 more
Caused by: java.lang.AssertionError: AFTER mandatory stack transformations: incorrect bytecode
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
	at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.kt:62)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:70)
	... 53 more
Caused by: java.lang.RuntimeException: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 51: Expected I, but found R
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:34)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.analyze(MethodTransformer.java:44)
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:26)
	... 56 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 51: Expected I, but found R
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:291)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:31)
	... 58 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Expected I, but found R
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:103)
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:43)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:290)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:187)
	... 59 more
```

When I defined the "iTotal" from UInt to Int, there is no error in build. Serialization and decoding are fine without unsigned type, do I need some extract operations to make unsigned type serialization work?

**Environment**
 - Kotlin version: [1.4.30]
 - Library version: [1.1.0]
 - Kotlin platforms: [android]
 - Gradle version: [6.5]
 - IDE version (if bug is related to the IDE) [Android Studio 4.1.2]

**Comment by qwwdfsad** [comment]
Please ensure that you have JVM IR backend enabled: https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#experimental-support-for-inline-classes-ir-only

Does it solves your problem?

**Comment by loongtail** [comment]
> Please ensure that you have JVM IR backend enabled: https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#experimental-support-for-inline-classes-ir-only
> 
> Does it solve your problem?

Yes, it works now, thanks alot.
