### ISSUE TITLE
Class names in default package clash with JVM names for primitive types (such as B or I)

### ISSUE THREAD

**Issue by vnermolaev** [Kotlin/kotlinx.serialization#1353]
**Bug**: Inner classes are assigned incorrect serializers for some specific class names.

The following segment showcases the issue
```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

fun main() {
    println(Json.encodeToString(Outer.serializer(), Outer()))
}

@Serializable
class Outer(val inner: List<I> = listOf(I()))

@Serializable
class I(val ints: List<Int> = listOf(0))
```
Now, `SerialDescriptor` for field `inner` is `kotlin.collections.ArrayList(PrimitiveDescriptor(kotlin.Int))`, which leads to this stacktrace, which is incorrect. This error leads to the following stacktrace.

```
Exception in thread "main" java.lang.ClassCastException: I cannot be cast to java.lang.Number
	at kotlinx.serialization.internal.IntSerializer.serialize(Primitives.kt:102)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:223)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:71)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:223)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:71)
	at Outer.write$Self(main.kt:9)
	at Outer$$serializer.serialize(main.kt)
	at Outer$$serializer.serialize(main.kt:9)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:223)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:73)
	at MainKt.main(main.kt:5)
	at MainKt.main(main.kt)
```

If `I` is renamed to, say, `I0`, everything works as expected.
Additionally, if `I` is renamed to `B`, the respective `SerialDescriptor` for `inner` is `kotlin.collections.ArrayList(PrimitiveDescriptor(kotlin.Byte))`, so there is some correlation, I did not verify it further.

 - Kotlin version: 1.4.30
 - Library version: 1.1.0
 - Kotlin platforms: JVM
 - Gradle version: bundled 203.7148.57

Further research confirms the assumption above. See [the plugin source
](https://github.com/JetBrains/kotlin/blob/master/plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt#L166)
In particular
```kotlin
        "B", "kotlin.Byte" -> "ByteSerializer"
        "S", "kotlin.Short" -> "ShortSerializer"
        "I", "kotlin.Int" -> "IntSerializer"
        "F", "kotlin.Float" -> "FloatSerializer"
        "D", "kotlin.Double" -> "DoubleSerializer"
        "C", "kotlin.Char" -> "CharSerializer"
```
which prevents the developer to have classes called as above. I know it is not often the case that a class called with a single capital letter, but, indeed, it is the case for quick and dirty trial apps. Would have been great to have this documented.

**Comment by pdvrieze** [comment]
I suspect this is due to these letters being the JVM internal type names for the primitives.

**Comment by sandwwraith** [comment]
This is default JVM platform, not IR, right?
