### ISSUE TITLE
Android | Proguard | Serializer for class 'JsonElement' is not found

### ISSUE THREAD

**Issue by Bombo** [Kotlin/kotlinx.serialization#1355]
Maybe this is intentional, so please let me know if that is the case, but everything works fine for debug builds with proguard disabled.

**To Reproduce**
Certain fields in our data contract are dynamic, so I don't necessarily know the content and structure of those fields. To support this, I'm using the `kotlinx.serialization.json.JsonObject` type for those fields:
```Kotlin
@Serializable
data class MyClass(
  val known1: String? = null,
  val known2: Boolean = false,
  val unknown: JsonObject? = null
)
```
As stated above, everything works fine when running regular debug builds, but things go sideways for a release build with Proguard/R8 minification enabled:
```
java.lang.ExceptionInInitializerError
        at kotlinx.serialization.json.q.<clinit>(JsonElementSerializers.kt:2)
        at […]$$serializer.deserialize(Unknown Source:132)
        at […]$$serializer.deserialize([…].kt:1)
        at kotlinx.serialization.json.t.s.c(Polymorphic.kt:12)
        at kotlinx.serialization.json.t.v.B(StreamingJsonDecoder.kt:1)
        at kotlinx.serialization.encoding.a.I(AbstractDecoder.kt:1)
        at kotlinx.serialization.encoding.a.v(AbstractDecoder.kt:2)
        at […]serializer.deserialize(Unknown Source:417)
        at […]$$serializer.deserialize([…].kt:1)
        at kotlinx.serialization.json.t.s.c(Polymorphic.kt:12)
        at kotlinx.serialization.json.t.v.B(StreamingJsonDecoder.kt:1)
        at kotlinx.serialization.json.a.b(Json.kt:3)
        at […]$Companion.a([…].kt:2)
        at […].h.a.M([…].kt:10)
        at […].h.a$d.a([…].kt:32)
        at […].h.a$d$a.p(Unknown Source:16)
        at kotlin.e0.k.a.a.d(ContinuationImpl.kt:3)
        at kotlinx.coroutines.b3.U0(Builders.common.kt:4)
        at kotlinx.coroutines.a.d(AbstractCoroutine.kt:3)
        at kotlin.e0.k.a.a.d(ContinuationImpl.kt:10)
        at kotlinx.coroutines.z0.run(DispatchedTask.kt:19)
        at kotlinx.coroutines.f3.b.E(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.f3.b$a.c(CoroutineScheduler.kt:4)
        at kotlinx.coroutines.f3.b$a.m(CoroutineScheduler.kt:4)
        at kotlinx.coroutines.f3.b$a.run(CoroutineScheduler.kt:1)
     Caused by: kotlinx.serialization.h: Serializer for class 'f' is not found.
    Mark the class as @Serializable or provide the serializer explicitly.
        at kotlinx.serialization.o.y0.d(Platform.common.kt:3)
        at kotlinx.serialization.o.x0.k(Platform.kt:1)
        at kotlinx.serialization.k.d(Serializers.kt:8)
        at kotlinx.serialization.j.b(Unknown Source:1)
        at kotlinx.serialization.k.a(Serializers.kt:4)
        at kotlinx.serialization.k.e(Serializers.kt:8)
        at kotlinx.serialization.k.c(Serializers.kt:1)
        at kotlinx.serialization.j.a(Unknown Source:1)
        at kotlinx.serialization.json.q$a.<init>(JsonElementSerializers.kt:2)
        at kotlinx.serialization.json.q$a.<clinit>(JsonElementSerializers.kt:1)
        	... 25 more
```
It took me a while to find that the class `'f'` above is actually `JsonElement`.

I have the suggested Proguard rules applied, and also added rules for `JsonElement`, `JsonObject` and both their serializers for good measure, but couldn't get it to run.

As `JsonElementSerializer` is `internal`, I couldn't specify that serializer explicitly for my field, so I resorted to use my own serializer (which probably has its own issues, but it works for me):
```Kotlin
object JsonSerializer : KSerializer<JsonObject> {
  override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("JsonObject", PrimitiveKind.STRING)

  override fun deserialize(decoder: Decoder): JsonObject {
    val input = decoder as JsonDecoder
    return input.decodeJsonElement() as JsonObject
  }

  override fun serialize(encoder: Encoder, value: JsonObject) {
    val output = encoder as JsonEncoder
    output.json.encodeToJsonElement(JsonObject.serializer(), value)
  }
}

@Serializable
data class MyClass(
  val known1: String? = null,
  val known2: Boolean = false,
  @Serializable(with = JsonSerializer::class)
  val unknown: JsonObject? = null
)
```

**Expected behavior**
Using `JsonObject` as a field type for a `@Serializable` `data class` should work, with or without Proguard.

**Environment**
 - Kotlin version: 1.4.21 (tried also 1.4.31)
 - Library version: 1.0.1 (tried also 1.1.0)
 - Kotlin platforms: JVM
 - Gradle version: 6.8

**Comment by Bombo** [comment]
*Note*: Once I get some time, I will try and create a basic project in Android Studio to reproduce the issue.

**Comment by sandwwraith** [comment]
Recent versions of the library include all necessary ProGuard rules. Please re-open if the issue is still reproducible on recent releases.
