### ISSUE TITLE
The backend generates an invalid function for write$self

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#136]
The signature generated for `write$self` is invalid as it doesn't declare the type information (as retrieved with `javap -c`).
```
public void write$Self(kotlinx.serialization.KOutput, kotlinx.serialization.KSerialClassDesc, kotlinx.serialization.KSerializer<T>, kotlinx.serialization.KSerializer<T>);
```
This is problematic when using the class in Android with databinding as kapt chokes on this. FWIW, a comparable signature is: `public final <T> T foo(T);`

The error from kapt is:
```
e: /home/pdvrieze/IdeaProjects/ProcessManager/PMEditor/build/tmp/kapt3/stubs/release/nl/adaptivity/process/diagram/android/ParcelableActivity.java:6: error: cannot access ActivityBase
public final class ParcelableActivity extends nl.adaptivity.process.diagram.DrawableActivity implements android.os.Parcelable {
             ^
  bad class file: /home/pdvrieze/IdeaProjects/ProcessManager/PE-common/android/build/intermediates/intermediate-jars/release/classes.jar(nl/adaptivity/process/processModel/ActivityBase.class)
    undeclared type variable: T
    Please remove or make sure it appears in the correct subdirectory of the classpath.
e: java.lang.IllegalStateException: failed to analyze: java.lang.AssertionError: annotation tree hasn't been attributed yet: @kotlin.Metadata(mv = {1, 1, 10}, bv = {1, 0, 2}, k = 1, d1 = {"\u0000N\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000b\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0006\u0018\u0000 \u001c2\u00020\u00012\u00020\u0002:\u0001\u001cB\u001f\b\u0016\u0012\u000e\u0010\u0003\u001a\n\u0012\u0002\b\u0003\u0012\u0002\b\u00030\u0004\u0012\u0006\u0010\u0005\u001a\u00020\u0006\u00a2\u0006\u0002\u0010\u0007B\u000f\b\u0012\u0012\u0006\u0010\b\u001a\u00020\t\u00a2\u0006\u0002\u0010\nB-\u0012\u000e\u0010\u000b\u001a\n\u0012\u0002\b\u0003\u0012\u0002\b\u00030\f\u0012\u0016\b\u0002\u0010\r\u001a\u0010\u0012\u0004\u0012\u00020\u000f\u0012\u0006\u0012\u0004\u0018\u00010\u00100\u000e\u00a2\u0006\u0002\u0010\u0011J\b\u0010\u0012\u001a\u00020\u0013H\u0016J\b\u0010\u0014\u001a\u0004\u0018\u00010\u0015J\u0010\u0010\u0016\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\tH\u0002J\u0010\u0010\u0019\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\tH\u0002J\u0018\u0010\u001a\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\t2\u0006\u0010\u001b\u001a\u00020\u0013H\u0016\u00a8\u0006\u001d"}, d2 = {"Lnl/adaptivity/process/diagram/android/ParcelableActivity;", "Lnl/adaptivity/process/diagram/DrawableActivity;", "Landroid/os/Parcelable;", "orig", "Lnl/adaptivity/process/processModel/Activity;", "compat", "", "(Lnl/adaptivity/process/processModel/Activity;Z)V", "source", "Landroid/os/Parcel;", "(Landroid/os/Parcel;)V", "builder", "Lnl/adaptivity/process/processModel/Activity$Builder;", "buildHelper", "Lnl/adaptivity/process/processModel/ProcessModel$BuildHelper;", "Lnl/adaptivity/process/diagram/DrawableProcessNode;", "Lnl/adaptivity/process/diagram/DrawableProcessModel;", "(Lnl/adaptivity/process/processModel/Activity$Builder;Lnl/adaptivity/process/processModel/ProcessModel$BuildHelper;)V", "describeContents", "", "getUserTask", "Lnl/adaptivity/process/tasks/EditableUserTask;", "writeDefines", "", "dest", "writeResults", "writeToParcel", "flags", "Companion", "PMEditor_release"})
        at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:135)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:405)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:920)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:950)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:919)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:404)
        at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: annotation tree hasn't been attributed yet: @kotlin.Metadata(mv = {1, 1, 10}, bv = {1, 0, 2}, k = 1, d1 = {"\u0000N\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000b\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0006\u0018\u0000 \u001c2\u00020\u00012\u00020\u0002:\u0001\u001cB\u001f\b\u0016\u0012\u000e\u0010\u0003\u001a\n\u0012\u0002\b\u0003\u0012\u0002\b\u00030\u0004\u0012\u0006\u0010\u0005\u001a\u00020\u0006\u00a2\u0006\u0002\u0010\u0007B\u000f\b\u0012\u0012\u0006\u0010\b\u001a\u00020\t\u00a2\u0006\u0002\u0010\nB-\u0012\u000e\u0010\u000b\u001a\n\u0012\u0002\b\u0003\u0012\u0002\b\u00030\f\u0012\u0016\b\u0002\u0010\r\u001a\u0010\u0012\u0004\u0012\u00020\u000f\u0012\u0006\u0012\u0004\u0018\u00010\u00100\u000e\u00a2\u0006\u0002\u0010\u0011J\b\u0010\u0012\u001a\u00020\u0013H\u0016J\b\u0010\u0014\u001a\u0004\u0018\u00010\u0015J\u0010\u0010\u0016\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\tH\u0002J\u0010\u0010\u0019\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\tH\u0002J\u0018\u0010\u001a\u001a\u00020\u00172\u0006\u0010\u0018\u001a\u00020\t2\u0006\u0010\u001b\u001a\u00020\u0013H\u0016\u00a8\u0006\u001d"}, d2 = {"Lnl/adaptivity/process/diagram/android/ParcelableActivity;", "Lnl/adaptivity/process/diagram/DrawableActivity;", "Landroid/os/Parcelable;", "orig", "Lnl/adaptivity/process/processModel/Activity;", "compat", "", "(Lnl/adaptivity/process/processModel/Activity;Z)V", "source", "Landroid/os/Parcel;", "(Landroid/os/Parcel;)V", "builder", "Lnl/adaptivity/process/processModel/Activity$Builder;", "buildHelper", "Lnl/adaptivity/process/processModel/ProcessModel$BuildHelper;", "Lnl/adaptivity/process/diagram/DrawableProcessNode;", "Lnl/adaptivity/process/diagram/DrawableProcessModel;", "(Lnl/adaptivity/process/processModel/Activity$Builder;Lnl/adaptivity/process/processModel/ProcessModel$BuildHelper;)V", "describeContents", "", "getUserTask", "Lnl/adaptivity/process/tasks/EditableUserTask;", "writeDefines", "", "dest", "writeResults", "writeToParcel", "flags", "Companion", "PMEditor_release"})
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:118)
        at com.sun.tools.javac.comp.Check.validateTypeAnnotation(Check.java:2745)
        at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitAnnotation(Attr.java:4484)
        at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2317)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at com.sun.tools.javac.tree.TreeScanner.visitModifiers(TreeScanner.java:315)
        at com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2343)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.comp.Attr$TypeAnnotationsValidator.visitClassDef(Attr.java:4566)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at com.sun.tools.javac.comp.Attr.validateTypeAnnotations(Attr.java:4473)
        at com.sun.tools.javac.code.TypeAnnotations$2.run(TypeAnnotations.java:142)
        at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:155)
        at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:45)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:257)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:212)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:95)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:84)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:374)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:64)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:365)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:130)
        ... 29 more
```

**Comment by pdvrieze** [comment]
Btw. The java compiler also chokes on this:
```
/home/pdvrieze/IdeaProjects/ProcessManager/ProcessEngine/servlet/src/main/java/nl/adaptivity/process/engine/servlet/ServletProcessEngine.java:40: error: cannot access RootProcessModelBase
import nl.adaptivity.process.processModel.RootProcessModelBase;
                                         ^
  bad class file: /home/pdvrieze/IdeaProjects/ProcessManager/PE-common/jvm/build/classes/kotlin/main/nl/adaptivity/process/processModel/RootProcessModelBase.class
    undeclared type variable: T
    Please remove or make sure it appears in the correct subdirectory of the classpath.

```

**Comment by pdvrieze** [comment]
I've created a pull request against rr/kotlinx.serialization (https://github.com/JetBrains/kotlin/pull/1684). It fixes the generated code for me.
