### ISSUE TITLE
ArrayIndexOutOfBoundsException on serialize

### ISSUE THREAD

**Issue by Lewik** [Kotlin/kotlinx.serialization#139]
Got `java.lang.ArrayIndexOutOfBoundsException`  on 0.5.0
```
java.lang.ArrayIndexOutOfBoundsException: 39
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:543)
    at java.lang.StringBuilder.append(StringBuilder.java:175)
    at kotlinx.serialization.json.JSON$Composer.printQuoted(JSON.kt:213)
    at kotlinx.serialization.json.JSON$JsonOutput.writeStringValue(JSON.kt:162)
    at kotlinx.serialization.json.JSON$JsonOutput.writeElement(JSON.kt:126)
    at kotlinx.serialization.KOutput.writeNullableSerializableElementValue(Serialization.kt:197)
    at com.tavrida.electroscada.entities.LineState.write$Self(LineState.kt) <- my code
```

0.4.2 do not have that bug
@sandwwraith said this bug could be performance optimisation bug.
Sorry, I can't provide data. It's too complex. And I can't determine wich data cause this =(

**Comment by sandwwraith** [comment]
After a little investigation, it was found that such an error can be thrown from `StringBuilder` only when it is accessed from multiple threads, since this class is not thread-safe. Since `JSON.stringify` uses internal modes cache, this method is also *not therad-safe* and therefore whole JSON class is not.

**Comment by sandwwraith** [comment]
@elizarov we haven't discussed this problem explicitly, but while compiler-generated code is stateless and thread-safe, some output formats could not be. Should we strive to make them thread-safe? E.g. jackson's `ObjectMapper` is thread-safe AFAIR and Spring usually expects from beans to be thread-safe. On the other side, `JSON` instances are lightweight and there could be no harm to create them per thread or per request. If thread-safety indeed needed, then open corresponding feature request.

**Comment by Lewik** [comment]
I used `JSON.stringify()` in some kind of controllers, that executes in parallel threads.

**Comment by coder82** [comment]
when will this be released?

**Comment by antanas-arvasevicius** [comment]
Yeah, and the fun fact that we used JSON.stringify in ktor where everything works in parallel.
Shouldn't all non thread-safe or stateful APIs be clearly documented? Understand that its pre release version of serialization but still everyone would be happier by that.

**Comment by Lewik** [comment]
Than do not forget about CBOR please.

**Comment by sandwwraith** [comment]
@coder82 I suppose soon. You also can try to build library by yourself
