### ISSUE TITLE
ArrayIndexOutOfBounds in Serialization

### ISSUE THREAD

**Issue by alexkamp** [Kotlin/kotlinx.serialization#14]
hey, 

I am getting: 

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at kotlinx.serialization.internal.SerialClassDescImpl.getElementName(SerialClassDescImpl.kt:44)
	at kotlinx.serialization.json.JSON$JsonOutput.writeElement(JSON.kt:243)
	at kotlinx.serialization.ElementValueOutput.writeStringElementValue(Serialization.kt:312)
	at de.bugreport.SpecialItem.write$Self(structure.kt)
	at de.bugreport.Item$Companion.save(structure.kt)
	at de.bugreport.Item$Companion.save(structure.kt:16)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:133)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:174)
	at kotlinx.serialization.internal.MapEntrySerializer.save(CollectionSerializers.kt:191)
	at kotlinx.serialization.internal.MapEntrySerializer.save(CollectionSerializers.kt:183)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:133)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:174)
	at kotlinx.serialization.internal.ListLikeSerializer.save(CollectionSerializers.kt:49)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:133)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:174)
	at de.bugreport.Registry.write$Self(structure.kt)
	at de.bugreport.Registry$Companion.save(structure.kt)
	at de.bugreport.Registry$Companion.save(structure.kt:7)
	at kotlinx.serialization.KOutput.write(Serialization.kt:93)
	at kotlinx.serialization.json.JSON.stringify(JSON.kt:36)
	at kotlinx.serialization.json.JSON$Companion.stringify(JSON.kt:53)
	at TestSerialization.test(TestSerialization.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)

```

Here is the class structure:

```
@Serializable
data class Registry(private val map: Map<String,Item>) {

   @Transient
   val size: Int = map.size
    
    
}

@Serializable
sealed class Item {
    abstract val name: String
}

@Serializable
data class SpecialItem(
        override val name: String
): Item()
```

and here is how I serialize it:

```
class TestSerialization {
    
    @Test
    fun test() {
        val registry = Registry(mapOf("Hello" to SpecialItem("Hello")))
        
        println(JSON.Companion.stringify(registry))
    }
    
}
```

**Comment by sandwwraith** [comment]
Don't add `@Serializable` to abstract classes or interfaces, this action has another semantic (generate a synthetic implementation for deserializing), which we don't support yet.

With `@Serializable` only in `SpecialItem` your example works fine

**Comment by wilonth** [comment]
@sandwwraith Doesn't seem to work for me, without `@Serializable` on the sealed class, it errors out:


> kotlinx.serialization.SerializationException: Can't locate companion serializer for class ...

I'm using version 0.3.
