### ISSUE TITLE
JSON parser fails on string values containing escaped JSON

### ISSUE THREAD

**Issue by abissell** [Kotlin/kotlinx.serialization#144]
Example:
```kotlin
val stringMapSerializer = (StringSerializer to StringSerializer).map
val json = """{"key1":"value1","key2":"[1, \"2\", null, true]"}"""
val parsedMap = JSON.parse(stringMapSerializer, json)
println(parsedMap)
```
Output:
```
java.lang.IllegalStateException: Shall parse complete string
	at kotlinx.serialization.json.JSON.parse(JSON.kt:50)
	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:59)
```

**Comment by abissell** [comment]
Nevermind ... reading my IntelliJ test output incorrectly
