### ISSUE TITLE
Cannot write custom serializer for inline class

### ISSUE THREAD

**Issue by MikolajKakol** [Kotlin/kotlinx.serialization#1442]
I was trying to write custom serialization adapter for Duration class which is inline and I failed.

**To Reproduce**
Use following test:
```
class InlineClassSerializationTest {

    object InlineWrapperSerializer : KSerializer<InlineWrapper> {
        override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("InlineWrapper", PrimitiveKind.INT)
        override fun serialize(encoder: Encoder, value: InlineWrapper) = encoder.encodeInt(value.intVal)
        override fun deserialize(decoder: Decoder) = InlineWrapper(decoder.decodeInt())
    }

    inline class InlineWrapper(val intVal: Int)

    @Serializable
    class SampleClass(
        @Serializable(InlineWrapperSerializer::class)
        val inlinedValue: InlineWrapper
    )

    @Test
    fun test() {
        val json = """{"inlinedValue":  4}"""

        val result = Json.decodeFromString<SampleClass>(json)

        result.inlinedValue.intVal shouldBe 4
    }
}
```
It will fail to compile on JVM and Native. With stacktrace:
```
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated
   L0
    ICONST_1
    DUP
    ILOAD 1
    IAND
    IF_ICMPEQ L1
    ILOAD 1
    ICONST_1
    GETSTATIC pl/lib/serialization/InlineClassSerializationTest$SampleClass$$serializer.INSTANCE : Lpl/lib/serialization/InlineClassSerializationTest$SampleClass$$serializer;
    CHECKCAST kotlinx/serialization/KSerializer
    INVOKEINTERFACE kotlinx/serialization/KSerializer.getDescriptor ()Lkotlinx/serialization/descriptors/SerialDescriptor; (itf)
    INVOKESTATIC kotlinx/serialization/internal/PluginExceptionsKt.throwMissingFieldException (IILkotlinx/serialization/descriptors/SerialDescriptor;)V
   L1
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ALOAD 0
    ILOAD 2
    PUTFIELD pl/lib/serialization/InlineClassSerializationTest$SampleClass.inlinedValue : I
    RETURN
   L2
    LOCALVARIABLE this Lpl/lib/serialization/InlineClassSerializationTest$SampleClass; L0 L2 0
    LOCALVARIABLE seen1 I L0 L2 1
    LOCALVARIABLE inlinedValue Lpl/lib/serialization/InlineClassSerializationTest$InlineWrapper; L0 L2 2
    LOCALVARIABLE serializationConstructorMarker Lkotlinx/serialization/internal/SerializationConstructorMarker; L0 L2 3
    MAXSTACK = 3
    MAXLOCALS = 4

File being compiled: (27,5) in /Users/mikolajkakol/Projects/Sources/api/serialization/src/commonTest/kotlin/pl/lib/serialization/InlineClassSerializationTest.kt
The root cause org.jetbrains.kotlin.codegen.CompilationException was thrown at: org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:968)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:498)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:260)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:165)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt.generateMethod(JVMCodegenUtil.kt:144)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.generateInternalConstructor(SerializableCodegenImpl.kt:86)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:29)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl$Companion.generateSerializableExtensions(SerializableCodegenImpl.kt:53)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationCodegenExtension.generateClassSyntheticParts(SerializationCodegenExtension.kt:29)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:448)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:132)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:312)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:176)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:80)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:129)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:77)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:62)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:595)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:211)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:386)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:110)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:286)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:99)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:114)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1659)
	at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
<init> (ILpl/lib/serialization/InlineClassSerializationTest$InlineWrapper;Lkotlinx/serialization/internal/SerializationConstructorMarker;)V:
   L0
    ICONST_1
    DUP
    ILOAD 1
    IAND
    IF_ICMPEQ L1
    ILOAD 1
    ICONST_1
    GETSTATIC pl/lib/serialization/InlineClassSerializationTest$SampleClass$$serializer.INSTANCE : Lpl/lib/serialization/InlineClassSerializationTest$SampleClass$$serializer;
    CHECKCAST kotlinx/serialization/KSerializer
    INVOKEINTERFACE kotlinx/serialization/KSerializer.getDescriptor ()Lkotlinx/serialization/descriptors/SerialDescriptor; (itf)
    INVOKESTATIC kotlinx/serialization/internal/PluginExceptionsKt.throwMissingFieldException (IILkotlinx/serialization/descriptors/SerialDescriptor;)V
   L1
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ALOAD 0
    ILOAD 2
    PUTFIELD pl/lib/serialization/InlineClassSerializationTest$SampleClass.inlinedValue : I
    RETURN
   L2
    LOCALVARIABLE this Lpl/lib/serialization/InlineClassSerializationTest$SampleClass; L0 L2 0
    LOCALVARIABLE seen1 I L0 L2 1
    LOCALVARIABLE inlinedValue Lpl/lib/serialization/InlineClassSerializationTest$InlineWrapper; L0 L2 2
    LOCALVARIABLE serializationConstructorMarker Lkotlinx/serialization/internal/SerializationConstructorMarker; L0 L2 3
    MAXSTACK = 3
    MAXLOCALS = 4

File is unknown
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:92)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:961)
	... 58 more
Caused by: java.lang.AssertionError: AFTER mandatory stack transformations: incorrect bytecode
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:28)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
	at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.kt:62)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:70)
	... 59 more
Caused by: java.lang.RuntimeException: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 16: Expected I, but found R
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:34)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.analyze(MethodTransformer.java:44)
	at org.jetbrains.kotlin.codegen.optimization.MethodVerifier.transform(MethodVerifier.kt:26)
	... 62 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 16: Expected I, but found R
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:291)
	at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:31)
	... 64 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Expected I, but found R
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:103)
	at org.jetbrains.org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:43)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:290)
	at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:187)
	... 65 more


```

**Expected behavior**
It should work, so I can write custom serializers for duration like this:
```
object DurationInSecondsAsIntSerializer : KSerializer<Duration> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("DurationInSeconds", PrimitiveKind.INT)
    override fun serialize(encoder: Encoder, value: Duration) = encoder.encodeInt(value.toInt(DurationUnit.SECONDS))
    override fun deserialize(decoder: Decoder): Duration = decoder.decodeInt().toDuration(DurationUnit.SECONDS)
}

```
**Environment**
 - Kotlin version: 1.4.31
 - Library version: 1.1.0
 - Kotlin platforms: JVM,Native
 - Gradle version: 7.0

**Comment by pdvrieze** [comment]
Are you using the ir backend. Inline classes don't work without enabling this new backend.

**Comment by MikolajKakol** [comment]
I think I do... To be sure I added `kotlinOptions.useIR = true` in `gradle.properties`.

If I were to change intlined value from Int to String it will compile just fine but fails with:
```

class pl.lib.serialization.InlineClassSerializationTest$InlineWrapper cannot be cast to class java.lang.String (pl.lib.serialization.InlineClassSerializationTest$InlineWrapper is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class pl.lib.serialization.InlineClassSerializationTest$InlineWrapper cannot be cast to class java.lang.String (pl.lib.serialization.InlineClassSerializationTest$InlineWrapper is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at pl.lib.serialization.InlineClassSerializationTest$SampleClass$$serializer.deserialize(InlineClassSerializationTest.kt)
	at pl.lib.serialization.InlineClassSerializationTest$SampleClass$$serializer.deserialize(InlineClassSerializationTest.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
```

**Comment by fvasco** [comment]
Please consider that `inline class` is experimental and [it has been replaced by experimental `value class`](https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md#inline-classes-are-user-defined-value-classes) in Kotlin 1.5.

**Comment by MikolajKakol** [comment]
@fvasco sure, I'm not storming here, just asking or pointing potential bug :)

**Comment by MikolajKakol** [comment]
Tested on kotlin 1.5.10 and it works.
