### ISSUE TITLE
Can not serialize string with Json

### ISSUE THREAD

**Issue by LorenzooG** [Kotlin/kotlinx.serialization#1488]
**Describe the bug**
I can't serialize a large string with kotlinx.serialization:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 258 out of bounds for length 258
	at kotlinx.serialization.json.internal.JsonStringBuilder.appendStringSlowPath(JsonStringBuilder.kt:99)
	at kotlinx.serialization.json.internal.JsonStringBuilder.appendQuoted(JsonStringBuilder.kt:61)
	at kotlinx.serialization.json.internal.Composer.printQuoted(Composers.kt:42)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeString(StreamingJsonEncoder.kt:203)
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:139)
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:136)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
	at com.lorenzoog.diekeditora.web.tests.graphql.GraphQLTestClientKt.main(GraphQLTestClient.kt:88)
	at com.lorenzoog.diekeditora.web.tests.graphql.GraphQLTestClientKt.main(GraphQLTestClient.kt)
```

**To Reproduce**

This is the code used:
```kt
fun main() {
    val input = "\$input"

    Json.encodeToString(
        """
        mutation CreateUser($input: UserInput!) {
            createUser(input: $input) {
                user {
                    name
                    username
                    email
                    createdAt
                    emailVerifiedAt
                    deletedAt
                    updatedAt
                }
            }
        }
        """.trimIndent()
    ).let {
        println("IT $it")
    }
}
```

**Expected behavior**

Prints this output in the prompt:
```
IT "mutation CreateUser($input: UserInput!) {\r\n    createUser(input: $input) {\r\n        user {\r\n            name\r\n            username\r\n            email\r\n            createdAt\r\n            emailVerifiedAt\r\n            deletedAt\r\n            updatedAt\r\n        }\r\n    }\r\n}"
```

**Environment**
 - Kotlin version: 1.4.32
 - Library version: 1.2.1
 - Kotlin platforms: Kotlin/JVM
 - Gradle version: 7.0
 - IDE version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)
 - Other relevant context: OS: Ubuntu 20.10; JRE: Amazon Corretto 11.0.10

**Comment by qwwdfsad** [comment]
Could you please ensure that you are using `1.2.1` version? E.g. reset IDEA/Gradle caches and please check out that Gradle actually selects the dependency.

I've checked it on the fresh project, the expected string is printed correctly with 1.2.1 and fails with 1.2.0

**Comment by LorenzooG** [comment]
I reseted the gradle/intellij cache and it worked fine, tnx.
