### ISSUE TITLE
Unresolved class: interface java.util.List for calling `JsonArray.serializer()`

### ISSUE THREAD

**Issue by dzwicker** [Kotlin/kotlinx.serialization#1507]
**Describe the bug**
We have a custom quarkus extension to help with common tasks setup the kotlinx.serialiazation to be used in reasteasy projects. Updating kotlin from 1.3.xx to 1.4.xx breaks our buildsystem with a `Unresolved class: interface java.util.List` exception. I have no idea why. Used all versions of kotlin 1.4 and jdks from 1.8 to 11.xxx. The errors is the same. Any hint would be great.

**Environment**
 - Kotlin version: [1.4.20 - 1.4.32]
 - Library version: [1.x.x]
 - Kotlin platforms: [JVM]
 - Gradle version: [6.8.3]
 - OS: macOS 11.3.1
 - JRE 1.8 - 11.0.11

```java
...
Caused by: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: interface java.util.List
        at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:325)
        at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
        at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:47)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:123)
        at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:132)
        at kotlinx.serialization.json.JsonArraySerializer$JsonArrayDescriptor.<init>(JsonElementSerializers.kt:234)
        at kotlinx.serialization.json.JsonArraySerializer$JsonArrayDescriptor.<clinit>(JsonElementSerializers.kt:171)
        at kotlinx.serialization.json.JsonArraySerializer.<clinit>(JsonElementSerializers.kt:176)
        at kotlinx.serialization.json.JsonArray$Companion.serializer(JsonElement.kt)
        at de.authada.quarkus.kotlinx.KotlinXProcessor.<clinit>(KotlinXProcessor.kt:132)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:186)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:101)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:307)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:141)
        at io.quarkus.gradle.tasks.QuarkusBuild.buildQuarkus(QuarkusBuild.java:162)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
...
```

**Comment by dzwicker** [comment]
For `JsonObject.serializer()` it can not look up `String`

```java
Caused by: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class java.lang.String
        at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:325)
        at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
        at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:47)
        at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:123)
        at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:127)
        at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<init>(JsonElementSerializers.kt:234)
        at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<clinit>(JsonElementSerializers.kt:145)
        at kotlinx.serialization.json.JsonObjectSerializer.<clinit>(JsonElementSerializers.kt:150)
        at kotlinx.serialization.json.JsonObject$Companion.serializer(JsonElement.kt)

```

**Comment by sandwwraith** [comment]
I'm not sure what exactly can cause this, but it is likely not a problem of the library. `kotlin.jvm.internal.Reflection.typeOf` is an experimental compiler intrinsic that produces KType, which servers the same purpose as Java's type token (e.g. Jackson's `TypeReference`). So it is either a problem with this intrinsic or kotlin-reflect (although it shouldn't be required, in theory). In either case, please report this issue to the main Kotlin's tracker (kotl.in/issue)

**Comment by sandwwraith** [comment]
Maybe you have some cryptic setup problem when kotlin stdlib or java stdlib is missing from classpath, although I'm not sure this is even possible
