### ISSUE TITLE
serializing instances of classes with certain single character names causes ClassCastException

### ISSUE THREAD

**Issue by LastExceed** [Kotlin/kotlinx.serialization#1523]
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.*

fun main() {
	println(Json.encodeToString(A())) //works
	println(Json.encodeToString(B())) //breaks
}

@Serializable
class A

@Serializable
class B
```
**expected:**
```
{}
{}
```
**got:**
```
{}
Exception in thread "main" java.lang.ClassCastException: class B cannot be cast to class java.lang.Number (B is in unnamed module of loader 'app'; java.lang.Number is in module java.base of loader 'bootstrap')
	at kotlinx.serialization.internal.ByteSerializer.serialize(Primitives.kt:87)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
	at MainKt.main(main.kt:16)
	at MainKt.main(main.kt)
```

**problematic characters:** `BCDFIJSTZ`

**Workaround:** use other characters

**Potentially related:** #1524 

---
**Reproduced on** *(but not necessarily exclusive to)*:
 - Kotlin version: 1.5.10
 - Library version: 0.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0.1
 - IDE version: IntellijIDEA 2021.1.1
 - Operating system: Win10

**Comment by sandwwraith** [comment]
See #1353.

Also, using a package for your classes (so it would be `com.myapp.B` instead of `B`) would help
