### ISSUE TITLE
serializing instances of classes with names that are a different case of other class's name causes NoClassDefFoundError

### ISSUE THREAD

**Issue by LastExceed** [Kotlin/kotlinx.serialization#1524]
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.*

fun main() {
	println(Json.encodeToString(Foo())) //works
	println(Json.encodeToString(foO())) //breaks
}

@Serializable
class foO

@Serializable
class Foo
```
**expected:**
```
{}
{}
```
**got:**
```
{}
Exception in thread "main" java.lang.NoClassDefFoundError: Foo (wrong name: foO)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at MainKt.main(main.kt:6)
	at MainKt.main(main.kt)
```

**Workaround:** use more unique class names

**Potentially related:** #1523 

---
**Reproduced on** *(but not necessarily exclusive to)*:
 - Kotlin version: 1.5.10
 - Library version: 0.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0.1
 - IDE version: IntellijIDEA 2021.1.1
 - Operating system: Win10

**Comment by sandwwraith** [comment]
This looks like Java Virtual Machine itself has a problem with those classes. If they're not `@Serializable` (try just `foO().toString()`), does problem still exist?
