### ISSUE TITLE
Initialization from Java fails with NoClassDefFoundError because of default method in interface SerializersModuleCollector

### ISSUE THREAD

**Issue by werner77** [Kotlin/kotlinx.serialization#1527]
**Describe the bug**

We initializer the Json configuration with Spring boot 2.4.4 running on Java 11 with kotlinx serialization 1.2.1.

However this fails because of the interface SerializersModuleCollector which contains a default method without the @JvmDefault annotation and/or compiler flag '-Xjvm-default=all' (I guess the latter is impossible due to the jvm target version of 1.6)

See the following stacktrace:

```
Caused by: java.lang.NoClassDefFoundError: kotlinx/serialization/modules/SerializersModuleCollector$DefaultImpls
	at kotlinx.serialization.json.internal.PolymorphismValidator.contextual(PolymorphismValidator.kt:12) ~[kotlinx-serialization-json-jvm-1.2.1.jar!/:na]
	at kotlinx.serialization.modules.SerialModuleImpl.dumpTo(SerializersModule.kt:133) ~[kotlinx-serialization-core-jvm-1.0.0.jar!/:1.0.0]
	at kotlinx.serialization.json.JsonImpl.validateConfiguration(Json.kt:290) ~[kotlinx-serialization-json-jvm-1.2.1.jar!/:na]
	at kotlinx.serialization.json.JsonImpl.<init>(Json.kt:284) ~[kotlinx-serialization-json-jvm-1.2.1.jar!/:na]
	at kotlinx.serialization.json.JsonKt.Json(Json.kt:134) ~[kotlinx-serialization-json-jvm-1.2.1.jar!/:na]
	at org.beatkit.model.support.JsonSerializer.<init>(Serialization.kt:207) ~[beatkit-model-jvm-1.0.0-SNAPSHOT.jar!/:na]
	at com.beatgridmedia.measurementkit.config.WebMvcConfiguration.<init>(WebMvcConfiguration.java:53) ~[classes!/:1.0.0-SNAPSHOT]
```

PolymorphismValidator.kt implements the mentioned interface SerializersModuleCollector, but does not override the default method.

**To Reproduce**

From Java code, from Json.kt call the following function:

```
public fun Json(from: Json = Json.Default, builderAction: JsonBuilder.() -> Unit): Json
```

**Expected behavior**

Initialization succeeds.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 6.9

**Comment by werner77** [comment]
My bad: It was due to an older version of kotlinx-serialization-core (1.0.0) that was lingering in the classpath. The server project explicitly defined the dependency to kotlinx-serialization as well with a different version.
