### ISSUE TITLE
Reflection breaks the serialization/deserialization of JsonObject

### ISSUE THREAD

**Issue by thumannw** [Kotlin/kotlinx.serialization#1534]
Our application environment has some restrictions on reflection usage, so Kotlin serialization seemed to be a good fit. For some reasons (e.g. schema generation) we want to work with `JsonObject` at some places. However, when trying to serialize or decode that, we get
```
kotlinx.serialization.SerializationException: Serializer for class 'JsonElement' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```
Looking into the code, it seems that reflection is used to instantiate the serializer for `JsonElement`. Here is the stacktrace when calling `encodToString` or  `decodeFromJsonElement` on a `JsonObject`:
```
at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:29)
at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:60)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
at kotlinx.serialization.SerializersKt__SerializersKt.builtinSerializer$SerializersKt__SerializersKt(Serializers.kt:96)
at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:84)
at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:59)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:41)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<init>(JsonElementSerializers.kt:237)
at kotlinx.serialization.json.JsonObjectSerializer$JsonObjectDescriptor.<clinit>(JsonElementSerializers.kt)
```

Is there a workaround for this? Unfortunately, the serializer for `JsonElement` is internal.

**Expected behavior**
Reflection is not used when serializing/deserializing `JsonObject`.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platform: JVM
 - Gradle version: 6.8.3
 - JDK: 8

**Comment by sandwwraith** [comment]
Indeed, we probably need to avoid reflective `serializer<T>()` calls in the core.

Out of interest, is your environment GraalVM?

**Comment by thumannw** [comment]
No, we are not using GraalVM, just a standard JRE with SecurityManager configured to deny some reflection accesses.

Do you know how to workaround this problem with the current version? We are currently prototyping a new product and I need to defend the choice for kotlinx.serialization (and Kotlin as well).

**Comment by sandwwraith** [comment]
Unfortunately, the workaround isn't coming to my mind. If you allow reflection read access to the `JsonElement` class and its nested classes, this should be enough.

**Comment by thumannw** [comment]
Thanks for the fix and release. It works now. :clap: :thumbsup:
