### ISSUE TITLE
Contextual serializer fails for map keys

### ISSUE THREAD

**Issue by Sxtanna** [Kotlin/kotlinx.serialization#1551]
**Describe the bug**
Contextual serialization does not work on map keys, even when the serializer descriptor is of STRING primitive kind.

**To Reproduce**

#### Code
```kotlin
@Serializable
data class Pass(val id: Long, @Contextual val uuid: UUID)

@Serializable
data class Fail(val id: Long, val data: Map<@Contextual UUID, String>)

fun main() {
    val uuid = object : KSerializer<UUID> {
        override val descriptor = PrimitiveSerialDescriptor("java.util.UUID", PrimitiveKind.STRING)
    
        override fun serialize(encoder: Encoder, value: UUID) {
            encoder.encodeString(value.toString())
        }
        
        override fun deserialize(decoder: Decoder): UUID {
            return UUID.fromString(decoder.decodeString())
        }
    }
    
    val json = Json {
        serializersModule = SerializersModule {
            contextual(uuid)
        }
    }
    
    println(json.encodeToString(Pass(0, UUID.randomUUID())))
    println(json.encodeToString(Fail(0, mapOf(UUID.randomUUID() to "Hello"))))
}
```

#### Output:
```
{"id":0,"uuid":"e8ccb154-3062-4f29-857e-62ddb2c0d786"}

Exception in thread "main" kotlinx.serialization.json.internal.JsonEncodingException: Value of type 'kotlinx.serialization.ContextualSerializer<UUID>' can't be used in JSON as a key in the map. It should have either primitive or enum kind, but its kind is 'CONTEXTUAL'.
Use 'allowStructuredMapKeys = true' in 'Json {}' builder to convert such maps to [key1, value1, key2, value2,...] arrays.
	at kotlinx.serialization.json.internal.JsonExceptionsKt.InvalidKeyKindException(JsonExceptions.kt:69)
	at kotlinx.serialization.json.internal.WriteModeKt.switchMode(WriteMode.kt:56)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.beginStructure(StreamingJsonEncoder.kt:80)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:274)
	at kotlinx.serialization.encoding.AbstractEncoder.beginCollection(AbstractEncoder.kt:18)
	at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:118)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at c.s.m.r.Fail$$serializer.serialize(contextual_fail.kt:20)
	at c.s.m.r.Fail$$serializer.serialize(contextual_fail.kt:20)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
	at c.s.m.r.Contextual_failKt.main(contextual_fail.kt:55)
	at c.s.m.r.Contextual_failKt.main(contextual_fail.kt)
```

**Expected behavior**
For the library to recognize and use the provided contextual serializer when reading map keys.

**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0
 - IDE version (if bug is related to the IDE): N/A
 - Other relevant context: N/A

**Comment by Sxtanna** [comment]
What makes this even stranger is that you can fully serialize and deserialize maps with contextual types as keys by themselves... ex:

#### Code
```kotlin
val encoded = json.encodeToString(mapOf(UUID.randomUUID() to "Hello"))
println(encoded)
    
val decoded = json.decodeFromString<Map<UUID, String>>(hash)
println(decoded)
```

#### Output
```
{"eaca12fb-b2e8-4b99-8340-6044f121977f":"Hello"}

{eaca12fb-b2e8-4b99-8340-6044f121977f=Hello}
```

**Comment by pdvrieze** [comment]
Looking at the actual code: https://github.com/Kotlin/kotlinx.serialization/blob/f314e7f6463eb456856a63ab1c1d8730c203ca69/formats/json/commonMain/src/kotlinx/serialization/json/internal/WriteMode.kt#L29-L44
it is quite clear what is going on. The code doesn't "resolve" the contextual serializer before making the decision.
