### ISSUE TITLE
Can't locate companion serializer for class class Data

### ISSUE THREAD

**Issue by pannous** [Kotlin/kotlinx.serialization#157]
After wasting 1 hour in IntelliJ, it finally offered option "Add kotlinx... to classpath?" yes.

now there is only one bug left:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate companion serializer for class class Data
	at kotlinx.serialization.SerializationKt.invokeSerializerGetter(Serialization.kt:55)
	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:22)
	at JsonKt.main(json.kt:11)

Process finished with exit code 1
```

running minimal example:
```
import kotlinx.serialization.*
import kotlinx.serialization.json.JSON

@Serializable
data class Data(val a: Int, @Optional val b: String = "42")

fun main(args: Array<String>) {
	println(JSON.stringify(Data(42))) // {"a": 42, "b": "42"}
	val obj = JSON.parse<Data>("""{"a":42}""") // Data(a=42, b="42")
}
```

gradle as on homepage:
```

buildscript {
	ext.kotlin_version = '1.2.50'
	ext.serialization_version = '0.5.1'
	repositories {
		jcenter()
		maven { url "https://kotlin.bintray.com/kotlinx" }
	}

	dependencies {
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
		classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
	}
}

apply plugin: 'kotlin'
apply plugin: 'kotlinx-serialization'

repositories {
	jcenter()
	maven { url "https://kotlin.bintray.com/kotlinx" }
}

dependencies {
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
}
```

possible duplicate of https://github.com/Kotlin/kotlinx.serialization/issues/95

**Comment by sandwwraith** [comment]
Buildscript looks valid. Does the gradle build works for you? Try to run example from `example-jvm` folder

**Comment by sandwwraith** [comment]
Obsolete?
