### ISSUE TITLE
Protobuf is not aware of type parameters with nullable upper bound

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.serialization#1586]
**Describe the bug**

"Nullable" type parameter is detected and handled properly in Json but doesn't work in Protobuf.

**To Reproduce**
```kotlin
@Serializable
class Nulls(val poly: List<@Polymorphic Any?>)

private val module = SerializersModule {
  polymorphic(Any::class, String::class, String.serializer())
}

private val json = Json {
  serializersModule = module
  useArrayPolymorphism = true
}

private val protobuf = ProtoBuf {
  serializersModule = module
}

fun main() {
  println(json.encodeToString(Nulls(listOf("1", "2", "3"))))
  println(json.encodeToString(Nulls(listOf(null)))) // works well with json

  println(protobuf.encodeToHexString(Nulls(listOf("1", "2", "3"))))
  println(protobuf.encodeToHexString(Nulls(listOf(null)))) // CRASH  'null' is not allowed for not-null properties
}
```

The result is 
```
Exception in thread "main" kotlinx.serialization.SerializationException: 'null' is not allowed for not-null properties
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeNull(ProtobufTaggedEncoder.kt:44)
	at kotlinx.serialization.internal.NullableSerializer.serialize(NullableSerializer.kt:25)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:127)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:135)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:127)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:135)
	at app.format.api.impl.Nulls.write$Self(Sandbox.kt:12)
	at app.format.api.impl.Nulls$$serializer.serialize(Sandbox.kt:12)
	at app.format.api.impl.Nulls$$serializer.serialize(Sandbox.kt:12)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:127)
	at kotlinx.serialization.protobuf.ProtoBuf.encodeToByteArray(ProtoBuf.kt:130)
	at kotlinx.serialization.SerialFormatKt.encodeToHexString(SerialFormat.kt:113)
	at app.format.api.impl.SandboxKt.main(Sandbox.kt:45)
	at app.format.api.impl.SandboxKt.main(Sandbox.kt)
```

**Expected behavior**
Nullable type parameters should work in Protobuf as well.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM

**Comment by pdvrieze** [comment]
Protobuf doesn't actually support null values. I've had a look at it: https://github.com/pdvrieze/kotlinx.serialization/tree/protobuf-list-of-nullable-1586 but couldn't come to a more satisfactory solution than changing the error message. While serializing lists of null values can be made to "work" this would amount to omitting all those null values. Deserializing would end up with an empty list. (I didn't make it a pull request as it doesn't do much except change an error message).

There may be a case to always throw an exception when attempting to serialize/deserialize a list of nullable elements, rather than only when encoding a null element (and nothing with decoding)

To solve this, it would be needed to use some sort of null marker, but this would create compatibility issues.

**Comment by cy6erGn0m** [comment]
Well, protobuf doesn't and what a surprise that Kotlin does. It should be a way to workaround it. Why it works well with regular nullable fields and doesn't with collections? 

```kotlin
@Serializable
data class Works(val x: String?, val y: Int?)

@Serializable
data class DoesntWork(val data: Map<String, String?>)
```

**Comment by pdvrieze** [comment]
@cy6erGn0m What the format does is it omits regular nullable fields. It doesn't support optionals (as it can't distinguish between null and the default - and no it isn't smart enough to realise when those are the same). For a list it can't distinguish between an empty list and a null value (both don't encode anything for the list. As said, the way to "handle" this would be to have the format use null/not null markers, in many ways the protobuf format is not as elaborate as the json format with many configuration options.

**Comment by sandwwraith** [comment]
We've decided not to support this case. Because the only way to encode `null` in a list is to omit it, any protobuf encoding/decoding will turn `listOf(null, 1, null)` into just `listOf(1)`. To explicitly mark null presence, one has to use a non-nullable wrapper with nullable property.
