### ISSUE TITLE
IR plugin can't pass generic serializer to a custom serializer

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.serialization#1587]
**Describe the bug**

The IR plugin implementation crashes at attempt to pass actual serializer for generic to a custom serializer

**To Reproduce**
```kotlin

@Serializable
class Holder(@Serializable(MySerializer::class) val items: List<String>)

fun main() {
  println(Json.encodeToString(Holder(listOf("1", "2", "3"))))
}

class MySerializer(val paramSerializer: KSerializer<String>) : KSerializer<List<String>> {
  constructor() : this(String.serializer())

  override val descriptor: SerialDescriptor
    get() = TODO()

  override fun serialize(encoder: Encoder, value: List<String>) {
    TODO()
  }

  override fun deserialize(decoder: Decoder): List<String> {
    TODO()
  }
}
```

Produces:
```
java.lang.AssertionError: No such type argument slot in IrConstructorCallImpl: 0 (total=0).
Symbol: public app.format.api.impl/MySerializer.<init>|7245708574307176896[0]
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpressionKt.throwNoSuchArgumentSlotException(IrMemberAccessExpression.kt:66)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.putTypeArgument(IrMemberAccessExpression.kt:49)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.irInvoke(GeneratorHelpers.kt:234)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.irInvoke(SerializableIrGenerator.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:1041)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.serializerInstance(SerializableIrGenerator.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.formEncodeDecodePropertyCall(GeneratorHelpers.kt:1178)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.formEncodeDecodePropertyCall(SerializableIrGenerator.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.formEncodeDecodePropertyCall$default(GeneratorHelpers.kt:1168)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializeAllProperties(GeneratorHelpers.kt:1127)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.serializeAllProperties(SerializableIrGenerator.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:318)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:275)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.contributeFunction(GeneratorHelpers.kt:71)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.contributeFunction(SerializableIrGenerator.kt:34)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateWriteSelfMethod(SerializableIrGenerator.kt:275)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticMethods(SerializableCodegen.kt:51)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:25)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$Companion.generate(SerializableIrGenerator.kt:337)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:52)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitElement(SerializationLoweringExtension.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitPackageFragment(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:271)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt.runOnFileInOrder(SerializationLoweringExtension.kt:31)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtension.generate(SerializationLoweringExtension.kt:71)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda-1(JvmIrCodegenFactory.kt:126)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:89)
```

**Expected behavior**

It should work the same as in 1.4.x

**Environment**
 - Kotlin version: 1.5.10, 1.5.20
 - Library version: 1.2.1
 - Kotlin platforms: JVM

**Comment by pdvrieze** [comment]
Your code shouldn't need a parameter as you provide a concrete type. Does it also fail if you actually have a generic parameter to `MySerializer` (even if it is bounded to "extend" `String`).

**Comment by cy6erGn0m** [comment]
It also works if I convert serializer to `object`

**Comment by pdvrieze** [comment]
@cy6erGn0m Your serializer has no generic parameter so the plugin expects either an object or a class with default constructor. (It expects one parameter for each generic parameter to the serializer).

**Comment by cy6erGn0m** [comment]
> @cy6erGn0m Your serializer has no generic parameter so the plugin expects either an object or a class with default constructor. (It expects one parameter for each generic parameter to the serializer).

What about the secondary noarg constructor? Why doesn't it invoke it instead?

**Comment by sandwwraith** [comment]
The problem is not with _value_ parameters, but with _type_ parameters. Such declaration would work despite T being unused: `class MySerializer<T: String>(val paramSerializer: KSerializer<String>) : KSerializer<List<String>>`

**Comment by pdvrieze** [comment]
@sandwwraith I noticed the sample has a no-arg secondary constructor. I suspect not picking that one up is a limitation in the plugin (only looking for primary constructors). While I'm not sure where in real code you would need it, it is nevertheless surprising that it doesn't work.

**Comment by Whathecode** [comment]
Related problem, or at least, a very similar exception/stack trace:

```
@Serializable( CustomTestSerializer::class )
class Test<T>( val field: T )

class CustomTestSerializer : KSerializer<Test<*>>
{
    override val descriptor: SerialDescriptor
        get() = TODO()

    override fun deserialize( decoder: Decoder ): Test<*> = TODO()
    override fun serialize( encoder: Encoder, value: Test<*> ) = TODO()
}
```

This also worked in serialization 1.1.0/Kotlin 1.4.31. My [actual use case is to retrieve the serializer of supported types through the custom serializer constructor](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonMain/kotlin/dk/cachet/carp/common/application/data/input/CustomInput.kt#L36).

**Comment by sandwwraith** [comment]
@cy6erGn0m What's the use case for exact `KSerializer<List<String>>` instead of `KSerializer<List<T>>`? The problem is, you may accidentally apply this serializer for list of other types and it would fail on runtime with strange errors.

@Whathecode are you saying that it worked with `constructor ( vararg supportedDataTypes: KClass<*> )`???

**Comment by Whathecode** [comment]
> @Whathecode are you saying that it worked with `constructor ( vararg supportedDataTypes: KClass<*> )`???

It did (does), but [I invoke it manually as a registered polymorph subtype](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonMain/kotlin/dk/cachet/carp/common/infrastructure/serialization/Serialization.kt#L45):

```
polymorphic( Data::class )
{
    subclass(
        CustomInput::class,
        CustomInputSerializer( String::class, Int::class )
    )
}
```
