### ISSUE TITLE
Encode ProtoBuf bytes

### ISSUE THREAD

**Issue by ShreckYe** [Kotlin/kotlinx.serialization#1648]
**Describe the bug**
With the `ProtoBuf` format, it seems a `ByteArray` is encoded as a collection of numbers. How do I encode the raw bytes directly as the `bytes` type in [The Scalar Value Types section in Language Guide](https://developers.google.com/protocol-buffers/docs/proto#scalar)? I see docs and issues doing this for CBOR using the `@ByteString` annotation but couldn't find anything for ProtoBuf. Is this currently supported?

**To Reproduce**
Attach a code snippet or test data if possible.

"EncodeProtobufBytes.kt":
```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToByteArray
import kotlinx.serialization.protobuf.ProtoBuf
import kotlinx.serialization.protobuf.ProtoNumber

@Serializable
class OptionalBytesWrapper(
    @ProtoNumber(1)
    val bytes: ByteArray?
)

fun main() {
    println(ProtoBuf.encodeToByteArray(OptionalBytesWrapper(null)))
}

```

Output:
```
Exception in thread "main" kotlinx.serialization.SerializationException: 'null' is not supported for collection types in ProtoBuf
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeNull(ProtobufTaggedEncoder.kt:44)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeNullableSerializableValue(Encoding.kt:299)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeNullableSerializableValue(ProtobufTaggedEncoder.kt:11)
	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeNullableSerializableElement(ProtobufTaggedEncoder.kt:154)
	at OptionalBytesWrapper.write$Self(EncodeProtobufBytes.kt:6)
	at OptionalBytesWrapper$$serializer.serialize(EncodeProtobufBytes.kt:6)
	at OptionalBytesWrapper$$serializer.serialize(EncodeProtobufBytes.kt:6)
	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:128)
	at kotlinx.serialization.protobuf.ProtoBuf.encodeToByteArray(ProtoBuf.kt:130)
	at EncodeProtobufBytesKt.main(EncodeProtobufBytes.kt:15)
	at EncodeProtobufBytesKt.main(EncodeProtobufBytes.kt)
```

**Expected behavior**
The `ByteArray` should be encoded directly as `bytes` and a null `ByteArray` should be supported.

**Environment**
 - Kotlin version: [1.5.21]
 - Library version: [1.2.2]
 - Kotlin platforms: [JVM]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by shanshin** [comment]
Hi!
According to [Encoding guide](https://developers.google.com/protocol-buffers/docs/encoding#structure) `bytes` encoded as Length-delimited - byte array with its length at the beginning.
Since protobuf does not support the special value `null`, you can use the absence of a value to encode it - which is perceived by the library as a default value.

```
@Serializable
class OptionalBytesWrapper(
    @ProtoNumber(1)
    val bytes: ByteArray? = null
)

fun main() {
    println(ProtoBuf.encodeToByteArray(OptionalBytesWrapper(null)))
}
```

**Comment by ShreckYe** [comment]
@shanshin Thanks. It works! However, I would still wish that there be an annotation to distinguish them explicitly.

**Comment by sandwwraith** [comment]
@ShreckYe Bytes, strings, and embedded messages are all length-delimeted data. Proto format usually don't distinguish them (in the serialized form)

**Comment by ShreckYe** [comment]
@sandwwraith Yeah, I am aware of this. I mean to distinguish such length-delimited data from a collection of data (`repeated` fields).

**Comment by ShreckYe** [comment]
Hi, I just reviewed this issue again. And now I realize that it's not necessary to support encoding a `repeated` field of `Byte`s as it just wastes space. In the packed way, and if every byte is between 0 and 127, it is the same as using a `bytes` field; otherwise a byte takes up to 4 bytes due to the variant encoding. In the unpacked way, it just wastes more space. And if I really need to do this in a rare case, I might just use `Array<Byte>` or `List<Byte>`.

Also as I tested what's in the issue description has been resolved in the latest version.

So I am closing this. Thanks for everything.

**Comment by ShreckYe** [comment]
Sorry I made a mistake. What's in the issue description is still not resolved.

**Comment by pdvrieze** [comment]
@ShreckYe Protobuf packed vs repeated are both valid encodings for the same data (the defaults change between v2 and v3). But due to this it is not possible to distinguish an empty array and a null value.
If you want to encode a null value you will need a (nullable) wrapper object that then contains the array elements (or nothing) inside it.

**Comment by sandwwraith** [comment]
So, to sum up, the solution is that we should allow `ByteArray` to be nullable?

**Comment by ShreckYe** [comment]
My opinion is yes.
