### ISSUE TITLE
Obtaining serializers fails for multi platform modules

### ISSUE THREAD

**Issue by czeidlertest** [Kotlin/kotlinx.serialization#165]
I upgraded kotlinx.serialization from 0.4.2 to 0.5.1 and now have some compiler issues.

I'm basically doing the same as described here (Obtaining serializers):
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md

This is still working fine for JVM only projects but it does not build if I put the code into a common module. When doing:

`Box.serializer(serializer)`

the compiler says:

`Unresolved reference: serializer`

I created a demo project that shows this issue:
https://gitlab.com/czeidler/boxbug

**Comment by sandwwraith** [comment]
You need to `apply plugin: 'kotlinx-serialization' to your common module as well

**Comment by czeidlertest** [comment]
Great thanks, after adding it to all common modules the error is gone. However, I get the following compiler error (in compileKotlinCommon):

```
e: java.lang.IllegalStateException: Cannot get FQ name of local class: class <no name provided>
	at org.jetbrains.kotlin.serialization.DescriptorAwareStringTable$DefaultImpls.getFqNameIndex(DescriptorAwareStringTable.kt:22)
	at org.jetbrains.kotlin.serialization.StringTableImpl.getFqNameIndex(StringTableImpl.kt:25)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.getClassifierId(DescriptorSerializer.kt:704)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.fillFromPossiblyInnerType(DescriptorSerializer.kt:550)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.type$serialization(DescriptorSerializer.kt:515)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.typeId$serialization(DescriptorSerializer.kt:480)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.propertyProto(DescriptorSerializer.kt:218)
	at org.jetbrains.kotlin.serialization.DescriptorSerializer.classProto(DescriptorSerializer.kt:107)
	at org.jetbrains.kotlin.cli.metadata.MetadataSerializer$PackageSerializer.serializeClass(MetadataSerializer.kt:161)
	at org.jetbrains.kotlin.cli.metadata.MetadataSerializer$PackageSerializer.serializeClasses(MetadataSerializer.kt:170)
	at org.jetbrains.kotlin.cli.metadata.MetadataSerializer$PackageSerializer.run(MetadataSerializer.kt:154)
	at org.jetbrains.kotlin.cli.metadata.MetadataSerializer$performSerialization$1.visitClassOrObject(MetadataSerializer.kt:109)
...
```

Any idea how to debug this? Or what the error could be?

**Comment by sandwwraith** [comment]
Given that stacktrace is from `kotlin.serialization`, not `kotlinX.serialization`, I can assume that it is internal compiler problem (`kotlin.serialization` is a compiler package which is responsible for writing classes and modules metadata). Please report to YouTrack.

**Comment by czeidlertest** [comment]
There was already an issue for that and its indeed unrelated:
https://youtrack.jetbrains.com/issue/KT-20996
It also has a workaround that worked for me.
