### ISSUE TITLE
java16 runtime + serialization doesn't work (throws exception)

### ISSUE THREAD

**Issue by yoelp2k** [Kotlin/kotlinx.serialization#1669]
I'm using kotlin serialization library for some time and it works great
recently i started experimenting with the badass runtime plugin to create a native linux executable with the latest java16 jre
when I combine both it's not working

**Bug description**
serialization + badass runtime plugin doesn't work together - an exception is thrown (neither works with json nor properties serialization)

**Expected behavior**
running without exception

**Environment**
    Kotlin version: 1.5.30
    Language version: 1.5
    Library version: 1.3.0-RC
    Kotlin platforms: Kotlin/JVM Multiplatform
    Gradle version: 7.2
    JRE: openjdk-16.0.2
    Other relevant context: org.beryx.runtime version 1.12.5

**To Reproduce**
I have a small program that demonstrate a problem of 
```
package ser.j16.example
import kotlinx.serialization.*
import kotlinx.serialization.properties.*

@Serializable class Project(val name: String, val owner: User)

@Serializable class User(val name: String)

fun main() {
    val data = Project("kotlinx.serialization",  User("kotlin"))
    val map = Properties.encodeToMap<Project>(data)
    map.forEach { (k, v) -> println("$k = $v") }
}
```

and here is the build.gradle.kts file
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.30"
    id("org.beryx.runtime") version "1.12.5"
    application
}

val compileKotlin: KotlinCompile by tasks
val compileJava: JavaCompile by tasks
compileJava.destinationDir = compileKotlin.destinationDir

kotlin {
    jvmToolchain {
        (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of("16"))
    }
}

runtime {
    imageZip.set(project.file("${project.buildDir}/image-zip/hello-image.zip"))
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))
    modules.set(listOf("jdk.unsupported", "java.scripting", "java.logging", "java.xml"))
    targetPlatform("linux", "/home/yoelp/.jdks/openjdk-16.0.2/")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.google.guava:guava:30.1.1-jre")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0-RC")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-properties:1.3.0-RC")
}

application {
    mainClass.set("ser.j16.example.AppKt")
}
```

The exception is thrown
```
Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'Project' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:29)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:60)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at ser.j16.example.AppKt.main(App.kt:21)
	at ser.j16.example.AppKt.main(App.kt)

Process finished with exit code 1
```

**Comment by yoelp2k** [comment]
after fixing build gradle file problem fixed
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.30"
    kotlin("plugin.serialization") version "1.5.30"
    id("org.beryx.runtime") version "1.12.5"
    application
}
```
