### ISSUE TITLE
Error on IR backend: generic base class with more than one type parameter

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1692]
**Describe the bug**
A compilation error occurs when using the JS IR backend, but not when using the LEGACY backend (Kotlin 1.5.31/serialization 1.2.2), when trying to serialize a class which contains a polymorphic field of a type with more than one type parameter.

```
java.lang.IllegalStateException: Expected type argument at 0 in CALL 'public final fun serializer <T0, T1> (typeSerial0: kotlinx.serialization.KSerializer<T0 of dk.cachet.carp.common.application.GenericBase.Companion.serializer>, typeSerial1: kotlinx.serialization.KSerializer<T1 of dk.cachet.carp.common.application.GenericBase.Companion.serializer>): kotlinx.serialization.KSerializer<dk.cachet.carp.common.application.GenericBase<T0 of dk.cachet.carp.common.application.GenericBase.Companion.serializer, T1 of dk.cachet.carp.common.application.GenericBase.Companion.serializer>> declared in dk.cachet.carp.common.application.GenericBase.Companion' type=kotlinx.serialization.KSerializer<dk.cachet.carp.common.application.GenericBase<T0 of dk.cachet.carp.common.application.GenericBase.Companion.serializer, T1 of dk.cachet.carp.common.application.GenericBase.Companion.serializer>> origin=null
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeMemberAccessCommon(IrFileSerializer.kt:579)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeCall(IrFileSerializer.kt:609)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1049)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeVarargElement(IrFileSerializer.kt:884)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeVararg(IrFileSerializer.kt:875)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1074)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeMemberAccessCommon(IrFileSerializer.kt:594)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeCall(IrFileSerializer.kt:609)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1049)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeReturn(IrFileSerializer.kt:779)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1067)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeStatement(IrFileSerializer.kt:1102)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeBlockBody(IrFileSerializer.kt:490)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeStatement(IrFileSerializer.kt:1105)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrStatementBody(IrFileSerializer.kt:178)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunctionBase(IrFileSerializer.kt:1191)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunction(IrFileSerializer.kt:1205)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1358)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1286)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1366)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1286)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1366)
	at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFile(IrFileSerializer.kt:1489)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializeIrFile(IrModuleSerializer.kt:28)
	at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializedIrModule(IrModuleSerializer.kt:35)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.serializeModuleIntoKlib(klib.kt:567)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:186)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:243)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:182)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:75)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:191)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:77)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:358)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:300)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:160)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:72)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:550)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1745)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
```

**To Reproduce**

The following fails:

```
interface SomeInterface

@Serializable
abstract class GenericBase<T1 : SomeInterface, T2 : SomeInterface>

@Serializable
class ToSerialize( val fails: GenericBase<*, *> )
```

The following succeeds:

```
interface SomeInterface

@Serializable
abstract class GenericBase<T1 : SomeInterface>

@Serializable
class ToSerialize( val fails: GenericBase<*> )
```

**Expected behavior**

With the upgrade to 1.5.31 the JVM backend now compiles again, but I'm still stuck getting JS IR to work [on my multiplatform project](https://github.com/cph-cachet/carp.core-kotlin). I would really like to upgrade to the JS IR backend so that I can start generating TS declarations rather than maintaining them myself.

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.2.2
 - Kotlin platforms: JS IR
 - Gradle version: 6.8.3

**Comment by sandwwraith** [comment]
I can confirm there are still issues for JVM IR & JS IR on 1.7.20. I'm going to investigate them

**Comment by Whathecode** [comment]
Am I correct in understanding this should be fixed in the upcoming 1.8.0 release? I tried it with `1.8.0-RC` which still fails for me, but seemingly for different reasons:

```
Problem with `expect companion object Companion : UUIDFactory {
  expect fun parse(uuid: String): UUID
  expect override fun randomUUID(): UUID
  /* fake */ override operator fun equals(other: Any?): Boolean
  /* fake */ override fun hashCode(): Int
  /* fake */ override fun toString(): String
  fun serializer(): KSerializer<UUID> {
    return UUIDSerializer
  }

}
```

Should I file this as a new bug report?

**Comment by sandwwraith** [comment]
@Whathecode Yes, please, this seems to be a different issue

**Comment by Whathecode** [comment]
Posted a small repro here: https://github.com/Kotlin/kotlinx.serialization/issues/2134

Luckily, I could work around it, and it currently isn't a blocker for me.
