### ISSUE TITLE
ProtoBuf decoding fails with an inferred reified type in a `run`

### ISSUE THREAD

**Issue by ShreckYe** [Kotlin/kotlinx.serialization#1695]
**Describe the bug**
ProtoBuf decoding fails with an inffered reified type in a `run`.

**To Reproduce**
Attach a code snippet or test data if possible.

Code:
```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromByteArray
import kotlinx.serialization.encodeToByteArray
import kotlinx.serialization.protobuf.ProtoBuf
import kotlinx.serialization.protobuf.ProtoNumber

var someReceiver: Unit? = Unit

inline fun <reified T> workingDecode(byteArray: ByteArray): T =
    someReceiver?.run {
        ProtoBuf.decodeFromByteArray<T>(byteArray)
    } ?: throw Exception()

inline fun <reified T> buggyDecode(byteArray: ByteArray): T =
    someReceiver?.run {
        ProtoBuf.decodeFromByteArray(byteArray)
    } ?: throw Exception()

@Serializable
class Data(@ProtoNumber(1) val field: String)

fun main() {
    val data = Data("test")
    val serialized = ProtoBuf.encodeToByteArray(data)

    workingDecode<Data>(serialized)
    buggyDecode<Data>(serialized)
}
```

Output:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Unexpected EOF, available 5 bytes, requested: 10
	at kotlinx.serialization.protobuf.internal.ByteArrayInput.ensureEnoughBytes(Streams.kt:38)
	at kotlinx.serialization.protobuf.internal.ByteArrayInput.slice(Streams.kt:14)
	at kotlinx.serialization.protobuf.internal.ProtobufReader.objectTaglessInput(ProtobufReader.kt:75)
	at kotlinx.serialization.protobuf.internal.ProtobufDecodingKt.makeDelimited(ProtobufDecoding.kt:421)
	at kotlinx.serialization.protobuf.internal.ProtobufDecodingKt.access$makeDelimited(ProtobufDecoding.kt:1)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.beginStructure(ProtobufDecoding.kt:152)
	at Data$$serializer.deserialize(Test.kt:19)
	at Data$$serializer.deserialize(Test.kt:19)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
	at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
	at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
	at TestKt.main(Test.kt:46)
	at TestKt.main(Test.kt)

```

**Expected behavior**
Either `buggyDecode` doesn't compile or it works the same as `workingDecode`.

**Environment**
 - Kotlin version: [1.5.30]
 - Library version: [1.2.2]
 - Kotlin platforms: [JVM]
 - Gradle version: [7.2]
 - IDE version (if bug is related to the IDE) [IntellijIDEA 2021.2.2 (Community Edition)]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by LouisCAD** [comment]
Just got bitten by that type inference issue.
Do you know if it's technically possible to fix it?
Maybe with a way to disable/prevent type inference in face of potential ambiguity?

**Comment by qwwdfsad** [comment]
We have an internal `@NoInfer` annotation, but it likely will force users to write type arguments where it is definitely not necessary.

Could you please share your case that you've stumbled upon?
I have an idea of IDE inspection in mind that I'd like to verify

**Comment by LouisCAD** [comment]
It's very similar to the example with `run`, only that I was using `let` instead.

Here's the code:
```kotlin
private fun WatchFaceStyle.Companion.fromDataItem(dataItem: DataItem?): WatchFaceStyle? {
    return dataItem?.data?.let {
        protoBuf.decodeFromByteArray(it) // inferred to WatchFaceStyle? instead of WatchFaceStyle
    }
}
```

**Comment by pdvrieze** [comment]
In @LouisCAD's example the type of the return type could validly either be `WatchFaceStyle` or `WatchFaceStyle?`. Only the inferrence system doesn't really support nullable types. While it could be an option to just ignore nullability for inference there is no reason a format could not allow nullable serializers at the top level. As such having inference handle nullability would be better, and in case there is always content this will work anyway. (of course explicit specification of the type is also valid).
