### ISSUE TITLE
JS/Native IR compilation fails on 1.5.31 when base class with optional property located in different module

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#1698]
**Describe the bug**

```
> Task :compileTestKotlinJsIr FAILED
e: java.lang.IllegalStateException: Symbol with IrFieldSymbolImpl is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindableSymbolBase.getOwner(IrPrivateSymbolBase.kt:58)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.getIrField(GeneratorHelpers.kt:331)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.getIrField(SerializerIrGenerator.kt:47)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializeAllProperties(GeneratorHelpers.kt:1270)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.serializeAllProperties(SerializerIrGenerator.kt:47)
```

**To Reproduce**

Module Main:

```kotlin
@Serializable
abstract class NotInConstructorBase {
    // b should precede a for testing
    val b = "val b"
    val a = "val a"
}
```

Module Test:

```kotlin
@Serializable
class NotInConstructorTest : NotInConstructorBase() {
    val c = "val c"
}
```

**Expected behavior**

Compilation passes succesfully

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.0
 - Kotlin platforms: JS IR

**Comment by sandwwraith** [comment]
Fixed in 1.6.0-RC
