### ISSUE TITLE
ClassCastException: int[] cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by guness** [Kotlin/kotlinx.serialization#1707]
**Cannot serialize `ByteArray` or `IntArray`**

**To Reproduce**

When the type of a property is unknown and a `ByteArray` is provided runtime, it fails. However when we provide it in a different way it works. The same holds for `IntArray` and `int[]`. I think it is related to the unboxing of primitive types.
Here is the code snippet that reproduces the exception:

```
@Serializable(with = CustomObjSerializer::class)
data class CustomObj(val type: Int, val value: Any)

object CustomObjSerializer : KSerializer<CustomObj> {

    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("CustomObj") {
        element<Int>("type")
        element<JsonElement>("value")
    }

    override fun deserialize(decoder: Decoder): CustomObj {
        require(decoder is JsonDecoder)
        TODO()
    }

    override fun serialize(encoder: Encoder, value: CustomObj) {
        val data = value.value
        val serializer = encoder.serializersModule.serializer(data::class.java)
        encoder.encodeStructure(descriptor) {
            encodeIntElement(descriptor, 0, value.type)
            encodeSerializableElement(descriptor, 1, serializer, data)
        }
    }
}

class CustomObjSerializerTest {
    
    // intArrayOf(1) fails
    @Test
    fun testSerializeFail() {
        Json.encodeToString(CustomObj(3, intArrayOf(1)))
    }

    // arrayOf(1) passes
    @Test
    fun testSerializePass() {
        Json.encodeToString(CustomObj(3, arrayOf(1)))
    }
}
```

**Expected behavior**
using `intArrayOf(1)` or `arrayOf(1)` should not make difference. same is valid for `ByteArray` or `Array<Byte>`

**Environment**
 - Kotlin version: [e.g. 1.5.31]
 - Library version: [e.g. 1.3.0]
 - Kotlin platforms: [JVM, Android]
 
 **Stacktrace**
```
E/TestRunner: java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]
        at kotlinx.serialization.internal.ReferenceArraySerializer.collectionSize(CollectionSerializers.kt:183)
        at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:65)
        at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
        at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
        at com.guness.utils.serializers.CustomObjSerializer.serialize(CustomObjSerializer.kt:122)
        at com.guness.utils.serializers.CustomObjSerializer.serialize(CustomObjSerializer.kt:105)
        at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
        at kotlinx.serialization.json.Json.encodeToString(Json.kt:85)
        at com.guness.utils.serializers.CustomObjSerializerTest.testSerializeFail(CustomObjSerializerTest.kt:44)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2196)
```

**Comment by sandwwraith** [comment]
That's because of `encoder.serializersModule.serializer(data::class.java)`. `serializer(java.lang.Type)` doesn't handle primitive arrays well currently.

**Comment by guness** [comment]
> That's because of `encoder.serializersModule.serializer(data::class.java)`. `serializer(java.lang.Type)` doesn't handle primitive arrays well currently.  

Thanks for quick response. I see your point. Is there a workaround for this?

I have tried to register custom serialiser for both type using polymorphic keyword. It did not work.
