### ISSUE TITLE
1.2.60 EAP not working

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.serialization#171]
We are using `0.5.2-SNAPSHOT` and getting the following error with Kotlin `1.2.60-eap-44`. This is blocking my investigation into https://youtrack.jetbrains.com/issue/KT-24599

```
00:00:08.060 Download https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-gradle-serialization-plugin/0.5.2-SNAPSHOT/kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.pom
00:00:08.661 Download https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-gradle-serialization-plugin/0.5.2-SNAPSHOT/kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.jar
00:00:12.064 
00:00:12.064 FAILURE: Build failed with an exception.
00:00:12.064 
00:00:12.064 * What went wrong:
00:00:12.064 A problem occurred configuring project ':api-common'.
00:00:12.064 > Failed to notify project evaluation listener.
00:00:12.064    > org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin: Provider org.jetbrains.kotlinx.serialization.gradle.SerializationKotlinGradleSubplugin could not be instantiated
00:00:12.065    > org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin: Provider org.jetbrains.kotlinx.serialization.gradle.SerializationKotlinGradleSubplugin could not be instantiated
00:00:12.065 
00:00:12.065 * Try:
00:00:12.065 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
00:00:12.065 
00:00:12.065 * Exception is:
00:00:12.065 org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':api-common'.
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:109)
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator.onAfterEvaluateFailure(LifecycleProjectEvaluator.java:105)
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:87)
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:72)
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:37)
00:00:12.065 	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:125)
00:00:12.065 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
00:00:12.066 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
00:00:12.066 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
00:00:12.074 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
00:00:12.074 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:52)
00:00:12.074 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:677)
00:00:12.074 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
00:00:12.074 	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
00:00:12.074 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
00:00:12.074 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
00:00:12.074 	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:262)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
00:00:12.074 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
00:00:12.074 	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:175)
00:00:12.074 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
00:00:12.074 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:115)
00:00:12.074 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
00:00:12.074 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
00:00:12.074 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
00:00:12.074 	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
00:00:12.074 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
00:00:12.074 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
00:00:12.074 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
00:00:12.074 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
00:00:12.074 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
00:00:12.074 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
00:00:12.074 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
00:00:12.074 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
00:00:12.074 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
00:00:12.074 	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
00:00:12.074 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
00:00:12.074 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
00:00:12.074 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:65)
00:00:12.074 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
00:00:12.074 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
00:00:12.074 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
00:00:12.074 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
00:00:12.074 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
00:00:12.074 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
00:00:12.074 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
00:00:12.074 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
00:00:12.074 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
00:00:12.074 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
00:00:12.074 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
00:00:12.074 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
00:00:12.074 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
00:00:12.074 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
00:00:12.074 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
00:00:12.074 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
00:00:12.074 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
00:00:12.074 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
00:00:12.074 	at org.gradle.util.Swapper.swap(Swapper.java:38)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:00:12.074 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
00:00:12.074 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
00:00:12.075 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
00:00:12.075 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
00:00:12.075 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
00:00:12.075 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
00:00:12.075 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
00:00:12.075 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
00:00:12.075 Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
00:00:12.075 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
00:00:12.075 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
00:00:12.075 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
00:00:12.075 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
00:00:12.075 	at com.sun.proxy.$Proxy26.afterEvaluate(Unknown Source)
00:00:12.075 	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:83)
00:00:12.075 	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:80)
00:00:12.075 	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1393)
00:00:12.075 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:80)
00:00:12.075 	... 88 more
00:00:12.075 Caused by: java.util.ServiceConfigurationError: org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin: Provider org.jetbrains.kotlinx.serialization.gradle.SerializationKotlinGradleSubplugin could not be instantiated
00:00:12.075 	at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.loadSubplugins(KotlinPlugin.kt:831)
00:00:12.075 	at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.access$loadSubplugins(KotlinPlugin.kt:1)
00:00:12.075 	at org.jetbrains.kotlin.gradle.plugin.KotlinCommonSourceSetProcessor$doTargetSpecificProcessing$1.execute(KotlinPlugin.kt:314)
00:00:12.075 	at org.jetbrains.kotlin.gradle.plugin.KotlinCommonSourceSetProcessor$doTargetSpecificProcessing$1.execute(KotlinPlugin.kt:295)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
00:00:12.075 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
00:00:12.075 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
00:00:12.075 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
00:00:12.075 	... 98 more
00:00:12.075 Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
00:00:12.075 	at org.jetbrains.kotlinx.serialization.gradle.SerializationSubpluginKt.findPluginVersion(SerializationSubplugin.kt:87)
00:00:12.075 	at org.jetbrains.kotlinx.serialization.gradle.SerializationSubpluginKt.access$findPluginVersion(SerializationSubplugin.kt:1)
00:00:12.075 	at org.jetbrains.kotlinx.serialization.gradle.SerializationKotlinGradleSubplugin.<init>(SerializationSubplugin.kt:48)
00:00:12.075 	... 108 more
00:00:12.075 
00:00:12.075 
00:00:12.075 * Get more help at https://help.gradle.org
00:00:12.075 
00:00:12.078 Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
00:00:12.081 See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings
00:00:12.081 
00:00:12.081 BUILD FAILED in 10s
```

**Comment by sandwwraith** [comment]
Kinda strange. Can you share your project so I try to reproduce the problem? I have https://github.com/sandwwraith/KotlinSerializationPlayground and all works fine when i change versions to 
```
kotlin_version = 1.2.60-eap-44
serialization_version=0.5.2-SNAPSHOT
```

**Comment by ScottPierce** [comment]
I can't share the project with you. I can do anything you might need and report back though. I can also hop on the kotlin slack and dm and diagnose it live if that helps as well.

**Comment by ScottPierce** [comment]
Obviously the bug is with:
```
00:00:12.075 Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
00:00:12.075 	at org.jetbrains.kotlinx.serialization.gradle.SerializationSubpluginKt.findPluginVersion(SerializationSubplugin.kt:87)
```

**Comment by sandwwraith** [comment]
The line that throws an exception is trying to read `plugin.version` from file `plugin.properties`, which is packed to `kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.jar`. I've downloaded it from bintray and verified that file is there and with proper content. Class loaders and jar resources are involved there, do you have something unusual with them or probably that's just an incorrect jar?

**Comment by ScottPierce** [comment]
This is the folder that is downloaded into my gradle cache directory.
[0.5.2-SNAPSHOT.zip](https://github.com/Kotlin/kotlinx.serialization/files/2185690/0.5.2-SNAPSHOT.zip)

**Comment by sandwwraith** [comment]
The archive contents seems ok. You can try to disable gradle daemon, but I'm not sure this gonna help. Which versions of Java and Gradle do you have?

**Comment by ScottPierce** [comment]
I think I'm using the embedded jvm, but incase not:
```
java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

```
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
Licensed to Rally Health / Scott Pierce
Subscription is active until February 11, 2019
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

Gradle 4.8

**Comment by ScottPierce** [comment]
I'm seeing this error on our Linux Jenkins server as well.

This is also blocking me on testing https://youtrack.jetbrains.com/issue/KT-24919

**Comment by ScottPierce** [comment]
I created a patch jar to unblock myself as per your recommendation, and added it to the project like this:
`classpath files('misc/libs/kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.jar')`

This seems to have unblocked my team for the moment.

[kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.jar.zip](https://github.com/Kotlin/kotlinx.serialization/files/2190336/kotlinx-gradle-serialization-plugin-0.5.2-SNAPSHOT.jar.zip)

**Comment by ScottPierce** [comment]
This seems to work with 0.6.1. Will reopen this if I see it again.
