### ISSUE TITLE
Unexpected JsonDecodingException when one letter class name is used

### ISSUE THREAD

**Issue by Stexxe** [Kotlin/kotlinx.serialization#1725]
**Describe the bug**
When one letter class name is used the library throws an `JsonDecodingException`.

To reproduce run the following code:
```
fun main() {
    Json.decodeFromString<F>(
        """
            {"x": 123}
        """.trimIndent()
    )
}

@kotlinx.serialization.Serializable
data class F(
    val x: Int
)
```

I expect no exceptions to be thrown but get the following one:
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected beginning of the string, but got {
JSON input: {"x": 123}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.JsonLexer.fail(JsonLexer.kt:493)
	at kotlinx.serialization.json.internal.JsonLexer.fail$default(JsonLexer.kt:492)
	at kotlinx.serialization.json.internal.JsonLexer.consumeStringLenient(JsonLexer.kt:391)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeFloat(StreamingJsonDecoder.kt:290)
	at kotlinx.serialization.internal.FloatSerializer.deserialize(Primitives.kt:121)
	at kotlinx.serialization.internal.FloatSerializer.deserialize(Primitives.kt:117)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at ClientKt.main(client.kt:57)
	at ClientKt.main(client.kt)
```

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.2.2
 - Kotlin platforms: JVM
 - Gradle version: 7.0

**Comment by qwwdfsad** [comment]
I cannot reproduce it either on 1.2.2 or on our latest 1.3.0.

Please double-check your setup or provide a reproducing project.
