### ISSUE TITLE
Internal compiler error: StackOverflow - ContextualSerializer

### ISSUE THREAD

**Issue by Maartyl** [Kotlin/kotlinx.serialization#1776]
**Describe the bug**
Compilation fails with StackOverflowError. (partial stack trace at the end)

**To Reproduce**
```kotlin
import kotlinx.serialization.*

@Serializable(with = ContextualSerializer::class)
class Ref<T : Any>(
  val id: String,
)
```

```gradle
plugins {
  kotlin("jvm") version "1.5.31"
  kotlin("plugin.serialization") version "1.5.31"
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.3.1")
}
```

**Expected behavior**
Compiles or shows meaningful error.

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.1
 - Kotlin platforms: JVM
 - Gradle version: 7.1

```
java.lang.StackOverflowError
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.visitPackageFragmentDescriptor(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.descriptors.impl.PackageFragmentDescriptorImpl.accept(PackageFragmentDescriptorImpl.kt:36)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.mangleSimpleDeclaration(DescriptorMangleComputer.kt:65)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.visitClassDescriptor(DescriptorMangleComputer.kt:248)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.visitClassDescriptor(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.descriptors.impl.AbstractClassDescriptor.accept(AbstractClassDescriptor.java:178)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.mangleType(DescriptorMangleComputer.kt:173)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.access$mangleType(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer$mangleTypeParameter$1.invoke(DescriptorMangleComputer.kt:155)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer$mangleTypeParameter$1.invoke(DescriptorMangleComputer.kt:155)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.MangleUtilsKt.collectForMangler(mangleUtils.kt:25)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.mangleTypeParameter(DescriptorMangleComputer.kt:155)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.access$mangleTypeParameter(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer$visitPropertyDescriptor$1.invoke(DescriptorMangleComputer.kt:280)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer$visitPropertyDescriptor$1.invoke(DescriptorMangleComputer.kt:280)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.MangleUtilsKt.collectForMangler(mangleUtils.kt:25)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.visitPropertyDescriptor(DescriptorMangleComputer.kt:280)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.visitPropertyDescriptor(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.descriptors.impl.PropertyDescriptorImpl.accept(PropertyDescriptorImpl.java:529)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.computeMangle(DescriptorMangleComputer.kt:23)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorMangleComputer.computeMangle(DescriptorMangleComputer.kt:19)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorBasedKotlinManglerImpl.withMode(DescriptorBasedKotlinManglerImpl.kt:20)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorBasedKotlinManglerImpl.getSignatureString(DescriptorBasedKotlinManglerImpl.kt:35)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.descriptor.DescriptorBasedKotlinManglerImpl.getSignatureString(DescriptorBasedKotlinManglerImpl.kt:18)
        at org.jetbrains.kotlin.ir.util.KotlinMangler$DefaultImpls.getSignatureMangle(KotlinMangler.kt:23)
        at org.jetbrains.kotlin.backend.common.serialization.mangle.AbstractKotlinMangler.getSignatureMangle(AbstractKotlinMangler.kt:11)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureDescriptor$DescriptorBasedSignatureBuilder.visitPropertyDescriptor(IdSignatureDescriptor.kt:79)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureDescriptor$DescriptorBasedSignatureBuilder.visitPropertyDescriptor(IdSignatureDescriptor.kt:17)
        at org.jetbrains.kotlin.descriptors.impl.PropertyDescriptorImpl.accept(PropertyDescriptorImpl.java:529)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureDescriptor$DescriptorBasedSignatureBuilder.accept(IdSignatureDescriptor.kt:22)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureDescriptor$DescriptorBasedSignatureBuilder.accept(IdSignatureDescriptor.kt:17)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureBuilder.buildSignature(IdSignatureBuilder.kt:75)
        at org.jetbrains.kotlin.backend.jvm.serialization.JvmIdSignatureDescriptor.composeSignature(JvmIdSignatureDescriptor.kt:104)
        at org.jetbrains.kotlin.ir.util.SymbolTable$FlatSymbolTable.signature(SymbolTable.kt:198)
        at org.jetbrains.kotlin.ir.util.SymbolTable$FlatSymbolTable.get(SymbolTable.kt:201)
        at org.jetbrains.kotlin.ir.util.SymbolTable.referenceProperty(SymbolTable.kt:1662)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl$referenceProperties$1.invoke(IrPluginContextImpl.kt:135)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl$referenceProperties$1.invoke(IrPluginContextImpl.kt:133)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl.resolveSymbolCollection(IrPluginContextImpl.kt:89)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl.referenceProperties(IrPluginContextImpl.kt:133)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationPluginContext.referenceProperties(SerializationLoweringExtension.kt)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:922)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:966)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:966)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:966)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:966)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance(GeneratorHelpers.kt:966)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableCompanionIrGenerator.serializerInstance(SerializableCompanionIrGenerator.kt:29)
        at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.serializerInstance$instantiate(GeneratorHelpers.kt:931)
```

**Comment by Maartyl** [comment]
I've found the following works*. - It's mostly just a simplified copy of the implementation. (However, the descriptor cannot 'implement' getContextualDescriptor.)

```kotlin
@OptIn(ExperimentalSerializationApi::class)
object GRefCtxSerializer : KSerializer<GRef<*>> {

  object PrimitiveSerialDescriptor : SerialDescriptor {
    override val serialName: String = "GRefCtx"
    override val kind = SerialKind.CONTEXTUAL
    override val elementsCount: Int get() = 0
    override fun getElementName(index: Int): String = error()
    override fun getElementIndex(name: String): Int = error()
    override fun isElementOptional(index: Int): Boolean = error()
    override fun getElementDescriptor(index: Int): SerialDescriptor = error()
    override fun getElementAnnotations(index: Int): List<Annotation> = error()
    override fun toString(): String = "PrimitiveDescriptor($serialName)"
    private fun error(): Nothing = throw IllegalStateException("Primitive descriptor does not have elements")
  }

  override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor

  private fun serializer(serializersModule: SerializersModule): KSerializer<GRef<*>> =
    serializersModule.getContextual(GRef::class) ?: error("contextual serializer for GRef not provided")

  override fun serialize(encoder: Encoder, value: GRef<*>) {
    encoder.encodeSerializableValue(serializer(encoder.serializersModule), value)
  }

  override fun deserialize(decoder: Decoder): GRef<*> {
    return decoder.decodeSerializableValue(serializer(decoder.serializersModule))
  }
}
```
*It works at least in simple tests I've done so far, in Protobuf; serializing GRef into a single string.

//btw. It's surprising that `capturedKClass` is not defined on `SerialDescriptor` (with default implementation`=null`). I wonder why that is... Backward binary compatibility? Preventing non-internal (and `by`) implementation? - Anyway, that's irrelevant, and I've found a workaround that seems to work for now.
