### ISSUE TITLE
Duplicate definition: local kotlinx.serialization.internal/|null[0]:1:3

### ISSUE THREAD

**Issue by nicolidin** [Kotlin/kotlinx.serialization#1801]
Hello, I'm using kotlin-multiplatform (IR js compiler) with last dev version for having enum and interface usage.
However, with those below version:
``` kotlin
//build.gradle.kts
plugins {
    kotlin("multiplatform") version "1.6.20-dev-7236"
    kotlin("plugin.serialization") version "1.6.20-dev-7236"
    application
}
  val commonMain by getting {
     dependencies {
         implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1")
     }
 }

//setting.gradle.kts
pluginManagement {
    repositories {
        maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/")
        mavenCentral()
        gradlePluginPortal()
    }
}

```
I'm getting this error:
``` 
java.lang.IllegalArgumentException: Duplicate definition: local kotlinx.serialization.internal/|null[0]:1:3

at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.JsIrProgram.crossModuleDependencies(JsIrProgramFragment.kt:38)

at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.IrModuleToJsTransformerTmpKt.generateWrappedModuleBody(IrModuleToJsTransformerTmp.kt:297)

at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.IrModuleToJsTransformerTmpKt.access$generateWrappedModuleBody(IrModuleToJsTransformerTmp.kt:1)

at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.IrModuleToJsTransformerTmp.generateModule(IrModuleToJsTransformerTmp.kt:66)
```
Hoping you can help, 
Thanks!

**Comment by rescribet** [comment]
I've [added a branch](https://github.com/rescribet/kotlin-js-enum-preview/tree/duplicate-definition) on the example repo which reproduces this exception

Though I've seen the same issue with coroutines (`Duplicate definition: local kotlinx.coroutines.intrinsics/|null[0]:2`), so this might be caused by JS/IR or the underlying setup.

**Comment by LifeIsStrange** [comment]
@sandwwraith friendly ping

**Comment by rescribet** [comment]
@LifeIsStrange @nicolidin I no longer have this issue with Kotlin `1.6.20-RC-4`
