### ISSUE TITLE
Cannot locate default serializer for `inline class`

### ISSUE THREAD

**Issue by AregevDev** [Kotlin/kotlinx.serialization#181]
```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON

fun main(args: Array<String>) {
    val n = Name("mike")
    n.hello()

    println(JSON.stringify(n))
}

@Serializable
inline class Name(private val v: String) {
    fun hello() {
        println("Hello $v")
    }
}
```

Gives this:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate default serializer for class org.aregevdev.kotlinstuff.Name
	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:23)
	at org.aregevdev.kotlinstuff.MainKt.main(main.kt:19)
```

**Comment by sandwwraith** [comment]
Seems like you just haven't applied proper plugin in buildscript to generate serializers for classes. Anyway, it currently does not work in `1.3-M1` because compiler API have been broken again. It does work on Kotlin/JS, though (but I didn't test it with inline classes).

**Comment by sandwwraith** [comment]
UPD: seems serializable inline classes are working on Kotlin/JS:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON as kxJson
import kotlin.test.*

@Serializable
inline class Name(private val v: String) {
    fun hello() {
        println("Hello $v")
    }
}

class ActualPlatformTest {
    @Test
    fun testName() {
        val n = Name("mike")

        val s = kxJson.stringify(n)
        assertEquals("""{"v":"mike"}""", s)
        // passes
    }
}
```
