### ISSUE TITLE
kotlinx-serialization gets confused with non-serializable generics

### ISSUE THREAD

**Issue by RaphaelTarita** [Kotlin/kotlinx.serialization#1813]
## Describe the bug

To describe the problem(s), let's start with a working example:

```kotlin
class Foo(val str: String)

@Serializable
sealed class Base {
    abstract fun produce(): Foo
}

@Serializable
@SerialName("sub")
data class Sub(val testValue: String) : Base() {
    override fun produce(): Foo = Foo("test test")
}

fun main() {
    println(Json.decodeFromString<Base>("{\"type\":\"sub\",\"testValue\":\"test\"}"))
}
```
This works as expected and prints `Sub(testValue=test)`. But what if we wanted to add a generic to `Base`, that gets substituted with `Foo` by `Sub`:

```kotlin
interface Marker

class Foo(val str: String) : Marker

@Serializable
sealed class Base<T : Marker> {
    abstract fun produce(): T
}

@Serializable
@SerialName("sub")
data class Sub(val testValue: String) : Base<Foo>() {
    override fun produce(): Foo = Foo("test test")
}

fun main() {
    println(Json.decodeFromString<Base<out Marker>>("{\"type\":\"sub\",\"testValue\":\"test\"}"))
}
```
Theoretically, this should work fine because there is no field in `Base` with the type `T`, so kotlinx-serialization shouldn't care about that generic. But instead I get a compiler exception:

```
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type Foo has not been found.
To use context serializer as fallback, explicitly annotate element with @Contextual
File is unknown
```
(full stacktrace below [1]) Especially the "File is unknown" makes finding the error quite difficult.

However, I figured out that this error, although I consider it a bug, can be avoided by making `Base` a `sealed interface` instead: 

```kotlin
interface Marker

class Foo(val str: String) : Marker

sealed interface Base<T : Marker> {
    fun produce(): T
}

@Serializable
@SerialName("sub")
data class Sub(val testValue: String) : Base<Foo> {
    override fun produce(): Foo = Foo("test test")
}

fun main() {
    println(Json.decodeFromString<Base<out Marker>>("{\"type\":\"sub\",\"testValue\":\"test\"}"))
}
```
Now this compiles properly, but throws an exception at runtime:
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'sub'
JSON input: {"type":"sub","testValue":"test"}
```
(full stacktrace below [2]) This, however, seems to be not specific to this setup, rather it seems to be impossible to deserialize with the static type being a `sealed interface`:

```kotlin
class Foo(val str: String)

sealed interface Base {
    fun produce(): Foo
}

@Serializable
@SerialName("sub")
data class Sub(val testValue: String) : Base {
    override fun produce(): Foo = Foo("test test")
}

fun main() {
    println(Json.decodeFromString<Base>("{\"type\":\"sub\",\"testValue\":\"test\"}"))
}
```
Which yields:
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'sub'
JSON input: {"type":"sub","testValue":"test"}
```
(full stacktrace below [3]) This surprised me because I fully expected this to work just like with sealed classes. I haven't seen any explicit note saying that serialization for `sealed interface`s is not supported, and even if that's the case, I'd consider this a feature worth adding to kotlinx-serialization.

## To Reproduce
Try to compile and run the given snippets.

## Expected behavior
I'd expect that
1. The second snippet doesn't throw a compiler exception, and actually compiles to a working program (output would be `Sub(testValue=test)`). It should not care about the generic, `Foo`.
    1.1 Even if this snippet would be considered erroneous, it shouldn't throw a compiler exception, but rather report the error properly as the compiler output (including file and line number).
2. The third and fourth snippet (e.g. de- / serializing a `sealed interface`) should not throw an exception at runtime (output would be `Sub(testValue=test)`)

## Environment
 - Kotlin/JVM 1.6.10
 - OpenJDK 17.0.1
 - kotlinx-serialization gradle plugin 1.6.10
 - kotlinx-serialization-json 1.3.0
 - Gradle 7.3
 - IntelliJ IDEA Ultimate 2021.3.1 (build #IU-213.6461.79)
 - Windows 11 Pro x86_64

## Stacktraces
Stacktrace [1]:
```
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type Foo has not been found.
To use context serializer as fallback, explicitly annotate element with @Contextual
File is unknown

	at org.jetbrains.kotlinx.serialization.compiler.backend.common.TypeUtilKt.findTypeSerializerOrContext(TypeUtil.kt:141)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.TypeUtilKt.findTypeSerializerOrContext$default(TypeUtil.kt:135)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:320)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:281)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderExtension$DefaultImpls.contributeFunction(GeneratorHelpers.kt:69)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.contributeFunction(SerializableIrGenerator.kt:35)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateWriteSelfMethod(SerializableIrGenerator.kt:281)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticMethods(SerializableCodegen.kt:51)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:25)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$Companion.generate(SerializableIrGenerator.kt:354)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:58)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptChildrenVoid(IrElementVisitorVoid.kt:275)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitElement(SerializationLoweringExtension.kt:32)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitPackageFragment(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:271)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt.runOnFileInOrder(SerializationLoweringExtension.kt:30)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtension.generate(SerializationLoweringExtension.kt:77)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda-1(JvmIrCodegenFactory.kt:121)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:88)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:146)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$default(JvmIrCodegenFactory.kt:64)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:331)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:434)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:120)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:159)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:622)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:100)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1713)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Stacktrace [2]:
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'sub'
JSON input: {"type":"sub","testValue":"test"}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.throwSerializerNotFound(Polymorphic.kt:76)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:66)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at MainKt.main(Main.kt:23)
	at MainKt.main(Main.kt)
```
Stacktrace [3]:
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'sub'
JSON input: {"type":"sub","testValue":"test"}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.throwSerializerNotFound(Polymorphic.kt:76)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:66)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at MainKt.main(Main.kt:21)
	at MainKt.main(Main.kt)
```

**Comment by sandwwraith** [comment]
Sorry for the long delay. Let's start with the second question: 

Special support for sealed interfaces will be added in 1.6.20 (#1576), for now, they're treated as regular interfaces and require registering in `SerializersModule { polymorphic(...) }`. Thus `Polymorphic serializer was not found for class discriminator 'sub'` error.

Regarding generics: that's also a known issue: https://github.com/Kotlin/kotlinx.serialization/issues/607 connected to the fact that plugin does not check whether type parameter is used or not, for the sake of simplicity and consistent behavior. The recommended way to work around this is to provide an arbitrary serializer for Foo.  Note you can apply one right in the type, as the error message suggests: `data class Sub(val testValue: String) : Base<@Contextual Foo>()`
