### ISSUE TITLE
Issue with Kotlin reflection after serializing a class with Flink

### ISSUE THREAD

**Issue by justinhj** [Kotlin/kotlinx.serialization#1831]
**Describe the bug**

As you may know Apache Flink sends code and data over the wire to workers to be executed. We have code that uses both Jackson and Kotlinx serialization. It works fine in local testing but when deployed to a cluster we get an error in the Jackson serializer when it tries to use reflection on the objects companion object.

Here is the call stack which is mostly unrelated to kotlinx.serialization but hopefully the top few lines are. I wonder if you can share some insight on what may be (or may not be) happening to the plugin generated code when it is sent over the wire?

Caused by: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class org.justinhj.domain.Config$$serializer
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:328)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
	at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:48)
	at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector$hasCreatorAnnotation$1.invoke(KotlinNamesAnnotationIntrospector.kt:94)
	at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector$hasCreatorAnnotation$1.invoke(KotlinNamesAnnotationIntrospector.kt:68)
	at com.fasterxml.jackson.module.kotlin.ReflectionCache.checkConstructorIsCreatorAnnotated(ReflectionCache.kt:53)
	at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.hasCreatorAnnotation(KotlinNamesAnnotationIntrospector.kt:68)
	at com.fasterxml.jackson.databind.AnnotationIntrospector.findCreatorAnnotation(AnnotationIntrospector.java:1514)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findCreatorAnnotation(AnnotationIntrospectorPair.java:842)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addExplicitConstructorCreators(BasicDeserializerFactory.java:451)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:304)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:609)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:188)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:856)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:647)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4805)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)

Where Config is:

```
@Serializable
data class Config(val version: Long, val name: String)
```

**To Reproduce**
Use KotlinX and Jackson serialization on a data type and use over a Flink cluster

**Expected behavior**
Everything works 

**Environment**
 - Kotlin version: [1.5.31]
 - Library version: [1.3.0]
 - Kotlin platforms: [JVM]
- Apache Flink [1.11.3]

**Comment by sandwwraith** [comment]
Sorry, I'm not familiar with Flink. So you're saying you're actually sending _the code_, not only the data? Like, class files and then loading them in another machine of the cluster?

Then maybe this `$serializer` class just got lost on the receiving side. Maybe because of some kind of name filter, or another reason.

**Comment by justinhj** [comment]
Yes I'm thinking something like that is happening. I'm digging into the details of how the classes are sent and what might be filtered, but just posted here on the off-chance I'm not the first to wander into this territory.

**Comment by justinhj** [comment]
Just a heads up, it seems that there is no issue using Kotlinx serialization with Flink. The problem I ran into was actually caused when Jackson's Kotlin module tries to serialize a class with Kotlinx serialization plugin generated code. There seems to be a bug in the reflection code that causes the crash. This bug is reported here:
https://youtrack.jetbrains.com/issue/KT-41373#focus=Comments-27-5708132.0-0

**Comment by ninja-** [comment]
> . We have code that uses both Jackson and Kotlinx serialization. It works fine in local testing but when deployed to a cluster we get an error in the Jackson serializer when it tries to use reflection on the objects companion object.

> Here is the call stack which is mostly unrelated to kotlinx.serialization but hopefully the top few lines are. I wonder if you can share some insight on what may be (or may not be) happening to the plugin generated code when it is sent over the wire?

I've hit the same issue, and I can't figure out why everything works inside the unit test, but crashes at runtime - very frustrating :/ I've checked that classpath is matching 100 times

**Comment by ninja-** [comment]
I've added some research on this issue to linked youtrack ticket
