### ISSUE TITLE
Json fails to decode to data class if the order of fields is different than expected.

### ISSUE THREAD

**Issue by Kietyo** [Kotlin/kotlinx.serialization#1890]
**Describe the bug**

I have a data classes defined like so:

```
@Serializable
data class GameMap(
    val width: Int, val height: Int,
    private var start: MapEntity.Start? = null,
    private var finish: MapEntity.Finish? = null,
    private val checkpoints: MutableList<MapEntity.CheckPoint> = mutableListOf(),
    private val teleportIns: MutableMap<Int, MapEntity.TeleportIn> = mutableMapOf(),
    private val teleportOuts: MutableMap<Int, MapEntity.TeleportOut> = mutableMapOf(),
    private val towers: MutableList<MapEntity.Tower> = mutableListOf(),
    private val rocks: MutableList<MapEntity.Rock> = mutableListOf(),
    private val smallBlockers: MutableList<MapEntity.SmallBlocker> = mutableListOf(),
    private val speedAreas: MutableList<MapEntity.SpeedArea> = mutableListOf()
)

// Note: Fb = Firebase
@Serializable
data class FbMapData(
    val data: Map<String, FbMapEntry>
)

@Serializable
data class FbMapEntry(
    val data: GameMap,
    val timestamp: Int
)
```

I've found that if I'm decoding from a string, it requires that the json fields be structured in the same order as the data class.

For example. 

This test passes:

```
    @Test
    fun decodeFbMapDataFromString1() {
        val str = """
            {"data":{"blahblah":{
            "data":{
            "width":10,
            "height":10,
            "start":{"x":2,"y":2},
            "finish":{"x":4,"y":4},
            "rocks":[{"x":0,"y":0,"width":2,"height":4}]},
            "timestamp":123456789}}}
        """.trimIndent()

        val map = Json.decodeFromString<FbMapData>(str)

        println(map)
    }
```

This test causes `Json.decodeFromString` to throw an exception:

```
    @Test
    fun decodeFbMapDataFromString2() {
        val str = """
            {"data":{"blahblah":{
            "data":{
            "rocks":[{"x":0,"y":0,"width":2,"height":4}]},
            "width":10,
            "height":10,
            "start":{"x":2,"y":2},
            "finish":{"x":4,"y":4},
            "timestamp":123456789}}}
        """.trimIndent()

        val map = Json.decodeFromString<FbMapData>(str)

        println(map)
    }
```

Notice that I move `rocks` above `width`.

Here's the error it throws:

```

Fields [width, height] are required for type with serial name 'com.xenotactic.gamelogic.model.GameMap', but they were missing
kotlinx.serialization.MissingFieldException: Fields [width, height] are required for type with serial name 'com.xenotactic.gamelogic.model.GameMap', but they were missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at com.xenotactic.gamelogic.model.GameMap.<init>(GameMap.kt:9)
	at com.xenotactic.gamelogic.model.GameMap$$serializer.deserialize(GameMap.kt:9)
	at com.xenotactic.gamelogic.model.GameMap$$serializer.deserialize(GameMap.kt:9)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at com.xenotactic.gamelogic.firebase_models.FbMapEntry$$serializer.deserialize(models.kt:12)
	at com.xenotactic.gamelogic.firebase_models.FbMapEntry$$serializer.deserialize(models.kt:12)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at com.xenotactic.gamelogic.firebase_models.FbMapData$$serializer.deserialize(models.kt:7)
	at com.xenotactic.gamelogic.firebase_models.FbMapData$$serializer.deserialize(models.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at firebase.FirebaseModelTest.decodeFbMapDataFromString2(FirebaseModelTest.kt:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This behavior is not ideal. For example, I am storing entity data in Firebase, and it looks like this:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/5054996/160973275-0b02b083-e9b8-468a-bd09-c0d1c5cf38de.png">

Notice how the fields are ordered in **alphabetical order**.

When I read entities from the database, it looks like this:

```
{
  "data": {
    "22e150c36a372dd51487cb597b10b58a568d5d4e": {
      "data": {
        "checkpoints": [
          {
            "sequenceNumber": 0,
            "x": 20,
            "y": 17
          },
          {
            "sequenceNumber": 1,
            "x": 30,
            "y": 9
          }
        ],
        "finish": {
          "x": 16,
          "y": 24
        },
        "height": 46,
        "rocks": [
          {
            "height": 2,
            "width": 4,
            "x": 20,
            "y": 11
          },
          {
            "height": 2,
            "width": 4,
            "x": 40,
            "y": 10
          },
          {
            "height": 2,
            "width": 4,
            "x": 29,
            "y": 35
          },
          {
            "height": 4,
            "width": 2,
            "x": 19,
            "y": 2
          },
          {
            "height": 4,
            "width": 2,
            "x": 3,
            "y": 11
          },
          {
            "height": 4,
            "width": 2,
            "x": 44,
            "y": 6
          },
          {
            "height": 4,
            "width": 2,
            "x": 29,
            "y": 15
          },
          {
            "height": 2,
            "width": 4,
            "x": 36,
            "y": 35
          },
          {
            "height": 4,
            "width": 2,
            "x": 33,
            "y": 8
          },
          {
            "height": 2,
            "width": 4,
            "x": 7,
            "y": 9
          },
          {
            "height": 2,
            "width": 4,
            "x": 5,
            "y": 19
          },
          {
            "height": 2,
            "width": 4,
            "x": 41,
            "y": 29
          },
          {
            "height": 4,
            "width": 2,
            "x": 11,
            "y": 30
          },
          {
            "height": 2,
            "width": 4,
            "x": 32,
            "y": 9
          },
          {
            "height": 4,
            "width": 2,
            "x": 2,
            "y": 35
          },
          {
            "height": 4,
            "width": 2,
            "x": 15,
            "y": 16
          },
          {
            "height": 2,
            "width": 4,
            "x": 20,
            "y": 39
          },
          {
            "height": 2,
            "width": 4,
            "x": 29,
            "y": 37
          },
          {
            "height": 4,
            "width": 2,
            "x": 29,
            "y": 41
          },
          {
            "height": 4,
            "width": 2,
            "x": 17,
            "y": 37
          },
          {
            "height": 2,
            "width": 4,
            "x": 28,
            "y": 2
          },
          {
            "height": 2,
            "width": 4,
            "x": 24,
            "y": 13
          },
          {
            "height": 2,
            "width": 4,
            "x": 6,
            "y": 10
          },
          {
            "height": 2,
            "width": 4,
            "x": 27,
            "y": 14
          },
          {
            "height": 2,
            "width": 4,
            "x": 2,
            "y": 25
          },
          {
            "height": 4,
            "width": 2,
            "x": 5,
            "y": 0
          },
          {
            "height": 4,
            "width": 2,
            "x": 1,
            "y": 8
          },
          {
            "height": 4,
            "width": 2,
            "x": 37,
            "y": 27
          },
          {
            "height": 2,
            "width": 4,
            "x": 35,
            "y": 42
          },
          {
            "height": 4,
            "width": 2,
            "x": 2,
            "y": 20
          },
          {
            "height": 2,
            "width": 4,
            "x": 38,
            "y": 42
          },
          {
            "height": 2,
            "width": 4,
            "x": 33,
            "y": 11
          },
          {
            "height": 4,
            "width": 2,
            "x": 39,
            "y": 33
          },
          {
            "height": 2,
            "width": 4,
            "x": 29,
            "y": 30
          },
          {
            "height": 4,
            "width": 2,
            "x": 33,
            "y": 22
          }
        ],
        "start": {
          "x": 8,
          "y": 22
        },
        "teleportIns": [
          {
            "sequenceNumber": 0,
            "x": 38,
            "y": 33
          },
          {
            "sequenceNumber": 1,
            "x": 21,
            "y": 44
          }
        ],
        "teleportOuts": [
          {
            "sequenceNumber": 0,
            "x": 28,
            "y": 16
          },
          {
            "sequenceNumber": 1,
            "x": 33,
            "y": 20
          }
        ],
        "width": 46
      },
      "timestamp": 1648611325331
    }
  }
}
```

Notice how the fields are read in **alphabetical** order. 

**Expected behavior**

I would like the API to be able to handle cases where the json fields are in **arbitrary order** to support decoding json from Firebase.

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: JVM

Learn more about firebase here:

https://firebase.google.com/docs/database/rest/retrieve-data

**Comment by aSemy** [comment]
The error says `Fields [width, height] are required for type with serial name 'com.xenotactic.gamelogic.model.GameMap'`

In the second test, the JSON is indeed missing `width` and `height` for the `"data": { ... }` field

It looks like the JSON has a misplaced `}` bracket

```json
{
  "data": {
    "blahblah": {
      "data": { 
        // no width or height
        "rocks": [
          {
            "x": 0,
            "y": 0,
            "width": 2,
            "height": 4
          }
        ]
      }, // this bracket looks misplaced?
      "width": 10,
      "height": 10,
      "start": {
        "x": 2,
        "y": 2
      },
      "finish": {
        "x": 4,
        "y": 4
      },
      "timestamp": 123456789
    }
  }
}
```

If you move the bracket, does this test work for you?

```json
{
  "data": {
    "blahblah": {
      "data": { 
        // no width or height
        "rocks": [
          {
            "x": 0,
            "y": 0,
            "width": 2,
            "height": 4
          }
        ]
      },
      "width": 10,
      "height": 10,
      "start": {
        "x": 2,
        "y": 2
      },
      "finish": {
        "x": 4,
        "y": 4
      },
      "timestamp": 123456789
    }
  }
}
```
