### ISSUE TITLE
  kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')

### ISSUE THREAD

**Issue by vivek-modi** [Kotlin/kotlinx.serialization#1920]
Hey I am working in ktor. I am getting weird issue and I am trying to find the issue, but unable to get the proper reference.

**androidMain**

**AndroidHttpClient.kt**

  ```
  package com.example.kotlinmultiplatformsharedmodule
    
    import io.ktor.client.*
    import io.ktor.client.call.*
    import io.ktor.client.engine.okhttp.*
    import io.ktor.client.plugins.*
    import io.ktor.client.plugins.auth.*
    import io.ktor.client.plugins.auth.providers.*
    import io.ktor.client.plugins.contentnegotiation.*
    import io.ktor.client.plugins.logging.*
    import io.ktor.client.request.*
    import io.ktor.client.statement.*
    import io.ktor.http.*
    import io.ktor.serialization.*
    import io.ktor.serialization.kotlinx.*
    import io.ktor.util.reflect.*
    import io.ktor.utils.io.*
    import kotlinx.serialization.json.Json
    import java.util.concurrent.TimeUnit
    import kotlin.reflect.KClass
    
    actual fun httpClient(config: HttpClientConfig<*>.() -> Unit) = createHttpClient(config)
    
    var converter: KotlinxSerializationConverter? = null
    
    fun createHttpClient(config: HttpClientConfig<*>.() -> Unit): HttpClient {
        val httpClient = HttpClient(OkHttp) {
            config(this)
            install(Logging) {
                logger = Logger.SIMPLE
                level = LogLevel.BODY
            }
            expectSuccess = false
            install(ContentNegotiation) {
                converter = KotlinxSerializationConverter(Json {
                    prettyPrint = true
                    ignoreUnknownKeys = true
                    explicitNulls = false
                })
                register(ContentType.Application.Json, converter!!)
            }
            engine {
                config {
                    retryOnConnectionFailure(true)
                    connectTimeout(30, TimeUnit.SECONDS)
                    readTimeout(40, TimeUnit.SECONDS)
                }
            }
            defaultRequest {
                header("Client-Version", Platform().versionCode)
            }
            install(Auth) {
                bearer {
                    loadTokens {
                        BearerTokens(tokenProvider.accessToken, "")
                    }
                    refreshTokens {
                        val response =
                            client.post("https://vivek-modi/api/v1/session/refresh") {
                                markAsRefreshTokenRequest()
                                contentType(ContentType.Application.Json)
                                setBody(KtorSessionCommand(tokenProvider.refreshToken))
                            }
                        if (response.status == HttpStatusCode.Unauthorized) {
                            null
                        } else {
                            val ktorLoginResponse = response.body<KtorLoginResponse>()
                            ktorLoginResponse.accessToken?.let { ktorAccessToken ->
                                ktorAccessToken.accessToken?.let { accessToken ->
                                    ktorAccessToken.refreshToken?.let { refreshToken ->
                                        BearerTokens(accessToken, refreshToken)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        httpClient.responsePipeline.intercept(HttpResponsePipeline.Transform) { (info, body) ->
            if (body !is ByteReadChannel) return@intercept
            val response = context.response
            val apiResponse = if (response.status.value in 200..299) {
                ApiResponse.Success(
                    converter?.deserialize(context.request.headers.suitableCharset(), info.ofInnerClassParameter(), body)
                )
            } else {
                ApiResponse.Error(responseCode = response.status.value)
            }
            proceedWith(HttpResponseContainer(info, apiResponse))
        }
        return httpClient
    }
    
    fun TypeInfo.ofInnerClassParameter(): TypeInfo {
        val typeProjection = kotlinType?.arguments?.get(0)
        val kType = typeProjection!!.type!!
        return TypeInfo(kType.classifier as KClass<*>, kType.platformType)
    }
```

**Platform.kt**

    lateinit var provider: VersionAndroidProvider
    lateinit var tokenProvider: AndroidToken
    
    actual class Platform actual constructor() {
        actual val versionCode get() = provider.version
    }
    
    interface VersionAndroidProvider {
        val version: String
    }
    
    interface AndroidToken {
        val accessToken: String
        val refreshToken: String
    }

**commainMain**

**CommonHttpClient.kt**

    expect fun httpClient(config: HttpClientConfig<*>.() -> Unit = {}): HttpClient

**KtorCountryApi** 

    package com.example.kotlinmultiplatformsharedmodule
    
    import io.ktor.client.*
    import io.ktor.client.call.*
    import io.ktor.client.request.*
    import kotlinx.serialization.Serializable
    
    class KtorCountryApi(private val httpClient: HttpClient) {
        suspend fun getCountry(): ApiResponse<KtorCountriesResponse> {
            return httpClient.get {
                url("https://vivek-modi/api/v1/address/country")
            }.body()
        }
    }
    
    @Serializable
    data class KtorCountriesResponse(
        val items: List<KtorCountry>? = null
    )
    
    @Serializable
    data class KtorCountry(
        val id: String? = null,
        val isCurrentCountry: Boolean? = null,
        var isoAlpha2Code: String? = null,
        var name: String? = null,
        var phonePrefix: String? = null,
        val usesPerAreaShipping: Boolean? = null
    )
    
    @Serializable
    data class KtorLoginResponse(
        val accessToken: KtorAccessTokenInfo? = null,
    )
    
    @Serializable
    data class KtorAccessTokenInfo(
        val accessToken: String? = null,
        val refreshToken: String? = null,
        val lastRefreshDateTime: String? = null,
    )
    
    @Serializable
    data class KtorSessionCommand(
        val refreshToken: String? = null,
    )

**Error**

    2022-04-28 15:47:35.918 9413-9413/com.example.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app.dev, PID: 9413
    kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')
    JSON input: .....pping":false,"phonePrefix":"263","isCurrentCountry":false}]}
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.PolymorphicKt.throwSerializerNotFound(Polymorphic.kt:76)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:66)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:55)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:135)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:13)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:6)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:170)
        at io.ktor.client.HttpClient$4.invoke(Unknown Source:11)
        at io.ktor.client.HttpClient$4.invoke(Unknown Source:6)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invokeSuspend(Logging.kt:167)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Unknown Source:11)
        at io.ktor.client.plugins.logging.Logging$setupResponseLogging$2.invoke(Unknown Source:6)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:91)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:140)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:13)
        at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:6)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.call.HttpClientCall.body(HttpClientCall.kt:87)
        at com.example.kotlinmultiplatformsharedmodule.KtorCountryApi.getCountry(KtorCountryApi.kt:52)
        at com.example.kotlinmultiplatformsharedmodule.KtorCountryApi$getCountry$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by vivek-modi** [comment]
I fixed this problem
