### ISSUE TITLE
Multiple inheritance bug

### ISSUE THREAD

**Issue by mvanassche** [Kotlin/kotlinx.serialization#1937]
**Describe the bug**

There is an issue with multiple inheritance, using interfaces, when multiple paths leads to the same serializable class.

**To Reproduce**
```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

fun main(args: Array<String>) {
    Json.encodeToString(Z(X()))
}

@Serializable
sealed interface A {}

@Serializable
sealed interface B: A {}

@Serializable
sealed interface C: A {}

@Serializable
class X: B, C


@Serializable
class Y(val b: B)

@Serializable
class Z(val a: A)
```

**Expected behavior**

Expected that the serialization just work, but it crashes with
`Element with name 'X' is already registered`

**Environment**
 - Kotlin version: 1.6.21
 - Library version: 1.6.21
 - Kotlin platforms: JVM, JS (BOTH)

**Comment by yandroidUA** [comment]
Hi. It's still not working for objects, but works for classes.

Version: `1.4.1`

The issue that I'm receiving:
```
Exception in thread "main" java.lang.IllegalArgumentException: Element with name 'unknown-error' is already registered
	at kotlinx.serialization.descriptors.ClassSerialDescriptorBuilder.element(SerialDescriptors.kt:282)
	at kotlinx.serialization.descriptors.ClassSerialDescriptorBuilder.element$default(SerialDescriptors.kt:276)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2$1$elementDescriptor$1.invoke(SealedSerializer.kt:110)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2$1$elementDescriptor$1.invoke(SealedSerializer.kt:107)
	at kotlinx.serialization.descriptors.SerialDescriptorsKt.buildSerialDescriptor(SerialDescriptors.kt:145)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2$1.invoke(SealedSerializer.kt:107)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2$1.invoke(SealedSerializer.kt:104)
	at kotlinx.serialization.descriptors.SerialDescriptorsKt.buildSerialDescriptor(SerialDescriptors.kt:145)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2.invoke(SealedSerializer.kt:104)
	at kotlinx.serialization.SealedClassSerializer$descriptor$2.invoke(SealedSerializer.kt:103)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at kotlinx.serialization.SealedClassSerializer.getDescriptor(SealedSerializer.kt:103)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:228)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:79)
	at MainKt.encode(Main.kt:12)
	at MainKt.main(Main.kt:6)
```

Reproduce project: [reproduce.zip](https://github.com/Kotlin/kotlinx.serialization/files/10097841/reproduce.zip)

**Note!** If change the `object` to `class` code works fine, but I'd expect to have it as an `object`.

**Comment by MrPowerGamerBR** [comment]
Can confirm the issue above, it is weird that I found this bug on my project literally the same day @yandroidUA reported it lol

**Comment by sandwwraith** [comment]
@yandroidUA Can you please create a new issue and link it to this one?
