### ISSUE TITLE
decodeFromStream works, but decodeFromBufferedSource fails

### ISSUE THREAD

**Issue by zoltish** [Kotlin/kotlinx.serialization#2017]
**Describe the bug**

When using `Json.decodeFromStream` everything works as expected, using `Json.decodeFromBufferedSource` fails miserably. Ive attached a long trace at the end of my post.

From what I can tell.. the symbols are processed incorrectly, e.g. `"completedAt": 1656152065072,` is incorrect if you look at it that way, but the comma is really the separator to the next value - which is correct. 

**To Reproduce**

The data Im working with can be found [here](https://drive.google.com/file/d/1-6tQawsh_BWmqcN-qIiQmPnmf8CUjHcd/view?usp=sharing) (Google Drive).

**Expected behavior**

I expect that both approaches yield the same result.

**Environment**
 - Kotlin version: 1.6.21
 - Library version: 1.4.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 7.4.0-alpha09
 - IDE version: Android Studio Electric Eel 9

**Trace**

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Unexpected trailing comma at path: $.sessions[3].performances[0].id
 JSON input: ,"completedAt":1656152065072,".....
 at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
 at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
 at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:530)
 at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:528)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:240)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:172)
 at progression.storage.model.dto.PerformanceDto$$serializer.deserialize(PerformanceDto.kt:20)
 at progression.storage.model.dto.PerformanceDto$$serializer.deserialize(PerformanceDto.kt:20)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
 at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
 at progression.storage.model.dto.SessionDto$$serializer.deserialize(SessionDto.kt:14)
 at progression.storage.model.dto.SessionDto$$serializer.deserialize(SessionDto.kt:14)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
 at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
 at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
 at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
 at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
06:45:55.877 E at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
 at progression.storage.model.dto.TransportDto$$serializer.deserialize(TransportDto.kt:6)
 at progression.storage.model.dto.TransportDto$$serializer.deserialize(TransportDto.kt:6)
 at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
 at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:38)
 at kotlinx.serialization.json.okio.OkioStreamsKt.decodeFromBufferedSource(OkioStreams.kt:67)
 at progression.export.data.DefaultDataImporter$import$2.invokeSuspend(DefaultDataImporter.kt:149)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f9d6861, androidx.compose.runtime.BroadcastFrameClock@7d92f86, StandaloneCoroutine{Cancelling}@b984047, AndroidUiDispatcher@1533074]

```

**Comment by zoltish** [comment]
I just noticed the 1.4.0 release.. It fixes this issue. Sorry, and thank you 🦖
