### ISSUE TITLE
Kotlin2Js with @Serializable annotation: Unexpected error occurred compiling the following fragment

### ISSUE THREAD

**Issue by egoossens** [Kotlin/kotlinx.serialization#202]
I'm getting the following error trying to compile a rather basic Kotlin file.
The error disappears when I remove the `@Serializable` annotations.

Kotlin 1.2.60
Serialization 0.6.1

Any idea how to fix this?

Thanks.

```
org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: 'package com.tastyelectrons.autopilog.repositories.flightaware

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AirlineFlightInfoResponseV2(@SerialName("AirlineFlightInfoResult") var airlineFlightInfoResult: AirlineFlightInfoResult) {
    @Serializable
    data class AirlineFlightInfoResult(var faFlightID: String,
                                       var ident: String,
                                       @SerialName("tailnumber") var tailNumber: String,
                                       @SerialName("codeshares") var codeShares: List<String> = listOf())
}' at (1,1) in /Users/egoossens/Apps/autopilog/lib/repositories/repositories-common/src/main/kotlin/com/tastyelectrons/autopilog/repositories/flightaware/AirlineFlightInfoResponseV2.kt
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:403)
        at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:312)
        at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:274)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.java:134)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.java:96)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:150)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:278)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:80)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:94)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:408)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:929)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:969)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:928)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:407)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:478)
        at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:460)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator.generateSerialDesc(SerializerJsTranslator.kt:70)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generate(SerializerCodegen.kt:43)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializerJsTranslator$Companion.translate(SerializerJsTranslator.kt:372)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationJsExtension.generateClassSyntheticParts(SerializationJsExtension.kt:30)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.generateClassSyntheticParts(ClassTranslator.kt:153)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:111)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:564)
        at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.generateClassOrObject(DeclarationBodyVisitor.kt:57)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:108)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:568)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:44)
        at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.visitClassOrObject(DeclarationBodyVisitor.kt:45)
        at org.jetbrains.kotlin.js.translate.declaration.DeclarationBodyVisitor.visitClassOrObject(DeclarationBodyVisitor.kt:32)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:34)
        at org.jetbrains.kotlin.js.translate.general.TranslatorVisitor.traverseContainer(TranslatorVisitor.java:43)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:92)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:568)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:44)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:37)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:34)
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:395)
        ... 35 more
```

**Comment by sandwwraith** [comment]
I've copied your code snippet from stacktrace and it has compiled normally for me. Can you please provide more info about file which causes this? 

Probably making this class non-inner should help.

**Comment by egoossens** [comment]
It might be related to applying the kotlinx-serialization gradle plugin to interdependent projects...
It works better when keeping things under the same project.
Sorry I don't have time to investigate further.
