### ISSUE TITLE
Error inlining call `encodeToString`

### ISSUE THREAD

**Issue by hanneskaeufler** [Kotlin/kotlinx.serialization#2090]
I am trying to serialize a simple data class to json but running into

```
Caused by: org.jetbrains.kotlin.codegen.inline.InlineException: Method inlining CALL 'public final fun encodeToString <T> (value: T of kotlinx.serialization.SerialFormatKt.encodeToString): kotlin.String [inline] declared in kotlinx.serialization.SerialFormatKt' type=kotlin.String origin=null: couldn't inline method call
Cause: encodeToString (Lkotlinx/serialization/StringFormat;Ljava/lang/Object;)Ljava/lang/String;:

        at org.jetbrains.kotlin.codegen.inline.MethodInliner.wrapException(MethodInliner.kt:1020)
        at org.jetbrains.kotlin.codegen.inline.MethodInliner.preprocessNodeBeforeInline(MethodInliner.kt:804)
        at org.jetbrains.kotlin.codegen.inline.MethodInliner.markPlacesForInlineAndRemoveInlinable(MethodInliner.kt:510)
        at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:94)
        at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:73)
        at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:118)
        at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:50)
        ... 127 more
Caused by: java.lang.NullPointerException: insnList.first must not be null
        at org.jetbrains.kotlin.codegen.optimization.common.InsnSequence.<init>(Util.kt:47)
        at org.jetbrains.kotlin.codegen.optimization.fixStack.FixStackContext.<init>(FixStackContext.kt:51)
        at org.jetbrains.kotlin.codegen.optimization.fixStack.FixStackMethodTransformer.transform(FixStackMethodTransformer.kt:31)
        at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
        at org.jetbrains.kotlin.codegen.inline.MethodInliner.preprocessNodeBeforeInline(MethodInliner.kt:801)
```

**To Reproduce**

```
# in foo.kt
@Serializable
data class Foo(
    val name: String,
)

# in main.kt
import kotlinx.serialization.json.Json
import kotlinx.serialization.encodeToString

val p = Foo("bar")
print(Json.encodeToString(p))

```

**Expected behavior**
Seeing the serialized string on the console

**Environment**
 - Kotlin version: Compiler version 1.7.20, language version 1.6
 - Library version: 1.3.3, 1.4.1, tried both with not visible change
 - Kotlin platforms: JVM
 - Gradle version: Running with bazel, not gradle
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
Have you tried the same code with the actual language version (1.7 or 1.8)? Does it work? Why do you need an old language version?

**Comment by sandwwraith** [comment]
Unfortunately, I was unable to reproduce the issue in a simple Gradle project. Moreover, language version settings should affect only source code compatibility (in theory). Can you share the Bazel project with the reproducer?

**Comment by hanneskaeufler** [comment]
I did move into a different direction with the project and will probably not invest the time anymore to look for a fix for this. Sorry bout the noise.
