### ISSUE TITLE
configparser does not handle @Optional values

### ISSUE THREAD

**Issue by Shengaero** [Kotlin/kotlinx.serialization#211]
When using the configparser library, I discovered the following doesn't work:
```kotlin
package xyz.laxus.bot

import kotlinx.serialization.Optional
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BotConfig internal constructor(
    val token: String,
    @SerialName("command.groups") val commandGroups: List<String>,
    @Optional val mode: RunMode = RunMode.SERVICE,
    @Optional val test: Boolean = false,
    @Optional val keys: BotConfig.Keys = BotConfig.Keys(),
    @Optional @SerialName("call.cache") val callCache: CallCache = CallCache()
) {
    @Serializable
    data class Keys internal constructor(
        @Optional @SerialName("dbots") val dBotsKey: String? = null,
        @Optional @SerialName("dbotslist") val dBotsListKey: String? = null,
        @Optional @SerialName("youtube") val youtubeKey: String? = null
    )

    @Serializable
    data class CallCache internal constructor(@Optional val size: Int = 300)
}
```

This produces the following error when attempting to use `ConfigParser.parse` on a `Config` instance without the value `test` being defined:

```
No configuration setting found for key 'test'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'test'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getValue(SimpleConfig.java:207)
	at com.typesafe.config.impl.SimpleConfig.getValue(SimpleConfig.java:41)
	at org.jetbrains.kotlinx.serialization.config.ConfigParser$ConfigReader.getTaggedConfigValue(ConfigReader.kt:84)
	at org.jetbrains.kotlinx.serialization.config.ConfigParser$ConfigReader.getTaggedConfigValue(ConfigReader.kt:74)
	at org.jetbrains.kotlinx.serialization.config.ConfigParser$ConfigConverter.readTaggedValue(ConfigReader.kt:64)
	at kotlinx.serialization.TaggedInput.readTaggedBoolean(Tagged.kt:212)
	at kotlinx.serialization.TaggedInput.readBooleanElementValue(Tagged.kt:249)
```

**Comment by markGilchrist** [comment]
@sandwwraith  I am still finding this issue in the latest version ('0.10.0'), 

@Optional is not taking the default value, it is null instead
