### ISSUE TITLE
Protobuf: Unsupported start group or end group wire type: 7

### ISSUE THREAD

**Issue by wilkomanger** [Kotlin/kotlinx.serialization#2122]
**Describe the bug**

When trying to decode a certain message using `ProtoBuf.decodeFromByteArray(bytes)`, the following exception is thrown:

```
kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 7
	at app//kotlinx.serialization.protobuf.internal.ProtobufReader.skipElement(ProtobufReader.kt:64)
	at app//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeElementIndex(ProtobufDecoding.kt:230)
	at app//org.dotlin.compiler.dart.element.DartPackageElement$$serializer.deserialize(Elements.kt:53)
	at app//org.dotlin.compiler.dart.element.DartPackageElement$$serializer.deserialize(Elements.kt:53)
	at app//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:196)
	at app//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:186)
	at app//kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
	at app//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:196)
	at app//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:186)
	at app//kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
	at app//org.dotlin.compiler.backend.steps.src2ir.DartPackageModuleResolver.deserializeLibsOf(DartPackageModuleResolver.kt:149)
```

**To Reproduce**
Call [`ProtoBuf.decodeFromByteArray(bytes)`](https://github.com/dotlin-org/dotlin/commit/05eeb7e3f4524b03ea48206bb42c8423b6751764#diff-bc85e86ac7ee5ff3de1446bff77ccfe8f300c15709fda0a821693256f86ae915R118), with the following Protobuf message (base64):
```
CtcCCLadARIyZmlsZTovLy90bXAvNDQ1MjkzNTg1MDM4NjU2NjkxOS8xNjcwODY1ODk2MzAxLmRh
cnQaEjE2NzA4NjU4OTYzMDEuZGFydCKIAgi4nQESgQIIup0BEg9ZZXRBbm90aGVyQ2xhc3Ma6QEI
u50BEAAYACIPeWV0QW5vdGhlckZpZWxkKAAwATgAQABKxQEKMm9yZy5kb3RsaW4uY29tcGlsZXIu
ZGFydC5lbGVtZW50LkRhcnRJbnRlcmZhY2VUeXBlEo4BCP81GogBCNs5GgMIoToifgjTMRI5CjJv
cmcuZG90bGluLmNvbXBpbGVyLmRhcnQuZWxlbWVudC5EYXJ0SW50ZXJmYWNlVHlwZRIDCNs5EjkK
Mm9yZy5kb3RsaW4uY29tcGlsZXIuZGFydC5lbGVtZW50LkRhcnRJbnRlcmZhY2VUeXBlEgMI2zka
AwihOg==
```

The data classes describing the protobuf are [here](https://github.com/dotlin-org/dotlin/commit/05eeb7e3f4524b03ea48206bb42c8423b6751764#diff-426dbb0d9b650d55659165cfdeebd9f4c70472e2a764dcd05b850aea24527ef3).

The protobuf message above is generated by the Dart code in [here](https://github.com/dotlin-org/dotlin/commit/05eeb7e3f4524b03ea48206bb42c8423b6751764#diff-9a3e30c20b27c2213fc89bca3c9a9ee020af7235d2734903b25a1781389159dfR22). It's also possible that there's something wrong with this code, or with the protobuf Dart library, instead of kotlinx.serialization itself.

This Dart code uses [this `.proto file`](https://github.com/dotlin-org/dotlin/commit/05eeb7e3f4524b03ea48206bb42c8423b6751764#diff-1b91cad1b18484942a6965302c79e4e85ea45580303094594aed69a304383aee), generated by [this code](https://github.com/dotlin-org/dotlin/commit/05eeb7e3f4524b03ea48206bb42c8423b6751764#diff-60bfd1b3f4368672d2b2521c943d38ea1dd99e84f901af542d9db31eb8cc9142R30).

**Expected behavior**

That the protobuf is deserialized successfully.

Any idea what's going on?

**Environment**
 - Kotlin version: 1.7.21
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: JVM
 - Gradle version: 7.2

**Comment by wilkomanger** [comment]
Great, that worked! Thanks a lot!
