### ISSUE TITLE
class kotlinx.serialization.json.JsonLiteral cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by TheFruxz** [Kotlin/kotlinx.serialization#2198]
**Describe the bug**

I receive a exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ClassCastException: class kotlinx.serialization.json.JsonLiteral cannot be cast to class java.lang.String (kotlinx.serialization.json.JsonLiteral is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:157)
	at kotlinx.serialization.json.internal.AbstractJsonTreeEncoder.encodeSerializableValue(TreeJsonEncoder.kt:257)
	at kotlinx.serialization.internal.TaggedEncoder.encodeSerializableElement(Tagged.kt:137)
	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
	at kotlinx.serialization.json.internal.AbstractJsonTreeEncoder.encodeSerializableValue(TreeJsonEncoder.kt:257)
	at kotlinx.serialization.json.internal.TreeJsonEncoderKt.writeJson(TreeJsonEncoder.kt:21)
	at kotlinx.serialization.json.Json.encodeToJsonElement(Json.kt:106)
	at de.fruxz.ascend.tool.delegate.JsonProperty.fromProvided(JsonProperty.kt:51)
	at de.fruxz.ascend.tool.delegate.JsonProperty.access$fromProvided(JsonProperty.kt:18)
	at de.fruxz.ascend.tool.delegate.JsonProperty$content$newObject$1.invoke(JsonProperty.kt:80)
	at de.fruxz.ascend.tool.delegate.JsonProperty$content$newObject$1.invoke(JsonProperty.kt:79)
	at de.fruxz.ascend.extension.data.JSONKt.buildJsonObject(JSON.kt:149)
	at de.fruxz.ascend.tool.delegate.JsonProperty.setContent(JsonProperty.kt:79)
	at de.fruxz.ascend.tool.delegate.JsonProperty.<init>(JsonProperty.kt:90)
	at de.fruxz.ascend.DemoKt.<clinit>(Demo.kt:58)
```

and it seems for me, that it comes from kotlinx.serialization itself, but unsure due to this very specific and complex use case.

Here is the failing code:
https://github.com/TheFruxz/Ascend/blob/fix/weirdError/src/main/kotlin/de/fruxz/ascend/Demo.kt
the var `list` is the property, where the error occurs.
More specifically, the error occurs on `JsonProperty.kt:51` during the second run (the run after the first initializing run)

I tried it on Kotlin 1.8.10 and 1.8.20-Beta, also on this libraries 1.4.1 and 1.5.0-RC

**Environment**
 - Kotlin version: 1.8.10 & 1.8.20-Beta
 - Library version: 1.4.1 & 1.5.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 7.5.1 & 8.0.0 & 8.0.1
 - Other relevant context
    - OS: macOS 13.2.1 (Apple Silicon)
    - JRE: 18

**Comment by TheFruxz** [comment]
I would like to deeply apologize, after a long investigation I found the erroneous code. It was `is JsonArray -> it.toList()...` which led to this incompatible content and actually had nothing to do with the kotlinx.serialization library. I thank you for the feedback, which had helped me to identify the problem.
