### ISSUE TITLE
java.lang.NoSuchMethodError when parsing a JSON stream on Java 8

### ISSUE THREAD

**Issue by madhead** [Kotlin/kotlinx.serialization#2218]
**Describe the bug**

I suspect the JSON format to be prone to this issue: https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243

The problem seems to be in the `CharsetReader`'s constructor, on the line ＃23:

https://github.com/Kotlin/kotlinx.serialization/blob/6dbb8a9d839fb817ece7566f991fb450a226ea31/formats/json/jvmMain/src/kotlinx/serialization/json/internal/CharsetReader.kt#L18-L24

It seem that this class is compiled with a higher language level and, running on Java 8, causing the issue.

I've `javap`-ed the `CharsetReader` class (from the 1.5.0 versio of the library) and although I see the its class version is 52 (Java 8) it seems to be not enough for this nasty bug. The bytecode seems to use the `ByteBuffer`, which is incorrect :point_down: 

![image](https://user-images.githubusercontent.com/577360/222816029-8ff15f26-cf88-4778-969a-c91b55cb5730.png)

It [seems](https://github.com/plasma-umass/doppio/issues/497#issuecomment-353394008) that a proper compiler option needs to be passed during the compilation process. The other way to solve this is [using](https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243) a manual cast.

**To Reproduce**

Please, refer to this minimal reproducible example: https://github.com/madhead/kotlinx-serialization-json-java8. Follow its README.

Basically, to reproduce the issues one needs to call `Json.decodeFromStream` on Java 8. As a result, he gets an exception like this:

```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at kotlinx.serialization.json.internal.CharsetReader.<init>(CharsetReader.kt:23)
        at kotlinx.serialization.json.internal.JavaStreamSerialReader.<init>(JvmJsonStreams.kt:258)
        at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:59)
        at me.madhead.kotlinx.serialization.json.java8.AppKt.main(App.kt:13)
        at me.madhead.kotlinx.serialization.json.java8.AppKt.main(App.kt)
```

**Expected behavior**

No exception is thrown, the stream is parsed correctly.

**Environment**

 - Kotlin platforms: JVM
 - JVM: 8.x
    ```
    openjdk version "1.8.0_322"
    OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
    OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
    ```
 - Kotlin version: 1.8.10
 - Library version: 1.5.0

**Comment by madhead** [comment]
Actually, `--release` is a `javac` option, a shortcut over `--source` + `--target` + `--bootclasspath` ([JEP ＃247](https://openjdk.org/jeps/247), and an [article for mortals](https://www.baeldung.com/java-compiler-release-option), where they explain the need for this option… with `Buffer`'s `flip()` method!)

There [seems to be no such option as `bootclasspath` for the `kotlinc`](https://discuss.kotlinlang.org/t/bootclasspath-for-kotlinc/6341/9), right?

So, I guess, casting manually is the easiest fix for this particular bug. There are only two `flips` in the whole codebase…

**Comment by madhead** [comment]
@Lukellmann, indeed. But here we need specifically the `bootclasspath`, I guess. It's not only about targeting a specific JVM version, but using it's `rt.jar` during the compilation process:

```
javac … -Xbootclasspath ${jdk8path}/jre/lib/rt.jar
```

Also, the default value for the `release` is already 1.8 and it didn't work apparently.

Anyway, I'm just afraid of introducing such a change to the build process (and I obviously don't have enough knowledge to do that). I guess it may require some access to the TeamCity configs or what. So let the team think of it.
