### ISSUE TITLE
Recommend changing serial name for surrogate descriptor

### ISSUE THREAD

**Issue by nacyolsa** [Kotlin/kotlinx.serialization#2247]
**Describe the bug**

I'm getting the following error with version 1.5.0. It works fine with 1.3.3.

```
Caused by: java.lang.reflect.InvocationTargetException: Multiple sealed subclasses of 'class com.project.PetDboSchema' have the same serial name 'class com.project.PetDboSurrogate': 'class com.project.PetDbo', 'class com.project.PetDboSurrogate'
	at kotlinx.serialization.internal.PlatformKt.invokeSerializerOnCompanion(Platform.kt:114)
	at kotlinx.serialization.internal.PlatformKt.constructSerializerForGivenTypeArgs(Platform.kt:46)
	at kotlinx.serialization.internal.PlatformKt.constructSerializerForGivenTypeArgs(Platform.kt:35)
	at kotlinx.serialization.internal.PlatformKt.compiledSerializerImpl(Platform.kt:22)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializerOrNull(Serializers.kt:230)
	at kotlinx.serialization.SerializersKt.serializerOrNull(Unknown Source)
	at org.litote.kmongo.serialization.KMongoSerializationRepository.getBaseSerializer(KMongoSerializationRepository.kt:155)
	at org.litote.kmongo.serialization.KMongoSerializationRepository.getSerializer(KMongoSerializationRepository.kt:183)
	at org.litote.kmongo.serialization.SerializationCodec.encode(SerializationCodec.kt:61)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:200)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:170)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:63)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceiveAsync(InternalStreamConnection.java:451)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceiveAsync(UsageTrackingInternalConnection.java:162)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceiveAsync(DefaultConnectionPool.java:681)
	at com.mongodb.internal.connection.CommandProtocolImpl.executeAsync(CommandProtocolImpl.java:77)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:259)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:242)
	at com.mongodb.internal.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:148)
	at com.mongodb.internal.connection.DefaultServer$AsyncOperationCountTrackingConnection.commandAsync(DefaultServer.java:456)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommandAsync(MixedBulkWriteOperation.java:524)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeBulkWriteBatchAsync$10(MixedBulkWriteOperation.java:421)
	at com.mongodb.internal.async.function.AsyncCallbackLoop.run(AsyncCallbackLoop.java:55)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatchAsync(MixedBulkWriteOperation.java:452)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeAsync$6(MixedBulkWriteOperation.java:362)
	at com.mongodb.internal.operation.OperationHelper.lambda$withAsyncSourceAndConnection$4(OperationHelper.java:634)
	at com.mongodb.internal.operation.OperationHelper.lambda$withAsyncSuppliedResource$6(OperationHelper.java:651)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$2(AsyncCallbackSupplier.java:99)
	at com.mongodb.internal.operation.OperationHelper.lambda$withAsyncSuppliedResource$7(OperationHelper.java:653)
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:133)
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:122)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.DefaultConnectionPool.lambda$getAsync$0(DefaultConnectionPool.java:198)
	at com.mongodb.internal.connection.DefaultConnectionPool.lambda$getAsync$1(DefaultConnectionPool.java:225)
	at com.mongodb.internal.connection.DefaultConnectionPool$Task.doComplete(DefaultConnectionPool.java:1385)
	at com.mongodb.internal.connection.DefaultConnectionPool$Task.execute(DefaultConnectionPool.java:1371)
	at com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.workerRun(DefaultConnectionPool.java:1311)
	at com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.runAndLogUncaught(DefaultConnectionPool.java:1342)
	at com.mongodb.internal.connection.DefaultConnectionPool$AsyncWorkManager.lambda$initUnlessClosed$0(DefaultConnectionPool.java:1275)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.lang.IllegalStateException: Multiple sealed subclasses of 'class com.project.PetDboSchema' have the same serial name 'class com.project.PetDboSurrogate': 'class com.project.PetDbo', 'class com.project.PetDboSurrogate'
	at kotlinx.serialization.SealedClassSerializer.<init>(SealedSerializer.kt:135)
	at kotlinx.serialization.SealedClassSerializer.<init>(SealedSerializer.kt:97)
	at com.project.PetDboSchema$Companion.serializer(PetDbo.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlinx.serialization.internal.PlatformKt.invokeSerializerOnCompanion(Platform.kt:109)
	... 51 more
```

**To Reproduce**

I have structure like this.

```
@Serializable
sealed interface PetDboSchema : Versionable

@Serializable(with = PetDboSerializer::class)
data class PetDbo(
    @SerialName("_id")
    @Serializable(with = UUIDSerializer::class)
    val id: UUID,
    val field1: String
) : PetDboSchema

@Serializable
data class PetDboSurrogate(
    @SerialName("_id")
    @Serializable(with = UUIDSerializer::class)
    val id: UUID,
    val field1: String
) : PetDboSchema
```

Issue occurs in runtime. For example when I run tests.

**Expected behavior**

**Environment**
 - Kotlin version: 1.7.20
 - Library version: 1.5.0, with 1.3.3 works fine
 - Kotlin platforms: graalvm-11
 - Gradle version: 7.5.1

**Comment by sandwwraith** [comment]
Can you post your `PetDboSerializer`, too, please? I suspect that its `descriptor` has the same serial name as the surrogate, thus triggering the error.

**Comment by nacyolsa** [comment]
> Can you post your `PetDboSerializer`, too, please? I suspect that its `descriptor` has the same serial name as the surrogate, thus triggering the error.

```
object PetDboSerializer : KSerializer<PetDbo> {

    override val descriptor: SerialDescriptor = PetDboSurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: PetDbo) =
        encoder.encodeSerializableValue(PetDboSurrogate.serializer(), value.toSurrogate())

    override fun deserialize(decoder: Decoder): PetDbo =
        decoder.deserialize<PetDboSchema, PetDbo, PetDboSurrogate>(schemaDeserializer = PetDboSchemaDeserializer)

}```

**Comment by sandwwraith** [comment]
To avoid such issues in the future, it's better to improve examples in this section: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#composite-serializer-via-surrogate

**Comment by nacyolsa** [comment]
Option with factory function solved my issue. @sandwwraith thanks for help.

**Comment by sandwwraith** [comment]
I'll left this open as there's work in the documentation section to be done.

**Comment by nacyolsa** [comment]
When I use custom descriptor unexpected `___type` field is assigned to my object is it some known behavior? 
It occurs only in 1.5.0. With 1.3.3 it's not assigned. I'm also not sure if this issue is on Kotlinx side or on kmongo which I use.

**Comment by sandwwraith** [comment]
We do not add anything with underscores in the beginning, so it's likely from a KMongo side
