### ISSUE TITLE
Auto-generated serializer name gives issues with ASM's `Remapper`

### ISSUE THREAD

**Issue by bddckr** [Kotlin/kotlinx.serialization#2285]
**Describe the bug**

I'm using the Android Gradle Plugin (AGP) together with a custom `AsmClassVisitorFactory`. Inside that factory, I return an instance of ASM's  `ClassRemapper` that uses my own subclass of ASM's `Remapper`. This is exactly what many plugins do in the Android ecosystem: Hilt is a big example, and so is [Sentry's Gradle plugin](https://github.com/getsentry/sentry-android-gradle-plugin). One plugin that runs into issue is [HiddenApiRefinePlugin](https://github.com/RikkaApps/HiddenApiRefinePlugin).

AGP's API requires us to use ASM, which leads us to the problem: If such instrumentation is applied to the auto-generated serializer class, [ASM's `Remapper` implementation strips the leading `$` from the name](https://gitlab.ow2.org/asm/asm/-/blob/9bf7d41ca5212d82b6383104d3340d3e897fea42/asm-commons/src/main/java/org/objectweb/asm/commons/Remapper.java#L287-292). It then rewrites that type name with the new name.

**To Reproduce**

Use a plugin in the Android ecosystem that ultimately tries to instrument the auto-generated serializer.

**Expected behavior**

The project should compile with instrumentation applied, but it fails with a compile error:
```
> Task :feature:set-dpc:compileDebugKotlin FAILED
e: java.lang.AssertionError: Class with incorrect id found: expected MyTest.$serializer, actual MyTest.serializer
        at org.jetbrains.kotlin.load.kotlin.JavaClassDataFinder.findClassData(JavaClassDataFinder.kt:29)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer.createClass(ClassDeserializer.kt:44)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer.access$createClass(ClassDeserializer.kt:27)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer$classes$1.invoke(ClassDeserializer.kt:29)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer$classes$1.invoke(ClassDeserializer.kt:29)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer.deserializeClass(ClassDeserializer.kt:34)
        at org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer.deserializeClass$default(ClassDeserializer.kt:33)
        at org.jetbrains.kotlin.serialization.deserialization.DeserializationComponents.deserializeClass(context.kt:62)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.deserializeClass(DeserializedMemberScope.kt:144)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:120)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:311)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:310)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:321)
        at org.jetbrains.kotlin.resolve.scopes.MemberScopeKt.getDescriptorsFiltered(MemberScope.kt:87)
        at org.jetbrains.kotlin.resolve.scopes.MemberScopeKt.getDescriptorsFiltered$default(MemberScope.kt:82)
        at org.jetbrains.kotlinx.serialization.compiler.resolve.KSerializationUtilKt.getClassSerializer(KSerializationUtil.kt:239)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.TypeUtilKt.findTypeSerializer(TypeUtil.kt:161)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.TypeUtilKt.findTypeSerializerOrContextUnchecked(TypeUtil.kt:132)
        at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.checkType(SerializationPluginDeclarationChecker.kt:394)
        at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.analyzePropertiesSerializers(SerializationPluginDeclarationChecker.kt:346)
        at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.check(SerializationPluginDeclarationChecker.kt:59)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.runDeclarationCheckers(ModifiersChecker.java:285)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifierListCommon(ModifiersChecker.java:224)
        at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifiersForDeclaration(ModifiersChecker.java:183)
        at org.jetbrains.kotlin.resolve.DeclarationsChecker.process(DeclarationsChecker.kt:95)
        at org.jetbrains.kotlin.resolve.BodyResolver.resolveBodies(BodyResolver.java:258)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:227)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:130)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
        at jdk.internal.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment**
 - Kotlin version: 1.8.20
 - `org.jetbrains.kotlin.plugin.serialization:1.8.20`
 - `org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0`
 - Kotlin platforms: Android
 - Gradle version: 8.1

---

I'm happy to report this issue elsewhere, but it felt best here because users would have to wait for all their instrumentation plugins to be fixed. Most users are probably not running into this issue, though, as most instrumentation plugins only return true from `AsmClassVisitorFactory.isInstrumentable` for types that were annotated specifically by the user. Since the auto-generated serializer is auto-generated, users cannot annotate it (at least not easily).  
However, in my case at least, the instrumentation is run on all classes, as the class visitor is forced to check for type details before it might bail out, not actually changing the type.

Is this something `org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer.createClass` from the stack trace could somehow resolve?

**Comment by sandwwraith** [comment]
According to Java naming rules, class names that start with dollar sign are perfectly valid identifiers, so it is definitely an issue of ASM's remapper that should be fixed. (Also, given that this is a nested class, its real FQ name should contain two dollar signs). And we'll likely be unable to change this name, because it affects binary compatibility.

Regarding the issue: there are two entirely different parts of stacktrace. `org.jetbrains.kotlinx.serialization.compiler` is a part of kotlinx-serialization plugin, which searches for defined `$serializer`. `org.jetbrains.kotlin.serialization.deserialization.ClassDeserializer`, however, is not related to serialization plugin in any way — it is a standard compiler mechanism that deserializes contents of `kotlin.Metadata` class annotation, that contains Kotlin-specific data on a .class file. What this error really says, that you've renamed the class to `serializer`, but its metadata still contains `$serializer` name and thus compiler can't proceed. You can try to alter metadata contents as well (e.g. with kotlinx-metadata-jvm library), but I doubt that serialization plugin would be able to find this serializer later.

I can see, however `Subclasses can override.` in documentation for `mapInnerClassName`. Can't you simply change this behavior or filter `$serializer` classes from processing?

**Comment by bddckr** [comment]
That makes sense; thank you for the additional insight!

> (Also, given that this is a nested class, its real FQ name should contain two dollar signs).

I accidentally removed too much from the error info above in a quest to hide internal product details, so this matches what I'm seeing.

> I can see, however `Subclasses can override.` in documentation for `mapInnerClassName`. Can't you simply change this behavior or filter `$serializer` classes from processing?

I can do so, but only some of the instrumentation plugins I'm using allow me to change _their_ implementation of the remapper. That said, a generic solution could be done by forcing Gradle to resolve a newer ASM version (that would likely fix this on their end) that these plugins would use. Of course, that assumes no compatibility issues between the ASM version the plugin uses vs. the new one with the fix.

Considering this would be a breaking change for `kotlinx.serialization`, I think the best course of action is for me to raise this with ASM (something I'm planning to do anyway) and then try to get all plugins to use a new version of it to fix it. The plugins that run into this issue can either be forced to use the latest version, or I'll have to raise it with them to update their usage of ASM.

Thanks for your help. I'll have to re-do the PR for one of the plugins that is linked above (https://github.com/RikkaApps/HiddenApiRefinePlugin/pull/22) to ensure multiple dollar signs (due to the nesting of classes) is no problem. I'll raise this with ASM and try to get a patch up there.

Closing this as resolved!

**Comment by bddckr** [comment]
For anyone wondering in the future: I've opened an issue with ASM [here](https://gitlab.ow2.org/asm/asm/-/issues/317999).
