### ISSUE TITLE
NoSuchMethodError when parsing a JSON stream on Java 8

### ISSUE THREAD

**Issue by KosmX** [Kotlin/kotlinx.serialization#2326]
**Describe the bug**
Similar issue just with a different method:
#2218 

Java changed some function signatures on java 9, when building on java 9+ with targeting java 8, invalid bytecode is produced.  
java 9+ function: `ByteBuffer position(int newPosition)`
java 8 function: `Buffer position(int newPosition)`

**To Reproduce**
Attach a code snippet or test data if possible.
```kt
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import kotlinx.serialization.json.encodeToStream
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream

@Serializable
data class Data(val name: String, val entry: Int = 0)

@OptIn(ExperimentalSerializationApi::class)
fun main() {
    val out = ByteArrayOutputStream()
    Json.encodeToStream(Data("meow?", entry = 42), out)
    val inputStream = ByteArrayInputStream(out.toByteArray())
    Json.decodeFromStream<Data>(inputStream).let { println(it) } //⚡
}
```
will produce
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at kotlinx.serialization.json.internal.CharsetReader.fillByteBuffer(CharsetReader.kt:106)
	at kotlinx.serialization.json.internal.CharsetReader.doRead(CharsetReader.kt:78)
	at kotlinx.serialization.json.internal.CharsetReader.read(CharsetReader.kt:64)
	at kotlinx.serialization.json.internal.JavaStreamSerialReader.read(JvmJsonStreams.kt:261)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.preload(JsonLexer.kt:87)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.<init>(JsonLexer.kt:47)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.<init>(JsonLexer.kt:38)
	at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:36)
	at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61)
	at SerialBugDemoKt.main(SerialBugDemo.kt:20)
	at SerialBugDemoKt.main(SerialBugDemo.kt)

Process finished with exit code 1
```
**Expected behavior**
Not crashing

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.5.1
 - Kotlin platforms: JVM **1.8** , newer JVM version don't crash
 - Gradle version: 8.1.1

**Comment by KosmX** [comment]
Workaround:
```kt

fun InputStream.asString(): String = String(readBytes())
// and then 
Json.decodeFromString<DatabaseFiles>(it.asString())
```
