### ISSUE TITLE
JSON namingStrategy: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token

### ISSUE THREAD

**Issue by otuva** [Kotlin/kotlinx.serialization#2334]
### Describe the bug

I'm trying to make every JSON key camel-case, regardless of how it's formatted. Like:

` ProjectName -> projectName`

or

`project_name -> projectName`

#### Things that do not work

- I want to do this on a large scale so using @SerialName on every single parameter is not plausible, requires too much work and is error-prone
- Following returned JSON key naming strategy breaks Kotlin code style guides and would be backward incompatible

I looked at the docs and saw [this example](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#global-naming-strategy)

However, using `namingStrategy` on JSON builder, won't work the way I wanted to

### To Reproduce

Although example code works to serialize class parameters to snake case

**first snippet**
```kotlin
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNamingStrategy

@OptIn(ExperimentalSerializationApi::class)
fun main() {
    @Serializable
    data class Project(val projectName: String, val projectOwner: String)

    val format = Json { namingStrategy = JsonNamingStrategy.SnakeCase }

    val project = format.decodeFromString<Project>("""{"project_name":"kotlinx.coroutines", "project_owner":"Kotlin"}""")
    println(format.encodeToString(project.copy(projectName = "kotlinx.serialization")))
// {"project_name":"kotlinx.serialization","project_owner":"Kotlin"}
}
```

---

This code doesn't work to deserialize pascal case to snake case

**second snippet**
```kotlin
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNamingStrategy

@OptIn(ExperimentalSerializationApi::class)
fun main() {
    @Serializable
    data class Project(val project_name: String, val project_owner: String)

    val format = Json { namingStrategy = JsonNamingStrategy.SnakeCase }

    val project = format.decodeFromString<Project>("""{"ProjectName":"kotlinx.coroutines", "ProjectOwner":"Kotlin"}""")
    println(format.encodeToString(project.copy(project_name = "kotlinx.serialization")))
}
```

Running second snippet results in exception

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'ProjectName' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"ProjectName":"kotlinx.coroutines", "ProjectOwner":"Kotlin"}
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:579)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:254)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:240)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:175)
    at MainKt$main$Project$$serializer.deserialize(Main.kt:9)
    at MainKt$main$Project$$serializer.deserialize(Main.kt:9)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
    at MainKt.main(Main.kt:17)
    at MainKt.main(Main.kt)
```

#### Custom `JsonNamingStrategy`

Implementing custom name strategy resulted in the same error above

**third snippet**
```kotlin
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNamingStrategy
import kotlinx.serialization.descriptors.SerialDescriptor

@OptIn(ExperimentalSerializationApi::class)
public object CamelCase : JsonNamingStrategy {
    override fun serialNameForJson(descriptor: SerialDescriptor, elementIndex: Int, serialName: String): String {
        val words = serialName.split(Regex("[^a-zA-Z0-9]+"))
        return buildString {
            words.forEachIndexed { index, word ->
                if (index == 0) {
                    append(word.lowercase())
                } else {
                    append(word.replaceFirstChar(Char::titlecase))
                }
            }
        }
    }

    override fun toString(): String = "CamelCase"
}

@OptIn(ExperimentalSerializationApi::class)
public fun main() {
    @Serializable
    data class Project(val projectName: String, val projectOwner: String)

    val format = Json { namingStrategy = CamelCase }

    val project =
        format.decodeFromString<Project>("""{"project_name":"kotlinx.coroutines", "project_owner":"Kotlin"}""")
    println(format.encodeToString(project.copy(projectName = "kotlinx.serialization")))
}
```

Again, running this code throws exception

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'project_name' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"project_name":"kotlinx.coroutines", "project_owner":"Kotlin"}
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:579)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:254)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:240)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:175)
    at MainKt$main$Project$$serializer.deserialize(Main.kt:28)
    at MainKt$main$Project$$serializer.deserialize(Main.kt:28)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
    at MainKt.main(Main.kt:37)
    at MainKt.main(Main.kt)
```

### Expected behavior

`namingStrategy` should parse JSON fields according to given strategy, but currently it does not. Fails saying, Unexpected JSON token

### Environment
 - Kotlin version: 1.8.21
 - Library version: 
   - `kotlin("plugin.serialization") version "1.8.21"`
   - `implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.1")`
 - Kotlin platforms: JVM, JS, Native
 - Gradle version: 7.6.1
 - IDE version: IntelliJ IDEA 2023.1.2 (Ultimate)
 - Other relevant context: 
```
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

**Comment by otuva** [comment]
@sandwwraith I was able to reproduce this with different machines

**Comment by sandwwraith** [comment]
It seems you've misunderstood `namingStrategy` feature. It defines a transformation of a property name, and a result of transformation is a single name. Therefore, no strategy can parse both `project_name` and `ProjectName` keys. You should choose one form and use proper strategy, either SnakeCase or CamelCase. Alternatively, you should use `@JsonNames` annotation to specify alternative names (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#alternative-json-names)

**Comment by otuva** [comment]
Oh, I see. Thank you for your answer

Also, will be there more built-in cases? Considering there's no naming convention with JSON keys

**Comment by sandwwraith** [comment]
I suppose this can be closed?

**Comment by sschuberth** [comment]
> In addition to snake, kebab and pascal case would be more than enough.

I'm missing PascalCase as well. Would a contribution to add it get accepted, @sandwwraith?

**Comment by sandwwraith** [comment]
I think this is a reasonable addition, so why not
