### ISSUE TITLE
IllegalArgumentException with CharsetDecoderICU on Java 7 (Android 6)

### ISSUE THREAD

**Issue by grote** [Kotlin/kotlinx.serialization#2336]
**Describe the bug**

Decoding a json stream throws a `IllegalArgumentException` on Android 6 while decoding the same stream doesn't throw an exception on newer Android versions.

**To Reproduce**

Can produce something for Java7/Android 6 if needed.

**Expected behavior**

No exception is thrown.

**Environment**
 - Kotlin version: 1.8.20
 - Library version: 1.5.1
 - Kotlin platforms: Android
 - Gradle version: 7.5.1
 - Other relevant context: Happens only on Android 6 which still has Java7, newer Android versions seem unaffected.

```ruby
E UpdateService: java.lang.IllegalArgumentException: Bad position (limit 127): -16130
E UpdateService:         at java.nio.Buffer.positionImpl(Buffer.java:351)
E UpdateService:         at java.nio.Buffer.position(Buffer.java:345)
E UpdateService:         at java.nio.charset.CharsetDecoderICU.setPosition(CharsetDecoderICU.java:205)
E UpdateService:         at java.nio.charset.CharsetDecoderICU.decodeLoop(CharsetDecoderICU.java:154)
E UpdateService:         at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:306)
E UpdateService:         at kotlinx.serialization.json.internal.CharsetReader.doRead(CharsetReader.kt:61)
E UpdateService:         at kotlinx.serialization.json.internal.CharsetReader.read(CharsetReader.kt:51)
E UpdateService:         at kotlinx.serialization.json.internal.JavaStreamSerialReader.read(JvmJsonStreams.kt:261)
E UpdateService:         at kotlinx.serialization.json.internal.ReaderJsonLexer.preload(JsonLexer.kt:84)
E UpdateService:         at kotlinx.serialization.json.internal.ReaderJsonLexer.ensureHaveChars(JsonLexer.kt:131)
E UpdateService:         at kotlinx.serialization.json.internal.ReaderJsonLexer.canConsumeValue(JsonLexer.kt:58)
E UpdateService:         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeMapIndex(StreamingJsonDecoder.kt:194)
E UpdateService:         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:173)
E UpdateService:         at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:34)
E UpdateService:         at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
E UpdateService:         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
E UpdateService:         at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
E UpdateService:         at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
E UpdateService:         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
```

**Comment by licaon-kter** [comment]
Related to https://github.com/Kotlin/kotlinx.serialization/issues/2231 ?

**Comment by grote** [comment]
I'd say its a duplicate of that.
