### ISSUE TITLE
Error when you skip decoding of decoder value from deserializer method in custom KSerializer...

### ISSUE THREAD

**Issue by urosjarc** [Kotlin/kotlinx.serialization#2403]
**Describe the bug**

In the method `deserialize` if you don't use decoder value with `decoder.decodeString()` the serialization will produce parsing error.
```kotlin
    override fun deserialize(decoder: Decoder): Hash {
        return Hash(ByteArray(size = 0)) //It will never happend that client will send hash value to the server.
    }
```

```text
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 24: Expected colon ':', but had '"' instead at path: $.hashed
JSON input:  {"hashed": "asdfasdfsdf"} 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
```

If you use value from decoder like so... The error is gone!
```kotlin
    override fun deserialize(decoder: Decoder): Hash {
        decoder.decodeString()
        return Hash(ByteArray(size = 0)) //It will never happend that client will send hash value to the server.
    }
```

**To Reproduce**

```kotlin
@Serializable
data class Hash(@Contextual val value: ByteArray)

@Serializable
data class Test(@Contextual val hashed: Hash)
object HashSerializer : KSerializer<Hash> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Hash", PrimitiveKind.STRING)

    @OptIn(ExperimentalSerializationApi::class)
    override fun serialize(encoder: Encoder, value: Hash) {
        encoder.encodeNull() //Never ever you would want to send hash to the client since this are private informations and should not be compromised.
    }

    override fun deserialize(decoder: Decoder): Hash {
        return Hash(ByteArray(size = 0)) //It will never happend that client will send hash value to the server.
    }
}

fun main() {
    val json = Json {
        this.serializersModule = SerializersModule {
            contextual(HashSerializer)
        }
    }
    val test = json.decodeFromString<Test>(""" {"hashed": "asdfasdfsdf"} """)
    println(test)
}
```

**Expected behavior**

The expected behavior would be that this should not count as an error but more as a warning that the decoder value was not used in the deserialization process.

**Environment**
 - Kotlin version: [1.9]
 - Library version: [1.5.0]
 - Kotlin platforms: [JVM]

**Comment by sandwwraith** [comment]
I understand that this can be confusing, but this code behaves exactly as intended. If you do not touch decoder, it does not change its state and does not advance input or discard any data. Therefore, if you are determined to skip the value, then you should explicitly call `decodeString()`.

**Comment by urosjarc** [comment]
Thank you for the feedback! This behavior is still a little bit risky to leave as it is but you guys know what are you doing...
Thank you for the great library and I wish you all the best!
