### ISSUE TITLE
map to json string error

### ISSUE THREAD

**Issue by BlueSky15171** [Kotlin/kotlinx.serialization#2411]
**Describe the bug**
I cannot convert map<String, Any> to a JSON string.

**To Reproduce**
I need to convert mapOf<String, Any>() to a JSON string, but running crash.
env:
```kotlin
ktor client: 2.3.3
kotlinx.serialization: 1.5.1
```
code 
```kotlin
// ...
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
// ...
    @Test
    fun map2str(){
        val map = mapOf(
            "key1" to "param",
            "key2" to "param",
            "key3" to true,
            "key4" to 1,
            "key5" to 1.0f,
        )
        println("json -> ${Json.encodeToString(map)}")
    }
```
error:
```log
08-16 17:29:37.394 13022 13054 E TestRunner: Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
08-16 17:29:37.394 13022 13054 E TestRunner:
08-16 17:29:37.394 13022 13054 E TestRunner: 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:92)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at kotlinx.serialization.SerializersKt__SerializersKt.noCompiledSerializer(Serializers.kt:373)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at kotlinx.serialization.SerializersKt.noCompiledSerializer(Unknown Source:1)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at com.cmm.JsonTest.map2str(JsonTest.kt:138)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
08-16 17:29:37.394 13022 13054 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2082)
08-16 17:29:37.394 13022 13054 E TestRunner: ----- end exception -----
08-16 17:29:37.406 13022 13054 I TestRunner: finished: map2str(com.cmm.JsonTest.kt)
```

**Comment by pdvrieze** [comment]
Kotlinx.serialization can only serialize types for which it has been given a serializer (either built-in or through the serializersModule). This is by design (it is designed to work with statically determined serializers, it is also a security issue to serialize/deserialize random types).

**Comment by sandwwraith** [comment]
Duplicate of #746
