### ISSUE TITLE
Custom generic serialization is broken on JS

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#244]
GenericCustomSerializersTest.kt produces following output on Kotlin/JS:

```
not ok 168 kotlinx.serialization.features > GenericCustomSerializerTest > testStringData
  ---
  message: "Died on test #1     at QUnitAdapter.test (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlin-test.js:501:13)
    at test (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlin-test.js:424:15)
    at Object.<anonymous> (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/classes/kotlin/test/kotlinx-serialization-runtime-js_test.js:13481:7): CheckedDataSerializer_init is not defined"
  severity: failed
  stack: ReferenceError: CheckedDataSerializer_init is not defined
    at StringData$$serializer.serialize_awe97i$ (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/classes/kotlin/test/kotlinx-serialization-runtime-js_test.js:5941:51)
    at encode_0 (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlinx-serialization-runtime-js.js:718:14)
    at JSON_0.stringify_tf03ej$ (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlinx-serialization-runtime-js.js:4949:5)
    at JSON$Companion.stringify_tf03ej$ (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlinx-serialization-runtime-js.js:5018:23)
    at GenericCustomSerializerTest.testStringData (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/classes/kotlin/test/kotlinx-serialization-runtime-js_test.js:6115:30)
    at /Users/jetbrains/work/x-ser-runtime/runtime/js/build/classes/kotlin/test/kotlinx-serialization-runtime-js_test.js:13482:52
    at Object.<anonymous> (/Users/jetbrains/work/x-ser-runtime/runtime/js/build/node_modules/kotlin-test.js:515:7)
  ...
```

**Comment by sandwwraith** [comment]
Fixed in 1.3.20
