### ISSUE TITLE
Json#decodeFromStream throws "Unexpected JSON token at offset" error when used with a module

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx.serialization#2484]
**Describe the bug**

When encoding/decoding a Json via a stream with a custom module, it throws:

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 80: Expected string literal but 'null' literal was found at path: $.some
Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: {"some":{"type":"com.arkivanov.essenty.statekeeper.FooTest.Some","map2":{"5":55,null:null}}}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:223)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNextToken(AbstractJsonLexer.kt:210)
	at kotlinx.serialization.json.internal.ReaderJsonLexer.consumeKeyString(ReaderJsonLexer.kt:142)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:383)
	at kotlinx.serialization.json.internal.JsonTreeReader.readObject(JsonTreeReader.kt:124)
	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:98)
	at kotlinx.serialization.json.internal.JsonTreeReader.readObject(JsonTreeReader.kt:19)
	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:98)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:50)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:65)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:81)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
	at com.arkivanov.essenty.statekeeper.FooTest$Value$$serializer.deserialize(FooTest.kt:59)
	at com.arkivanov.essenty.statekeeper.FooTest$Value$$serializer.deserialize(FooTest.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:39)
	at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61)
	at com.arkivanov.essenty.statekeeper.FooTest.foo(FooTest.kt:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**To Reproduce**

```kotlin
class FooTest {
    @Test
    fun foo() {
        val json =
            Json {
                allowStructuredMapKeys = true

                serializersModule =
                    SerializersModule {
                        polymorphic(SomeInterface::class) {
                            subclass(Some::class)
                        }
                    }
            }

        val value =
            Value(
                some = Some(
                    map2 = mapOf(5 to 55, null to null),
                ),
            )

        val bytes =
            ByteArrayOutputStream().use { output ->
                json.encodeToStream(serializer = Value.serializer(), value = value, stream = output)
                output.toByteArray()
            }

        val newValue =
            ByteArrayInputStream(bytes).use { input ->
                json.decodeFromStream(deserializer = Value.serializer(), stream = input)
            }

        assertEquals(value, newValue)
    }

    interface SomeInterface

    @Serializable
    data class Some(
        val map2: Map<Int?, Int?>,
    ) : SomeInterface

    @Serializable
    data class Value(
        val some: SomeInterface,
    )
}
```

**Expected behavior**

The test passes.

**Environment**
 - Kotlin version: 1.9.0
 - Library version: 1.6.0
 - Kotlin platforms: JVM
 - Gradle version: 8.0.2
 - IDE version: IntelliJ IDEA 2023.2

**Comment by sandwwraith** [comment]
Apparently, we do not allow `null` key inside `JsonObject`, therefore the whole object containing nullable keys is not eligible for polymorphism:

```
@Serializable
    class NullableMap(val map: Map<Int?, Int?>)

    @Test
    fun tester()  {
        val nm = NullableMap(mapOf(5 to 55, null to null))
        val s = Json.encodeToString(nm)
        println(s)
        println(Json.decodeFromString<NullableMap>(s).map)
        println(Json.parseToJsonElement(s))
    }
```

prints

```
{"map":{"5":55,null:null}}
{5=55, null=null}

kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 15: Expected string literal but 'null' literal was found at path: $
Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: {"map":{"5":55,null:null}}
```

Given that `null` keys are generally not permitted in Json, and `JsonObject` also does not permit them, I'm not sure this qualifies as a bug.

**Comment by arkivanov** [comment]
Indeed, nulls are not allowed as keys. Perhaps it should still work with `allowStructuredMapKeys = true`? Currently it fails with the same error. Though, the following test passes.

```kotlin
   @Serializable
    class NullableMap(val map: Map<Data?, Int?>)

    @Serializable
    class Data(val a: Int)

    @Test
    fun tester()  {
        val json =
            Json {
                allowStructuredMapKeys = true
            }

        val nm = NullableMap(mapOf(Data(a = 1) to 55, null to null))
        val s = json.encodeToString(nm)
        println(s)
        println(json.decodeFromString<NullableMap>(s).map)
        println(json.parseToJsonElement(s))
    }
```

**Comment by sandwwraith** [comment]
> It should still work with allowStructuredMapKeys = true.

`allowStructuredMapKeys` works only for maps with non-primitive keys. So, the test will pass if you change the type of `Some.map2` in the original reproducer to `Map<Data?, Int?>`.
