### ISSUE TITLE
Transient lambdas capture wrong parameters

### ISSUE THREAD

**Issue by adrian-shape** [Kotlin/kotlinx.serialization#2492]
**Describe the bug**

When you have a `@Serializable` class with a `@Transient` lambda, the lambda captures the wrong parameters and causes crashes that should be impossible.

**To Reproduce**
Attach a code snippet or test data if possible.

If we have the following class, and call `StringWrapper("1.0").double`

```
data class DoubleWrapper(val value: Double)
interface DoubleWrapperBuilder {
    fun build(value: Double): DoubleWrapper = DoubleWrapper(value)
}

@Serializable
data class StringWrapper(
    val value: String,
    @Transient val pointBuilder: DoubleWrapperBuilder = object : DoubleWrapperBuilder {
        override fun build(value: Double): DoubleWrapper = DoubleWrapper(value)
    }
) {
    val double: DoubleWrapper
        get() {
            val double: Double = value.toDouble()
            Timber.d("Value as double: $doubleValue")
            return pointBuilder.build(double)
        }
}
```

Then this is the result:

```
Value as double: 1.0
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.foo.StringWrapper.getValue()' on a null object reference
  at com.example.foo.StringWrapper$2.build(Foo.kt:36)
  at com.example.foo.StringWrapper.getDouble(Foo.kt:46)
```

If we change the code to the following:

```
val double: DoubleWrapper
        get() {
            val doubleValue: Double = value.toDouble()
            Timber.d("Value as double: $doubleValue")
            return pointBuilder.build(doubleValue)
        }
```

If I remove the annotations, the code behaves as expected.

If I change the argument names inside DoubleWrapperBuilder to not clash, then the code behaves as expected.

I have also in some other iteration of this bug with different usage gotten a ClassCastException from String to Number while having Java code involved.

**Expected behavior**

Calling the .double function as specified should not crash.

**Environment**
 - Kotlin version: 1.9.10
 - Library version: 1.6.0
 - Kotlin platforms: JVM / Android
 - Gradle version: 8.3

**Comment by pdvrieze** [comment]
This bug seems to do with name resolution by the compiler. The implementation of the build function in the anonymous object somehow resolves value to the string property, rather than to the double parameter.
Some questions:
- Is this problem the same if you just create the object without using serialization (but it being serializable).
- What happens if you use a private member class instead of an anonymous object?
- What happens if you use a private member object?
- What happens if you don't make the class a data class
- What happens if you move the `doubleWrapperBuilder` to the companion object

**Comment by adrian-shape** [comment]
> Is this problem the same if you just create the object without using serialization (but it being serializable)

I just created the object manually with `StringWrapper("1.0").double`, not using serialization, but it still crashes.
If I remove both annotations, the issue no longer appears.

> What happens if you don't make the class a data class

With both data classes being converted to regular classes, same crash appears.

> What happens if you move the doubleWrapperBuilder to the companion object

In both scenarios if I move the entire doubleWrapperBuilder value to the companion object everything works fine.
If I move the lambda to the companion object and assign it in the constructor, it works fine too.

I guess could have something to do with creating the lambda in the constructor with `@Transient`

**Comment by vsartiushkin** [comment]
Hi! The issue is fixed on the compiler side since Kotlin 2.4.0.

I reproduced issue for Kotlin versions up to 2.3.21 and library versions 1.6.0 to 1.11.0 for both JVM and ART with the minimized test:
```kotlin
class ParameterShadowingTest {

    data class Box(val value: Int)

    interface Builder {
        fun build(value: Int): Box
    }

    @Serializable
    data class Holder(
        val value: Int, // reproduces only when parameter names collide
        val builder: Builder = object : Builder {
            override fun build(value: Int): Box = Box(value)
        }
    ) {
        val boxed: Box
            get() = builder.build(value)
    }

    @Test
    fun testParameterShadowing() {
            Holder(1).boxed // throws on JVM/Android, fixed since Kotlin 2.4.0
    }
}
```
The issue seems to be caused by parameter names collision. `@Transient` is not required to reproduce the issue.

Additional note - the exceptions produced on Android and the JVM differ:
```
java.lang.NoSuchMethodError: ParameterShadowingTest$Holder$1: method 'void <init>()' not found
```
for JVM
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.example.gh2492repro.Holder.getValue()' on a null object referenc
```
for Android

**Comment by vsartiushkin** [comment]
Fixed by https://github.com/JetBrains/kotlin/pull/5714 and covered by the added test.
