### ISSUE TITLE
NullPointerException when trying to use JsonTransformingSerializer directly on serializable class

### ISSUE THREAD

**Issue by linean** [Kotlin/kotlinx.serialization#2497]
**Describe the bug**
Playing with `JsonTransformingSerializer` I have noticed that applying it directly to the serializable class produces `NullPointerException`. I'm not sure if this usage is correct, but if not I think it could be detected during compilation. Produced exception is not so easy to understand.

**To Reproduce**
Compile and run the following snippet:
```
@Serializable(with = ExampleSerializer::class)
data class Example(val value: String)

object ExampleSerializer : JsonTransformingSerializer<Example>(Example.serializer()) {
    override fun transformDeserialize(element: JsonElement): JsonElement {
        val value = element.jsonPrimitive
        return JsonObject(mapOf("value" to value))
    }
}

fun main() {
    val json = "example"
    val example: Example = Json.decodeFromString(json)
    println(example)
}
```

As result you'll see
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Example$Companion.serializer(Main.kt:4)
	at MainKt.main(Main.kt:21)
	at MainKt.main(Main.kt)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.json.JsonTransformingSerializer.<init>, parameter tSerializer
	at kotlinx.serialization.json.JsonTransformingSerializer.<init>(JsonTransformingSerializer.kt)
	at ExampleSerializer.<init>(Main.kt:7)
	at ExampleSerializer.<clinit>(Main.kt)
	... 3 more
```

To confirm that it works when used for other class parameter you can run:
```
@Serializable
data class Example(val value: String)

@Serializable
data class WorkingExample(
    @Serializable(with = ExampleSerializer::class)
    val example: Example
)

object ExampleSerializer : JsonTransformingSerializer<Example>(Example.serializer()) {
    override fun transformDeserialize(element: JsonElement): JsonElement {
        val value = element.jsonPrimitive
        return JsonObject(mapOf("value" to value))
    }
}

fun main() {
    val json = """{"example": "example"}"""
    val example: WorkingExample = Json.decodeFromString(json)
    println(example)
}

```

**Expected behavior**
It should either work or compilation should fail with more descriptive error.

**Environment**
 - Kotlin version: 1.9.20
 - Library version: 1.9.2
 - Kotlin platforms: JVM
 - Gradle version: 8.2

**Comment by pdvrieze** [comment]
Maybe a better suggestion is to fail on any abstract class being specified directly as serializer (`JsonTransformingSerializer` is abstract).

**Comment by linean** [comment]
@pdvrieze In my example, I don't directly use an abstract serializer. Instead, I reference a specific implementation, namely the `ExampleSerializer`. When I refer to doing it `directly` in my description, I mean applying it as follows:
```
@Serializable(with = ExampleSerializer::class)
data class Example(val value: String)
```
as opposed to
```
@Serializable(with = ExampleSerializer::class)
val example: Example
```

**Comment by pdvrieze** [comment]
Ah, I see the problem. `Example.serializer()` will resolve to `ExampleSerializer`. But by referencing it in the constructor it creates an initialization loop (hence the NPE).
Not only is there an initialization loop, it can not work either (the nested serializer is used to deserialize the transformed json).
One workaround would be to have an annotation generated serializer for `Example` that you pass instead (using the `@Serializer` annotation on a class/object.

**Comment by sandwwraith** [comment]
It is a known problem: #1169. Unfortunately, you can't use JsonTransformingSerializer as a default one, or you'll get an initialization loop. You can specify it on a property or file.

**Comment by linean** [comment]
I think this initialization loop could be detected by compiler plugin. It would save SDK users from runtime exceptions 🙏

**Comment by linean** [comment]
Maybe we don't need to detect a loop? 🤔 I think (but I may be wrong) that NullPointerException exposes some incorrectly generated code. I don't now exact implementation details, but I think it should not be resolved at runtime.

If it needs to be resolved at runtime, we could generate some better error message instead of failing in `Intrinsics.checkNotNullParameter`.

**Comment by sandwwraith** [comment]
>  NullPointerException exposes some incorrectly generated code

It's not always the case. There are many ways to get an NPE from initialization order, in both Java and Kotlin. 
For example, without serialization:

```
sealed class S {
    companion object {
        val obj = Obj
    }
}

object Obj : S()

fun main() {
    Obj
    println(S.obj) // prints null
}
```

(more examples in https://youtrack.jetbrains.com/issue/KT-8970/Object-is-uninitialized-null-when-accessed-from-static-context-ex.-companion-object-with-initialization-loop)

So, until this problem is directly resolved in the compiler (which, as I said, can be done only for a limited number of cases and can't be solved generally), there's nothing to be done from kotlinx.serialization side. I agree with you though that exception message can be more descriptive
