### ISSUE TITLE
ProGuard rule for R8 full mode and Serializable enums

### ISSUE THREAD

**Issue by leinardi** [Kotlin/kotlinx.serialization#2501]
**Describe the bug**
With the following `enum`

```kotlin
@Keep
@Serializable(with = LabelSerializer::class)
enum class Label {
    @SerialName("location")
    LOCATION,

    @SerialName("name")
    NAME,

    @SerialName("number")
    NUMBER,

    @SerialName("topic")
    TOPIC,

    @SerialName("unknown")
    UNKNOWN
}

private val Label.serialName: String
    get() = checkNotNull(this::class.java.getField(this.name).getAnnotation(SerialName::class.java)).value

private object LabelSerializer : KSerializer<Label> {
    private val className = checkNotNull(this::class.qualifiedName)
    private val lookup = Label.entries.associateBy({ it }, { it.serialName })
    private val revLookup = Label.entries.associateBy { it.serialName }
    override val descriptor = PrimitiveSerialDescriptor(className, PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Label) {
        encoder.encodeString(lookup.getValue(value))
    }

    override fun deserialize(decoder: Decoder) = revLookup.getOrDefault(decoder.decodeString(), Label.UNKNOWN)
}
```

And the following ProGuard rules
```
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.SerializationKt
-keep,includedescriptorclasses class com.my.company.**$$serializer { *; }
-keepclassmembers class com.my.company.** {
    *** Companion;
}
-keepclasseswithmembers class com.my.company.** {
    kotlinx.serialization.KSerializer serializer(...);
}
```

It still crashes at runtime with the following exception, when build with R8 full mode and minimized:

```
Fatal Exception: java.lang.ExceptionInInitializerError:
       at com.my.company.library.network.api.model.linkbot.Ask$Response$$serializer.deserialize(Ask.kt:11)
       at com.my.company.network.api.model.linkbot.Ask$Response$$serializer.deserialize(Ask.kt:11)
       at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
       at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.java:26)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.lang.NoSuchFieldException: COLLABORATION
       at java.lang.Class.getField(Class.java:2337)
       at com.my.company.library.network.api.model.linkbot.IntentKt.getSerialName(Intent.kt:45)
       at com.my.company.library.network.api.model.linkbot.IntentKt.access$getSerialName(Intent.kt:1)
       at com.my.company.library.network.api.model.linkbot.IntentSerializer.<clinit>(Intent.kt:49)
       at com.my.company.library.network.api.model.linkbot.Ask$Response$$serializer.deserialize(Ask.kt:11)
       at com.my.company.library.network.api.model.linkbot.Ask$Response$$serializer.deserialize(Ask.kt:11)
       at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
       at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.java:26)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
       at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Crashlytics Exception Handler1:
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1841)
       at java.lang.Thread.getAllStackTraces(Thread.java:1909)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadsList(CrashlyticsReportDataCapture.java:334)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateExecutionData(CrashlyticsReportDataCapture.java:305)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateEventApplicationData(CrashlyticsReportDataCapture.java:253)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData(CrashlyticsReportDataCapture.java:106)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent(SessionReportingCoordinator.java:303)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistFatalEvent(SessionReportingCoordinator.java:132)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:214)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:199)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
       at com.google.android.gms.tasks.zze.run(zze.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:1012)
```

**Expected behavior**
`proguard-consumer-rules.pro` of the library should take care of `enum`s or instructions should be provided on how to deal with serializable enums

**Environment**
 - Kotlin version: 1.9.10
 - Library version: `"org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"`
 - Kotlin platforms: JVM
 - Gradle version: 8.4
 - Other relevant context: As a workaround I can use the `androidx.annotation.Keep` annotation on the `enum`, but I would prefer to use a generic ProGuard rule

**Comment by pdvrieze** [comment]
Beyond suggesting you use the EnumSerializer as a basis there are some issues with the code (you don't appear to do something special and most formats already serialize enums as strings). The error states that the field "COLLABORATION" is not accessible. Even assuming this is an error in transforming the code to be suitable for the report, this is not how enums work, and if you want to read an annotation from the enum you will need to get it from the class, not a field in the class.

**Comment by leinardi** [comment]
I would love to be able to use a default enum serialized and avoid having to use a custom one, but I'm unable to find documentation about this `EnumSerializer`, do you have a link to some documentation or an example on how to use it?

**Comment by leinardi** [comment]
I think I had some Gradle cache issue because I tried again with just this and it works:

```kotlin
@Serializable
enum class Label {
    @SerialName("location")
    LOCATION,

    @SerialName("name")
    NAME,

    @SerialName("number")
    NUMBER,

    @SerialName("topic")
    TOPIC,

    @SerialName("unknown")
    UNKNOWN
}
```
