### ISSUE TITLE
JsonClassDiscriminator causes Unexpected JSON token

### ISSUE THREAD

**Issue by svok** [Kotlin/kotlinx.serialization#2526]
**Describe the bug**
When I use `@JsonClassDiscriminator` annotation to customize discriminator field name and trying to deserialize a JSON string, I get the exception: 
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'requestType' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"requestType":"create","requestId":"123"}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:593)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:257)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:243)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:178)
	at ru.otus.otuskotlin.marketplace.api.v2.models.AdCreateRequest$$serializer.deserialize(AdCreateRequest.kt:34)
	at ru.otus.otuskotlin.marketplace.api.v2.models.AdCreateRequest$$serializer.deserialize(AdCreateRequest.kt:34)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at ru.otus.otuskotlin.marketplace.api.v2.RequestV2SerializationTest.deserialize(RequestV2SerializationTest.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
```

**To Reproduce**
`IRequest`:
```kotlin
@Serializable
@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator("requestType")
sealed class IRequest {
    @SerialName(value = "requestId") abstract val requestId: kotlin.String?
}
```

`AdCreateRequest`:
```kotlin
@Serializable
@SerialName(value = "create")
data class AdCreateRequest (
    @SerialName(value = "requestId") override val requestId: kotlin.String? = null,
) : IRequest()
```

In the unit test:
```kotlin
        val json = Json.encodeToString(request)
        val obj = Json.decodeFromString(json) as AdCreateRequest
```
line 1 issues correct json while line 2 causes the above exception.

As advised in the exception
```kotlin
Json {
    ignoreUnknownKeys = true
}
```
such option eliminates the exception.

**Expected behavior**
Both serialization and deserialization must work properly with the custom discriminator fields without the need of `ignoreUnknownKeys` option.

**Environment**
 - Kotlin version: 1.9.21
 - Library version: 1.4 - 1.6.*
 - Kotlin platforms: multiplatform, any platforms
 - Gradle version: 7.*, 8.*
 - IDE version: any
 - Other relevant context: any OS (Ubuntu 20.04)

**Comment by sandwwraith** [comment]
This happens because you have `as AdCreateRequest` in decodeFromString. Doing so implies that the type parameter for it is also AdCreateRequest, i.e. equivalent to `Json.decodeFromString<AdCreateRequest>(json)`. Because of the [static typing](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#static-types), the deserializer for AdCreateRequest does not take the polymorphic key into account, as it doesn't need it. So, you either want to have `Json.decodeFromString<IRequest>(json)` to deserialize data polymorphically or keep `ignoreUnknownKeys = true`.

**Comment by svok** [comment]
@sandwwraith I cannot confirm your solution.
```kotlin
@Test
    fun deserialize() {
        val json = Json.encodeToString(response)
        val obj = Json.decodeFromString<IRequest>(json) as AdCreateResponse

        assertEquals(response, obj)
    }
```
issues the same error.

**Comment by sandwwraith** [comment]
@svok This test passes for me:

```kotlin
@Serializable
    @OptIn(ExperimentalSerializationApi::class)
    @JsonClassDiscriminator("requestType")
    sealed class IRequest {
        @SerialName(value = "requestId") abstract val requestId: kotlin.String?
    }

    @Serializable
    @SerialName(value = "create")
    data class AdCreateRequest (
        @SerialName(value = "requestId") override val requestId: kotlin.String? = null,
    ) : IRequest()

    @Test
    fun basic() {
        val response: IRequest = AdCreateRequest("foobar")
        val json = Json.encodeToString(response)
        val obj = Json.decodeFromString<IRequest>(json) as AdCreateRequest

        assertEquals(response, obj)
    }
```

**Comment by svok** [comment]
@sandwwraith Yes, that was my fault. I found my error. Sorry for disturb.
