### ISSUE TITLE
Getting `java.lang.ExceptionInInitializerError` After Using Custom Serializer

### ISSUE THREAD

**Issue by Mukuljangir372** [Kotlin/kotlinx.serialization#2541]
**Describe the bug**
Getting `java.lang.ExceptionInInitializerError` After Using Custom Serializer (KSerializer).

**To Reproduce**
Attaching Code Samples to regenerate the issue.

**Error Log**
```kotlin
java.lang.ExceptionInInitializerError
                                      	at com.scogo.app.core.data.network.conversation.ConversationMessagePayloadNetworkModel$$serializer.deserialize(ConversationMessagePayloadNetworkModel.kt:6)
                                      	at com.scogo.app.core.data.network.conversation.ConversationMessagePayloadNetworkModel$$serializer.deserialize(ConversationMessagePayloadNetworkModel.kt:6)
                                      	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
                                      	at com.scogo.app.core.data.network.conversation.ConversationMessageNetworkModel$$serializer.deserialize(ConversationMessageNetworkModel.kt:8)
                                      	at com.scogo.app.core.data.network.conversation.ConversationMessageNetworkModel$$serializer.deserialize(ConversationMessageNetworkModel.kt:8)
                                      	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                                      	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
                                      	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
                                      	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                                      	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                                      	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                                      	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
                                      	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                      	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
                                      	at com.scogo.app.data.chat.network.api.MessageApi$GetMessagesResponse$$serializer.deserialize(MessageApi.kt:8)
                                      	at com.scogo.app.data.chat.network.api.MessageApi$GetMessagesResponse$$serializer.deserialize(MessageApi.kt:8)
                                      	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                                      	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
                                      	at com.scogo.app.data.chat.network.MessageNetworkDataSourceImpl$getMessages$2.invokeSuspend(MessageNetworkDataSourceImpl.kt:46)
                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                      	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                      	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5c8086e, Dispatchers.Default]
                                      Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.internal.ArrayListClassDesc.<init>, parameter elementDesc
                                      	at kotlinx.serialization.internal.ArrayListClassDesc.<init>(Unknown Source:2)
                                      	at kotlinx.serialization.internal.ArrayListSerializer.<init>(CollectionSerializers.kt:214)
                                      	at com.scogo.app.core.data.network.conversation.ConversationMessagePayloadNetworkModel.<clinit>(ConversationMessagePayloadNetworkModel.kt:6)
```

```kotlin
@Serializable
data class ConversationMessageNetworkModel(
    @SerialName("payload")
    val payload: ConversationMessagePayloadNetworkModel? = null
)

@Serializable
data class ConversationMessagePayloadNetworkModel(
    @SerialName("title")
    val title: String? = "",

    @SerialName("content")
    val content: List<ConversationMessagePayloadContentNetworkModel>? = null
)

@Serializable(PayloadContentSerializer::class)
data class ConversationMessagePayloadContentNetworkModel(
    @SerialName("key")
    val key: String = "",

    @SerialName("value")
    val value: List<ConversationMessagePayloadValueNetworkModel> = emptyList(),

    @SerialName("highlight")
    val highlight: Boolean,

    @SerialName("elementType")
    val elementType: String,
)

@Serializable
data class ConversationMessagePayloadValueNetworkModel(
    @SerialName("key")
    val key: String = "",

    @SerialName("value")
    val value: String = ""
)

object PayloadContentSerializer : KSerializer<ConversationMessagePayloadContentNetworkModel> {
    override val descriptor: SerialDescriptor =
        ConversationMessagePayloadContentNetworkModel.serializer().descriptor
    private val valueListSerializer =
        ListSerializer(ConversationMessagePayloadValueNetworkModel.serializer())

    override fun serialize(encoder: Encoder, value: ConversationMessagePayloadContentNetworkModel) {
        encoder.encodeStructure(descriptor) {
            encodeStringElement(descriptor, 0, value.key)
            encodeSerializableElement(descriptor, 1, valueListSerializer, value.value)
            encodeBooleanElement(descriptor, 2, value.highlight ?: false)
            encodeStringElement(descriptor, 3, value.elementType ?: "")
        }
    }

    override fun deserialize(decoder: Decoder): ConversationMessagePayloadContentNetworkModel {
        return decoder.decodeStructure(descriptor) {
            var key = ""
            var value: List<ConversationMessagePayloadValueNetworkModel> = emptyList()
            var highlight: Boolean? = null
            var elementType: String? = null
            while (true) {
                when (val index = decodeElementIndex(descriptor)) {
                    0 -> key = decodeStringElement(descriptor, 0)
                    1 -> value = decodeSerializableElement(descriptor, 1, valueListSerializer)
                    2 -> highlight = decodeBooleanElement(descriptor, 2)
                    3 -> elementType = decodeStringElement(descriptor, 3)
                    CompositeDecoder.DECODE_DONE -> break
                    else -> throw SerializationException("Unknown index: $index")
                }
            }
            ConversationMessagePayloadContentNetworkModel(key, value, highlight ?: false, elementType ?: "")
        }
    }
}

// Encoding & Decoding
val json = Json { unknownKeys = true }
json.decode(...)
```

**Environment**
 - Kotlin version: 1.9.10
 - Library version: 1.6.0
 - Kotlin platforms: Native (Android & iOS)
 - Gradle version: 8.1.2
 - IDE version: Android Studio Hedgehog | 2023.1.1 Patch 1

**Comment by sandwwraith** [comment]
Take a look at your `PayloadContentSerializer`: 
It says that ` val descriptor: SerialDescriptor = ConversationMessagePayloadContentNetworkModel.serializer().descriptor`.
However, because you have `@Serializable(PayloadContentSerializer::class)` on a  `ConversationMessagePayloadContentNetworkModel`, it means that `ConversationMessagePayloadContentNetworkModel.serializer()` returns very same `PayloadContentSerializer` you're trying to create, causing an initialization loop. So you need to provide a descriptor on your own (same for `valueListSerializer`).

Side note: it looks like `PayloadContentSerializer` is similar to a generated one. Are you sure you need a custom serializer?

**Comment by pdvrieze** [comment]
Also, you shouldn't initialize `valueListSerializer` by referencing the serializer function, but rather by `ListSerializer(this)` (avoiding another initialization loop).
