### ISSUE TITLE
NoSuchMethodError Kotlin 1.3 / lib 0.9

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/kotlinx.serialization#260]
Kotlin 1.3 compiler and the 0.9 release generate invalid code.

```
java.lang.NoSuchMethodError: kotlinx.serialization.CompositeEncoder.encodeNullableElement(Lkotlinx/serialization/SerialDescriptor;ILjava/lang/Object;)V
        at co.haynet.database.Image.write$Self(Common.kt)
        at co.haynet.database.Image$$serializer.serialize(Common.kt)
        at co.haynet.database.Image$$serializer.serialize(Common.kt:90)
        at kotlinx.serialization.Encoder$DefaultImpls.encodeSerializableValue(Coders.kt:42)
        at kotlinx.serialization.ElementValueEncoder.encodeSerializableValue(ElementWise.kt:25)
        at kotlinx.serialization.Encoder$DefaultImpls.encodeNullableSerializableValue(Coders.kt:50)
        at kotlinx.serialization.ElementValueEncoder.encodeNullableSerializableValue(ElementWise.kt:25)
        at kotlinx.serialization.ElementValueEncoder.encodeNullableSerializableElement(ElementWise.kt:88)
        at co.haynet.database.User.write$Self(Users.kt)
        at co.haynet.database.User$$serializer.serialize(Users.kt)
        at co.haynet.database.User$$serializer.serialize(Users.kt:55)
        at kotlinx.serialization.CoreKt.encode(Core.kt:71)
        at kotlinx.serialization.cbor.CBOR.dump(CBOR.kt:390)
        at kotlinx.serialization.cbor.CBOR$Companion.dump(CBOR.kt:381)
        at co.haynet.memcache.MemcacheServiceImpl$put$2.invokeSuspend(MemcacheServiceImpl.kt:24)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.google.appengine.tools.development.BackgroundThreadFactory$1$1.run(BackgroundThreadFactory.java:60)
```

```
@Suppress("ArrayInDataClass")
@Serializable
data class Image(
        val id: UUID,
        /**
         * File name to show to user (mainly for Accessibility)
         */
        val name: String,
        /**
         * The storage bucket
         */
        val bucket: String,
        /**
         * This is the file name used to modify the object in storage.
         */
        val fileName: String,
        /**
         * Image uploaded by
         */
        @Serializable(UUIDSerializer::class)
        val userId: UUID,
        /**
         * Extra data for the file (e.g. Photo data)
         */
        val metadata: ByteArray?
)
```

**Comment by chrisjenx** [comment]
Yeah, looks like the 1.3 compiler and runtime are out of sync...

**Comment by sandwwraith** [comment]
@chrisjenx Your bug is connected to fact that `ByteArray` actually is not serializable yet. There's a check in the compiler plugin for it, but primitive arrays are bypassing it.

**Comment by sandwwraith** [comment]
@KirkBushman compiled library of `0.9.0` version on JS has `SerialClassDescImpl.prototype.addElement_ivxn3r$ = function (name, isOptional)` definition. Are you sure you doesn't have any outdated version in classpath?

**Comment by chrisjenx** [comment]
@sandwwraith oh that's weird, as this was working pre 1.3. I guess the compiler should fail in this case?

**Comment by chrisjenx** [comment]
Ah ok, thanks.

**Comment by KirkBushman** [comment]
kotlin = 1.3.0
serialization = 0.9.0

I'm basically copying the js sample

here: 

    apply plugin: 'kotlin2js'
    apply plugin: 'kotlin-dce-js'
    apply plugin: 'kotlinx-serialization'

    buildscript {
         ext.kotlin_version = '1.3.0'
         ext.serialization_version = '0.9.0'
         ext.output_folder = 'node'

         repositories {
              jcenter()
             maven { url "https://kotlin.bintray.com/kotlin-dev" }
         }

         dependencies {
             classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
             classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
         }
      }

      repositories {
          jcenter()
          maven { url "https://kotlin.bintray.com/kotlinx" }
          maven { url "https://kotlin.bintray.com/kotlin-dev" }
      }

      dependencies {
          implementation "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
          implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serialization_version"
      }

     compileKotlin2Js.kotlinOptions {
         moduleKind = "commonjs"
         outputFile = "${projectDir}/$output_folder/index.js"
         sourceMap = true
      }

    clean {
         delete new File("${projectDir}/$output_folder")
    }

    build.doLast {
          configurations.compile.each { File file ->
             copy {
                includeEmptyDirs = false

                from zipTree(file.absolutePath)
                into "${projectDir}/$output_folder"
                include { fileTreeElement ->
                      def path = fileTreeElement.path
                      path.endsWith(".js") && (path.startsWith("META-INF/resources/") || !path.startsWith("META-INF/"))
               }
            }
       }

       copy {
            from sourceSets.main.resources.srcDirs
            into "${projectDir}/$output_folder"
        }
     }

**Comment by sandwwraith** [comment]
#106

**Comment by KirkBushman** [comment]
With "umd" I get the same thing --> this.descriptor.addElement_ivxn3r$ is not a function 
With "amd" I'm getting define is not a function, cause I'm running on top of nodejs, and "commonjs" is recommended.

**Comment by sandwwraith** [comment]
How do you run it from node?

**Comment by KirkBushman** [comment]
I have a folder /node/index.js which is the output file from gradle, and "npm start" is binded to  

    "scripts": {
        "start": "PORT=3001 node node/index.js",
        "test": "echo \"Error: no test specified\" && exit 1"
     },

I've got 3 small web apps running this way, for internal use only, and for all of them updating 1.3.0/0.9.0 gives this error. No problem with 1.2.71/0.6.2.

**Comment by ogbash** [comment]
"npm install --save kotlinx-serialization-runtime-js" installs "^0.5.0" version. Replacing with js file from 0.9.1 jar fixed the problem for me (for 1.3.0). I'm missing some repo or correct way to install it, maybe you too.

**Comment by KirkBushman** [comment]
kotlin 1.3.20 / lib 0.10.0

works for me, looks like the latest version fixed this.

**Comment by sandwwraith** [comment]
So can this be closed?
