### ISSUE TITLE
How to deserialize List<Any> using Ktor.serialization

### ISSUE THREAD

**Issue by BlueSky15171** [Kotlin/kotlinx.serialization#2650]
How to use the sealed class or other method sequence number and antisequence of this json
```json
[
  {
    "key": "mac",
    "value": "3C:D1:6E:38:A2:43"
  },
  {
    "key": "status",
    "value": 0
  },
  {
    "key": "value",
    "value": 0.5
  },
  {
    "key": "json",
    "value": "{\"name\":\"sky\",\"age\":20,\"sex\":1}"
  }
]
```
```kotlin
data class KVValue(val key:String,val value:Any)

@Serializable
@JsonClassDiscriminator("key")
sealed class KVValue {
    // abstract val key: String
    @Serializable
    @SerialName("json")
    data class ValueString(
        // @SerialName("type") override val key: String,
        @SerialName("value") val value: String
    ) : KVValue()
    @Serializable
    @SerialName("value")
    data class ValueFloat(
        // @SerialName("type") override val key: String,
        @SerialName("value") val value: Float
    ) : KVValue()
// ...
}
```

**Comment by mobinyardim** [comment]
You can use [Polymorphism](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md) serialization to achieve this. By the way, there is a limitation that the class type must be specified with a field named "type", so you must change the "key" field in your JSON.

```
[
  {
    "type": "mac",
    "value": "3C:D1:6E:38:A2:43"
  },
  {
    "type": "status",
    "value": 0
  },
  {
    "type": "value",
    "value": 0.5
  },
  {
    "type": "json",
    "value": {"name":"sky","age":20,"sex":1}"
  }
]
```
the code:
```kotlin

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

val jsonValue = """[
  {
    "type": "mac",
    "value": "3C:D1:6E:38:A2:43"
  },
  {
    "type": "status",
    "value": 0
  },
  {
    "type": "value",
    "value": 0.5
  },
  {
    "type": "json",
    "value": {"name":"sky","age":20,"sex":1}
  }
]"""

@Serializable
data class Person(val name: String, val age: Int, val sex: Int)

@Serializable
sealed class KVValue {

    abstract val key: String

    @Serializable
    @SerialName("mac")
    data class Mac(val value: String) : KVValue() {
        override val key: String
            get() = "mac"
    }

    @Serializable
    @SerialName("status")
    data class Status(val value: Int) : KVValue() {
        override val key: String
            get() = "status"
    }

    @Serializable
    @SerialName("value")
    data class Value(val value: Double) : KVValue() {
        override val key: String
            get() = "value"
    }

    @Serializable
    @SerialName("json")
    class Json(val value: Person) : KVValue() {
        override val key: String
            get() = "json"
    }
}


val module = SerializersModule {
    polymorphic(KVValue::class) {
        subclass(KVValue.Mac::class)
        subclass(KVValue.Status::class)
        subclass(KVValue.Value::class)
        subclass(KVValue.Json::class)
    }
}

private val converter = Json {
    serializersModule = module
    ignoreUnknownKeys = true
    encodeDefaults = true
}

fun main(): Unit {
    println(
        converter.decodeFromString<List<KVValue>>(jsonValue)
    )
}
```
Another limitation is that if you want the value to be an object, it must be in JSON object format, not a string.

**Comment by sandwwraith** [comment]
Take a look at the `JsonElement` documentation: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-elements

Or model a sealed class hierarchy after your domain (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes), as @mobinyardim suggested.

**Comment by BlueSky15171** [comment]
@mobinyardim 
How do I deserialize int to enum, for example：
```kotlin
@Serializable
    @SerialName("status")
    data class Status(val value: StatusEnum) : KVValue() {
        override val key: String
            get() = "status"
    }
@Serializable(with = StatusSerializer::class)
enum class StatusEnum(val value: Int) {
    @SerialName("0")
    OFFLINE(0),
    @SerialName("1")
    ONLINE(1),
}
object StatusSerializer:KSerializer<StatusEnum>{
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("StatusEnum", PrimitiveKind.INT)
    override fun deserialize(decoder: Decoder): StatusEnum = when(decoder.decodeInt()){
        0 -> StatusEnum.OFFLINE
        1 -> StatusEnum.ONLINE
        else -> throw IllegalArgumentException("Unknown value")
    }
    override fun serialize(encoder: Encoder, value: StatusEnum) = encoder.encodeInt(value.value)
}
```
This writing is wrong：
```

kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
at kotlinx.serialization.ContextualSerializer.serializer(ContextualSerializer.kt:51)
at kotlinx.serialization.ContextualSerializer.deserialize(ContextualSerializer.kt:67)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
at com.orgaiot.libs.iot.data.KVValue$$serializer.deserialize(KVValue.kt:20)
at com.orgaiot.libs.iot.data.KVValue$$serializer.deserialize(KVValue.kt:20)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
at com.orgaiot.libs.iot.SerializationDynamicProperties.deserializeAny(SerializationDynamicProperties.kt:122)
```
thks.
