### ISSUE TITLE
Deserialization Error when Decoding Multiple Objects with one `Decoder`

### ISSUE THREAD

**Issue by barnard-b** [Kotlin/kotlinx.serialization#2708]
**Describe the bug**
When attempting to decode two separate objects from the same decoder in a custom KSerializer, the second deserialize call throws an error.
```
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
    JSON input: {
              "text": "Hello World",
              "number": 123
            }
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:580)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:578)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:231)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:226)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:223)
    at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:79)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
    at com.example.kotlinserializationdebug.Test2$$serializer.deserialize(A.kt:14)
    at com.example.kotlinserializationdebug.Test2$$serializer.deserialize(A.kt:14)
    at com.example.kotlinserializationdebug.CompositeObjectSerializer.deserialize(A.kt:34)
    at com.example.kotlinserializationdebug.CompositeObjectSerializer.deserialize(A.kt:23)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
```

**To Reproduce**
```kotlin
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable
data class Test(val text: String)

@Serializable
data class Test2(val number: Int)

@Serializable(with = CompositeObjectSerializer::class)
data class CompositeObject(
    val test1: Test?,
    val test2: Test2?
)

object CompositeObjectSerializer : KSerializer<CompositeObject> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("com.example.kotlinserializationdebug.CompositeObject") {
        element("not used", String.serializer().descriptor)
    }

    override fun serialize(encoder: Encoder, value: CompositeObject) {
        TODO("Not implemented")
    }

    override fun deserialize(decoder: Decoder): CompositeObject {
        val test = Test.serializer().deserialize(decoder)
        // val test: Test? = null
        val test2 = Test2.serializer().deserialize(decoder) // < Throws error here unless the first deserialize call is skipped.
        return CompositeObject(test, test2)
    }
}
```

```kotlin
val json = """{
  "text": "Hello World",
  "number": 123
}"""

val jsonDecoder = Json {
    ignoreUnknownKeys = true
}

val composite: CompositeObject = jsonDecoder.decodeFromString(json)
println(composite.test1?.text)
println(composite.test2?.number.toString())
```

**Expected behavior**

Both objects can be decoded since all required keys are present in the JSON.

**Environment**
 - Kotlin version: 2.0.0 (also 1.9.22)
 - Library version: 1.7.0 (also 1.6.0)
 - Kotlin platforms: JVM
 - Gradle version: 8.6

**Comment by pdvrieze** [comment]
>```kotlin
>     override fun deserialize(decoder: Decoder): CompositeObject {
>         val test = Test.serializer().deserialize(decoder)
>         // val test: Test? = null
>         val test2 = Test2.serializer().deserialize(decoder) // < Throws error here unless the first deserialize call is skipped.
>         return CompositeObject(test, test2)
>     }
>```

This is not correct. There are specific rules that custom serializers must follow (including having a valid serialDescriptor). Have a look at the specifics: in the [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#hand-written-composite-serializer).

**Comment by barnard-b** [comment]
I was not sure what a descriptor would look like for an object like that, but it seems like my issue was trying to use a single use decoder multiple times?
```kotlin
@Serializable(with = TestSerializer::class)
data class Test(val text: String)

object TestSerializer : KSerializer<Test> {
    override val descriptor: SerialDescriptor
        get() = buildClassSerialDescriptor("Test") {
            element("text", String.serializer().descriptor)
        }

    override fun serialize(encoder: Encoder, value: Test) {
        TODO()
    }
    
    override fun deserialize(decoder: Decoder): Test {
        val jsonDecoder = decoder as JsonDecoder
        jsonDecoder.decodeJsonElement()
        jsonDecoder.decodeJsonElement() // kotlinx.serialization.json.internal.JsonDecodingException: Cannot read Json element because of unexpected end of the input
        return Test("")
    }
}
```

Probably not best practice, but I ended up with something like this to decode both objects from the same JSON.
```kotlin
object CompositeObjectSerializer : KSerializer<CompositeObject> {
    private val jsonCoder = Json {
        ignoreUnknownKeys = true
    }

    override val descriptor: SerialDescriptor =
        buildClassSerialDescriptor("com.example.kotlinserializationdebug.CompositeObject") {}

    override fun serialize(encoder: Encoder, value: CompositeObject) {
       throw UnsupportedOperationException("CompositeObject cannot be serialized")
    }

    override fun deserialize(decoder: Decoder): CompositeObject {
        val jsonDecoder = decoder as? JsonDecoder ?: throw Error("CompositeObject can only be decoded from JSON")
        val element = jsonDecoder.decodeJsonElement()
        val test = jsonCoder.decodeFromJsonElement(Test.serializer(), element)
        val test2 = jsonCoder.decodeFromJsonElement(Test2.serializer(), element)
        return CompositeObject(test, test2)
    }
}
```

**Comment by sandwwraith** [comment]
The idea behind `.deserialize(decoder)` is that it deserializes the whole object within `{}`. So, your `Test.serializer().deserialize(decoder)` consumes *all* input, deserializes `text` and discards `number`. Therefore, there no input left for `Test2.serializer()` to decode. The same applies to `decodeJsonElement()`: it also consumes the whole object, giving you JsonObject with two keys — so you need to call it only once. Your last snippet is correct though — in case you want to deserialize two objects from a single given `{}` json object, you can use this technique.

You may also find `JsonTransformingSerializer` (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations) helpful in this case.
