### ISSUE TITLE
IllegalAccessError throwable when using private serializer with typealias

### ISSUE THREAD

**Issue by PhilipDukhov** [Kotlin/kotlinx.serialization#2814]
**Describe the bug**

When using serializer for system classes by typealias, as in [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-a-serializer-globally-using-a-typealias), it feels like serializer should be private, otherwise code suggestions would suggest me the `XxxSerializer` when I'm looking for `XxxSerialized`, and serializer should never be suggested.

When I tried making it private, I've got a runtime exception:
```
Exception in thread "main" java.lang.IllegalAccessError: failed to access class com.phil.other.TimezoneSerializer from class com.phil.Container (com.phil.other.TimezoneSerializer and com.phil.Container are in unnamed module of loader 'app')
	at com.phil.Container.<clinit>(Main.kt:7)
	at com.phil.MainKt.main(Main.kt:24)
	at com.phil.MainKt.main(Main.kt)
```

**To Reproduce**
`TimezoneSerialized.kt`
```kotlin
package com.phil.otherPackage

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import java.time.ZoneId

typealias TimezoneSerialized = @Serializable(TimezoneSerializer::class) ZoneId

private class TimezoneSerializer : KSerializer<ZoneId> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Date", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): ZoneId {
        val string = decoder.decodeString()
        return try {
            ZoneId.of(string)
        } catch (e: Exception) {
            throw IllegalStateException("failed to parse time zone from $string")
        }
    }

    override fun serialize(
        encoder: Encoder,
        value: ZoneId,
    ) {
        encoder.encodeString(value.id)
    }
}
```
`main.kt`
```kotlin
package com.phil

import com.phil.otherPackage.TimezoneSerialized
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class Container(
    val timezone: TimezoneSerialized,
)

//TIP `com.phil.some`
fun main() {
    println(Json.decodeFromString<Container>("""{"timezone": "America/New_York"}"""))
}
```
**Expected behavior**

Perfectly it should be possible to make the serializer private. But the least I would expect is a compile-time check that shows it's not allowed, not at runtime.

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.7.2
 - Kotlin platforms: JVM
 - Gradle version: 8.8

**Comment by sandwwraith** [comment]
Filed https://youtrack.jetbrains.com/issue/KT-71680/Report-a-warning-when-Serializable-public-class-has-private-serializer
