### ISSUE TITLE
Compilation error with R8 8.5.xx and compose type safe navigation

### ISSUE THREAD

**Issue by Beb3r** [Kotlin/kotlinx.serialization#2825]
When using compose navigation type safe and switching to R8 tool version 8.5.xx (8.5.10/8.5.27/8.5.35) compilation fails

Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
at kotlinx.serialization.SerializationException.<init>(SerializationException.java:49)
       at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform_common.kt:91)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__Serializers.kt:278)
       at kotlinx.serialization.SerializersKt.serializer(Serializers.kt:1)
       at androidx.navigation.NavDestinationBuilder.<init>(NavDestinationBuilder.kt:91)
       at androidx.navigation.compose.ComposeNavigatorDestinationBuilder.<init>(ComposeNavigatorDestinationBuilder.kt:95)

When falling back to R8 8.3.xx, compilation doesn't fail.

**Environment**
 - Kotlin version: 2.0.0
 - Kotlinx serialization: 1.6.3
 - Gradle version: 8.7
 - Gradle plugin version: 8.6.1
 - Navigation: 2.8.0

**Comment by sandwwraith** [comment]
This looks like R8 issue. Have you tried reporting this to Google's issue tracker?

**Comment by Beb3r** [comment]
Good point!
Just did
https://issuetracker.google.com/issues/371227633

**Comment by Beb3r** [comment]
Adding the @Keep annotation on routes fixed the issue
(Navigation safe type relies on serialization, but since they're not referenced at runtime, R8 strips them away)

**Comment by sandwwraith** [comment]
Can it be the same issue as #2861 ? Do you use `@Serializable object` or only `@Serializable class`?
