### ISSUE TITLE
JsonLexer points to incorrect offset when ignoring unknown type

### ISSUE THREAD

**Issue by namhyun-gu** [Kotlin/kotlinx.serialization#2843]
**Describe the bug**

Hello.
When handling data with a JsonClassDiscriminator annotation on a list-type structure, ignoring exceptions for undefined types causes JsonLexer to point to an incorrect Offset.

The list data is used to process data provided by the server, and for lower versions of the application, we intend to ignore unknown types if they appear. To handle this, we have been using `Serializer` called `SafeListSerializer`, and processing worked correctly for versions prior to `1.6.1`.

- `SafeListSerializer`
```kotlin
open class SafeListSerializer<T>(
    serializer: KSerializer<T>
) : KSerializer<List<T>> {

    private val delegateSerializer = ListSerializer(SafeSerializer(serializer))
    override val descriptor = delegateSerializer.descriptor

    override fun serialize(encoder: Encoder, value: List<T>) = encoder.encodeSerializableValue(delegateSerializer, value)

    override fun deserialize(decoder: Decoder): List<T> = decoder.decodeSerializableValue(delegateSerializer).filterNotNull()
}

class SafeSerializer<T>(
    private val serializer: KSerializer<T>
) : KSerializer<T?> {

    override val descriptor = serializer.descriptor

    override fun serialize(encoder: Encoder, value: T?) = encoder.encodeSerializableValue(serializer, requireNotNull(value))

    override fun deserialize(decoder: Decoder): T? = kotlin.runCatching { decoder.decodeSerializableValue(serializer) }
        .getOrNull()
}
```

However, after the upgrade, we found that JsonLexer is referencing an incorrect Offset, as shown below.
This issue has been confirmed to reproduce in version 1.7.3 as well.

```
Unexpected JSON token at offset 175: Expected end of the array or comma at path: $.list[1]
JSON input: .....       },
                    {
                      "key":.....
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 175: Expected end of the array or comma at path: $.list[1]
JSON input: .....       },
                    {
                      "key":.....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeListIndex(StreamingJsonDecoder.kt:266)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:180)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:34)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at com.naver.webtoon.data.core.remote.json.serializer.SafeListSerializer.deserialize(SafeListSerializer.kt:17)
	at com.naver.webtoon.data.core.remote.json.serializer.SafeListSerializer.deserialize(SafeListSerializer.kt:8)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
```

**To Reproduce**

```kotlin
// JsonBuilder
val json = Json {
    explicitNulls = false
    ignoreUnknownKeys = true
    coerceInputValues = true
    encodeDefaults = true
}

// Define data class
object TestDataSerializer : SafeListSerializer<TestData>(TestData.serializer())

@Serializable
data class ApiResult(
    @Serializable(TestDataSerializer::class)
    val list: List<TestData>
)

@JsonClassDiscriminator("key")
@Serializable
sealed class TestData {
    @SerialName("A")
    @Serializable
    data class A(
        @SerialName("value") val value: String,
    ) : TestData()
}

// Test code
@Test
fun test_TestData() {
    val content =
        """
        {
            "list": [
                {
                  "key": "A",
                  "value": "A"
                },
                {
                  "key": "B",
                  "value": "B"
                }
            ]
        }
        """

    val apiResult = json.decodeFromString<ApiResult>(content)
    assertEquals(apiResult.list.size, 1) // Succeeded if the version is lower than 1.6.1
}
```

**Expected behavior**

An Unexpected JSON Token error should not occur for valid data.

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.7.1 (occurs in all version after version `1.6.1`)
 - Kotlin platforms: JVM
 - Gradle version: 8.7

**Comment by sandwwraith** [comment]
There are no guarantees on exception safety, so you shouldn't use `runCatching` — see 'Exception safety' paragraph in https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.encoding/-decoder/

**Comment by namhyun-gu** [comment]
Thank you for sharing the document. It helped me a lot.
