### ISSUE TITLE
Wasm target compile failed after update Kotlin 2.1.0

### ISSUE THREAD

**Issue by FlowFan** [Kotlin/kotlinx.serialization#2870]
**Describe the bug**
The error occurs after updating Kotlin from 2.0.21 to 2.1.0, But both Android, iOS and desktop target can be compiled successfully.
```
e: KLIB resolver: The same 'unique_name=kotlin' found in more than one library: ~/org.jetbrains.kotlin/kotlin-stdlib-wasm-js/2.1.0/b96271506fb37f4d8d1c63db7a57384ab16ae218/kotlin-stdlib-wasm-js-2.1.0.klib, ~/org.jetbrains.kotlin/kotlin-stdlib-wasm/1.9.0/ec6525e2b8f7cf4f4fe62db24012ec26d0803ea/kotlin-stdlib-wasm-1.9.0.klib
Please file an issue to https://kotl.in/issue and meanwhile use CLI flag `-Xklib-duplicated-unique-name-strategy` with one of the following values:
allow-all-with-warning: Use all KLIB dependencies, even when they have same `unique_name` property.
allow-first-with-warning: Use the first KLIB dependency with clashing `unique_name` property. No order guarantees are given though.
deny: Fail a compilation with the error.
e: org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
~/DailyWord.kt:6:1
Problem with `@Deprecated(message = "This synthesized declaration should not be used directly", level = DeprecationLevel.HIDDEN)
@StabilityInferred(parameters = 0)
object $serializer : GeneratedSerializer<DailyWord> {
  private constructor() /* primary */ {
    super/*Any*/()
    /* <init>() */

  }

  override fun serialize(encoder: Encoder, value: DailyWord) {
    val tmp0_desc: SerialDescriptor = <this>.<get-descriptor>()
    val tmp1_output: CompositeEncoder = encoder.beginStructure(descriptor = tmp0_desc)
    when {
      when {
        tmp1_output.shouldEncodeElementDefault(descriptor = tmp0_desc, index = 0) -> true
        else -> EQEQ(arg0 = value.<get-text>(), arg1 = "").not()
      } -> tmp1_output.encodeStringElement(descriptor = tmp0_desc, index = 0, value = value.<get-text>())
    }
    when {
      when {
        tmp1_output.shouldEncodeElementDefault(descriptor = tmp0_desc, index = 1) -> true
        else -> EQEQ(arg0 = value.<get-from>(), arg1 = "").not()
      } -> tmp1_output.encodeStringElement(descriptor = tmp0_desc, index = 1, value = value.<get-from>())
    }
    tmp1_output.endStructure(descriptor = tmp0_desc)
  }

  override fun deserialize(decoder: Decoder): DailyWord {
    val tmp0_desc: SerialDescriptor = <this>.<get-descriptor>()
    var tmp1_flag: Boolean = true
    var tmp2_index: Int = 0
    var tmp3_bitMask0: Int = 0
    var tmp4_local0: String? = null
    var tmp5_local1: String? = null
    val tmp6_input: CompositeDecoder = decoder.beginStructure(descriptor = tmp0_desc)
    when {
      tmp6_input.decodeSequentially() -> { // BLOCK
        { // BLOCK
          tmp4_local0 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 0)
          tmp3_bitMask0 = tmp3_bitMask0.or(other = 1)
        }
        { // BLOCK
          tmp5_local1 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 1)
          tmp3_bitMask0 = tmp3_bitMask0.or(other = 2)
        }
      }
      else -> while (tmp1_flag) { // BLOCK
        tmp2_index = tmp6_input.decodeElementIndex(descriptor = tmp0_desc)
        when {
          EQEQ(arg0 = tmp2_index, arg1 = -1) -> tmp1_flag = false
          EQEQ(arg0 = tmp2_index, arg1 = 0) -> { // BLOCK
            tmp4_local0 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 0)
            tmp3_bitMask0 = tmp3_bitMask0.or(other = 1)
          }
          EQEQ(arg0 = tmp2_index, arg1 = 1) -> { // BLOCK
            tmp5_local1 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 1)
            tmp3_bitMask0 = tmp3_bitMask0.or(other = 2)
          }
          else -> throw UnknownFieldException(index = tmp2_index)
        }
      }
    }
    tmp6_input.endStructure(descriptor = tmp0_desc)
    return DailyWord(seen0 = tmp3_bitMask0, text = tmp4_local0, from = tmp5_local1, serializationConstructorMarker = null)
  }

  override val descriptor: SerialDescriptor
    override get

  override fun childSerializers(): Array<KSerializer<*>>

  /* fake */ override fun typeParametersSerializers(): Array<KSerializer<*>>

  /* fake */ override operator fun equals(other: Any?): Boolean

  /* fake */ override fun hashCode(): Int

  /* fake */ override fun toString(): String

  init {
    val tmp0_serialDesc: PluginGeneratedSerialDescriptor = PluginGeneratedSerialDescriptor(serialName = "xxx.DailyWord", generatedSerializer = <this>, elementsCount = 2)
    tmp0_serialDesc.addElement(name = "text", isOptional = true)
    tmp0_serialDesc.addElement(name = "from", isOptional = true)
    <this>.#descriptor = tmp0_serialDesc
  }

}

Details: kotlinx.serialization compiler plugin internal error: unable to transform declaration, see cause
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:230)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:46)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:48)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
	at org.jetbrains.kotlin.ir.declarations.IrClass.acceptChildren(IrClass.kt:76)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:48)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:34)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitElement(SerializationLoweringExtension.kt:42)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:172)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitPackageFragment(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:188)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:184)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt.runOnFileInOrder(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtension.generate(SerializationLoweringExtension.kt:194)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:472)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:241)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:130)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize(convertToIr.kt:100)
	at org.jetbrains.kotlin.cli.js.klib.JsCompilerPipelineKt.transformFirToIr(jsCompilerPipeline.kt:233)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.processSourceModuleWithK2(K2JSCompiler.kt:695)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.produceSourceModule(K2JSCompiler.kt:560)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:345)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:105)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:102)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:316)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:199)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:74)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:506)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:113)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:608)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:91)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1757)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: List has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:618)
	at org.jetbrains.kotlin.fir.backend.IrBuiltInsOverFir.arrayOf_delegate$lambda$63(IrBuiltInsOverFir.kt:287)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at org.jetbrains.kotlin.fir.backend.IrBuiltInsOverFir.getArrayOf(IrBuiltInsOverFir.kt:284)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderWithPluginContext.createArrayOfExpression(IrBuilderWithPluginContext.kt:243)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.generateChildSerializersGetter$lambda$23(SerializerIrGenerator.kt:246)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderWithPluginContext.addFunctionBody(IrBuilderWithPluginContext.kt:48)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.generateChildSerializersGetter(SerializerIrGenerator.kt:228)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator.generate(SerializerIrGenerator.kt:621)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerIrGenerator$Companion.generate(SerializerIrGenerator.kt:649)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:147)
	... 62 more

warning Ignored scripts due to flag.

FAILURE: Build failed with an exception.
```

**To Reproduce**
The minimal reproducible code is as follows
```
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.1")
implementation("com.soywiz.korlibs.krypto:krypto:4.0.10")
```

**Expected behavior**
Compilation does not report an error, just like using kotlin2.0.21.

**Environment**
 - Kotlin version: 2.1.0
 - Library version: 1.7.1
 - Kotlin platforms: Wasm
 - Gradle version: 8.10.2

**Comment by sandwwraith** [comment]
Have you tried reporting this yo YouTrack? It does not look directly related to kotlinx.serialization

**Comment by FlowFan** [comment]
> Have you tried reporting this yo YouTrack? It does not look directly related to kotlinx.serialization

When I use @Serializable, I get the following error, and I also report it to YouTrack, and I haven't received a reply yet
```
e: org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
~/DailyWord.kt:6:1
Problem with `@Deprecated(message = "This synthesized declaration should not be used directly", level = DeprecationLevel.HIDDEN)
@StabilityInferred(parameters = 0)
object $serializer : GeneratedSerializer<DailyWord> {
  private constructor() /* primary */ {
    super/*Any*/()
    /* <init>() */

  }

  override fun serialize(encoder: Encoder, value: DailyWord) {
    val tmp0_desc: SerialDescriptor = <this>.<get-descriptor>()
    val tmp1_output: CompositeEncoder = encoder.beginStructure(descriptor = tmp0_desc)
    when {
      when {
        tmp1_output.shouldEncodeElementDefault(descriptor = tmp0_desc, index = 0) -> true
        else -> EQEQ(arg0 = value.<get-text>(), arg1 = "").not()
      } -> tmp1_output.encodeStringElement(descriptor = tmp0_desc, index = 0, value = value.<get-text>())
    }
    when {
      when {
        tmp1_output.shouldEncodeElementDefault(descriptor = tmp0_desc, index = 1) -> true
        else -> EQEQ(arg0 = value.<get-from>(), arg1 = "").not()
      } -> tmp1_output.encodeStringElement(descriptor = tmp0_desc, index = 1, value = value.<get-from>())
    }
    tmp1_output.endStructure(descriptor = tmp0_desc)
  }

  override fun deserialize(decoder: Decoder): DailyWord {
    val tmp0_desc: SerialDescriptor = <this>.<get-descriptor>()
    var tmp1_flag: Boolean = true
    var tmp2_index: Int = 0
    var tmp3_bitMask0: Int = 0
    var tmp4_local0: String? = null
    var tmp5_local1: String? = null
    val tmp6_input: CompositeDecoder = decoder.beginStructure(descriptor = tmp0_desc)
    when {
      tmp6_input.decodeSequentially() -> { // BLOCK
        { // BLOCK
          tmp4_local0 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 0)
          tmp3_bitMask0 = tmp3_bitMask0.or(other = 1)
        }
        { // BLOCK
          tmp5_local1 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 1)
          tmp3_bitMask0 = tmp3_bitMask0.or(other = 2)
        }
      }
      else -> while (tmp1_flag) { // BLOCK
        tmp2_index = tmp6_input.decodeElementIndex(descriptor = tmp0_desc)
        when {
          EQEQ(arg0 = tmp2_index, arg1 = -1) -> tmp1_flag = false
          EQEQ(arg0 = tmp2_index, arg1 = 0) -> { // BLOCK
            tmp4_local0 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 0)
            tmp3_bitMask0 = tmp3_bitMask0.or(other = 1)
          }
          EQEQ(arg0 = tmp2_index, arg1 = 1) -> { // BLOCK
            tmp5_local1 = tmp6_input.decodeStringElement(descriptor = tmp0_desc, index = 1)
            tmp3_bitMask0 = tmp3_bitMask0.or(other = 2)
          }
          else -> throw UnknownFieldException(index = tmp2_index)
        }
      }
    }
    tmp6_input.endStructure(descriptor = tmp0_desc)
    return DailyWord(seen0 = tmp3_bitMask0, text = tmp4_local0, from = tmp5_local1, serializationConstructorMarker = null)
  }

  override val descriptor: SerialDescriptor
    override get

  override fun childSerializers(): Array<KSerializer<*>>

  /* fake */ override fun typeParametersSerializers(): Array<KSerializer<*>>

  /* fake */ override operator fun equals(other: Any?): Boolean

  /* fake */ override fun hashCode(): Int

  /* fake */ override fun toString(): String

  init {
    val tmp0_serialDesc: PluginGeneratedSerialDescriptor = PluginGeneratedSerialDescriptor(serialName = "xxx.DailyWord", generatedSerializer = <this>, elementsCount = 2)
    tmp0_serialDesc.addElement(name = "text", isOptional = true)
    tmp0_serialDesc.addElement(name = "from", isOptional = true)
    <this>.#descriptor = tmp0_serialDesc
  }

}
```

**Comment by FlowFan** [comment]
> This error is completely unrelated to the one you posted above. So it seems there are two different problems. Can you link both YT issues here, please?

They're stacked together, I'm sorry I didn't copy them all, it's YK link.
https://youtrack.jetbrains.com/issue/CMP-7165/Wasm-compile-failed-after-update-Kotlin-2.1.0

**Comment by sandwwraith** [comment]
Closing in favor of https://youtrack.jetbrains.com/issue/CMP-7165 — this is an outdated dependency problem
