### ISSUE TITLE
Fail parsing JSON with '~' char

### ISSUE THREAD

**Issue by ilaborie** [Kotlin/kotlinx.serialization#3]
I've got an

```
java.lang.ArrayIndexOutOfBoundsException: 127
	at kotlinx.serialization.json.JSON$Companion.c2tc(JSON.kt:107)
	at kotlinx.serialization.json.JSON$Parser.nextString(JSON.kt:502)
	at kotlinx.serialization.json.JSON$Parser.nextToken(JSON.kt:465)
	at kotlinx.serialization.json.JSON$JsonInput.readElement(JSON.kt:402)
	at Data$Companion.load(main.kt)
	at Data$Companion.load(main.kt:6)
	at kotlinx.serialization.KInput.read(Serialization.kt:187)
	at kotlinx.serialization.json.JSON.parse(JSON.kt:45)
	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:55)
	at MainKt.main(main.kt:14)
```

With this code: 

```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.JSON

@Serializable
data class Data(val a: Int, @Optional val b: String = "42")

fun main(args: Array<String>) {
    println(JSON.stringify(Data(42))) // {"a": 42, "b": "42"}
    val obj = JSON.parse<Data>("""{"a":42, "b":"~"}""") // Data(a=42, b="~")
}
```

**Comment by sandwwraith** [comment]
Fixed by 2e944e6
