### ISSUE TITLE
Automatically apply null as default value for @Optional nullable property

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Kotlin/kotlinx.serialization#300]
```kotlin
import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable

@Serializable
data class ErrorTest(@Optional val error: String?)
```

```
e: org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: 'package net.perfectdreams.spicymorenitta.views.dashboard

import kotlinx.serialization.Optional
import kotlinx.serialization.Serializable

@Serializable
data class ErrorTest(@Optional val error: String?)' at (1,1) in C:/Users/Whistler/Documents/IdeaProjects/Loritta/SpicyMorenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/views/dashboard/HelloWorld.kt
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:437)
        at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:346)
        at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:308)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.java:137)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.java:99)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:152)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:286)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:82)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:442)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1029)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1071)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1028)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:441)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: optional without an initializer
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:74)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$generateInternalConstructor$f$1.invoke(SerializableJsTranslator.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.JsCodegenUtilKt.buildFunction(JsCodegenUtil.kt:84)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator.generateInternalConstructor(SerializableJsTranslator.kt:56)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:33)
        at org.jetbrains.kotlinx.serialization.compiler.backend.js.SerializableJsTranslator$Companion.translate(SerializableJsTranslator.kt:115)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationJsExtension.generateClassSyntheticParts(SerializationJsExtension.kt:31)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.generateClassSyntheticParts(ClassTranslator.kt:156)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.translate(ClassTranslator.kt:111)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator.access$translate(ClassTranslator.kt:63)
        at org.jetbrains.kotlin.js.translate.declaration.ClassTranslator$Companion.translate(ClassTranslator.kt:573)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:48)
        at org.jetbrains.kotlin.js.translate.declaration.AbstractDeclarationVisitor.visitClassOrObject(AbstractDeclarationVisitor.kt:41)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:34)
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:429)
        ... 35 more

> Task :compileKotlin2Js FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin2Js'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed
```

Adding a default `null` value fixes the issue
```kotlin
@Serializable
data class ErrorTest(@Optional val error: String? = null)
```

But I guess it should be smart enough to suppose that "well, this field is nullable, so the default value if the field doesn't exist in the data should be null", right?

Or at least show a more "user friendly" error? (I only noticed after submitting the issue the "Caused by: java.lang.IllegalArgumentException: optional without an initializer" exception... derp, but still it isn't *that* user friendly)

**Comment by sandwwraith** [comment]
I can agree that the error is quite cumbersome and we definitely would work on compiler diagnostics and IDE support. 

Setting default value to `null` for optional nullable properties is probably reasonable, but current design tends to be explicit (see also #19). We can always strip down these restrictions later if we found these defaults sane.

**Comment by qwwdfsad** [comment]
`@Optional` annotation was removed, so closing as obsolete
