### ISSUE TITLE
VerifyError when using serializer with base class

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#315]
I have a custom serializer that deserializes a list and checks for duplicates, `PrerequisiteListDeserializer`. 

If I directly implement `KSerializer` on it, it behaves as expected.

If I move some of that functionality to a base class, I get a `java.lang.VerifyError` when attempting to use it:

```
java.lang.VerifyError: Bad <init> method call
Exception Details:
  Location:
    batect/config/io/deserializers/PrerequisiteListDeserializer.<init>(Lkotlinx/serialization/KSerializer;)V @11: invokespecial
  Reason:
    Type 'java/lang/Object' is not assignable to 'batect/config/io/deserializers/PrerequisiteListDeserializer'
  Bytecode:
    0x0000000: b800 954d 2b12 64b8 0029 2ab7 0067 2a2b
    0x0000010: b500 552c 100d 0454 b1
    at batect.config.io.TaskFromFile$$serializer.deserialize(TaskFromFile.kt)
    at batect.config.io.TaskFromFile$$serializer.deserialize(TaskFromFile.kt:28)
    at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:92)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:141)
    at kotlinx.serialization.internal.MapLikeSerializer.readItem(CollectionSerializers.kt:124)
    at kotlinx.serialization.internal.MapLikeSerializer.readItem(CollectionSerializers.kt:102)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
    at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:92)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:141)
    at batect.config.io.ConfigurationFile$$serializer.deserialize(ConfigurationFile.kt)
    at batect.config.io.ConfigurationFile$$serializer.deserialize(ConfigurationFile.kt:28)
    at kotlinx.serialization.CoreKt.decode(Core.kt:84)
    at com.charleskorn.kaml.Yaml.parse(Yaml.kt:34)
    at batect.config.io.ConfigurationLoader.loadConfig(ConfigurationLoader.kt:65)
```

<details>
<summary>PrerequisiteListDeserializer.kt</summary>

```kotlin
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer

@Serializer(forClass = List::class)
object PrerequisiteListDeserializer : UniqueStringCollectionDeserializer<List<String>, MutableList<String>>(), KSerializer<List<String>> {
    override fun createEmptyCollection(): MutableList<String> = mutableListOf()
    override fun MutableList<String>.toFinal(): List<String> = this

    override fun getDuplicateValueMessage(value: String) = "The prerequisite '$value' is given more than once"
}
```
</details>

<details>
<summary>UniqueStringCollectionDeserializer.kt</summary>

```kotlin
import batect.config.io.ConfigurationException
import com.charleskorn.kaml.YamlInput
import kotlinx.serialization.CompositeDecoder
import kotlinx.serialization.Decoder
import kotlinx.serialization.Encoder
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialDescriptor
import kotlinx.serialization.internal.HashSetClassDesc
import kotlinx.serialization.internal.StringSerializer

abstract class UniqueStringCollectionDeserializer<TFinal : Collection<String>, TBuilder : MutableCollection<String>> : KSerializer<TFinal> {
    private val elementSerializer = StringSerializer

    override val descriptor: SerialDescriptor = HashSetClassDesc(elementSerializer.descriptor)

    override fun deserialize(input: Decoder): TFinal {
        val structureInput = input.beginStructure(descriptor, elementSerializer)
        val result = read(structureInput)

        structureInput.endStructure(descriptor)

        return result
    }

    private fun read(input: CompositeDecoder): TFinal {
        val size = input.decodeCollectionSize(descriptor)

        while (true) {
            when (val index = input.decodeElementIndex(descriptor)) {
                CompositeDecoder.READ_ALL -> return readAll(input, size)
                CompositeDecoder.READ_DONE -> return createEmptyCollection().toFinal()
                else -> return readUntilDone(input, index)
            }
        }
    }

    private fun readAll(input: CompositeDecoder, size: Int): TFinal {
        val soFar = createEmptyCollection()

        for (currentIndex in 0..size) {
            soFar.add(readSingle(input, currentIndex, soFar))
        }

        return soFar.toFinal()
    }

    private fun readUntilDone(input: CompositeDecoder, firstIndex: Int): TFinal {
        var currentIndex = firstIndex
        val soFar = createEmptyCollection()

        do {
            soFar.add(readSingle(input, currentIndex, soFar))

            currentIndex = input.decodeElementIndex(descriptor)
        } while (currentIndex != CompositeDecoder.READ_DONE)

        return soFar.toFinal()
    }

    private fun readSingle(input: CompositeDecoder, index: Int, soFar: TBuilder): String {
        val value = input.decodeSerializableElement(descriptor, index, elementSerializer)

        if (value in soFar) {
            val location = (input as YamlInput).getCurrentLocation()

            throw ConfigurationException(getDuplicateValueMessage(value), null, location.line, location.column, null)
        }

        return value
    }

    override fun serialize(output: Encoder, obj: TFinal) = throw UnsupportedOperationException()

    protected abstract fun createEmptyCollection(): TBuilder
    protected abstract fun TBuilder.toFinal(): TFinal

    protected abstract fun getDuplicateValueMessage(value: String): String
}
```
</details>

**Comment by charleskorn** [comment]
I should mention that this is with version 0.9.1 of the runtime with Kotlin 1.3.11.

**Comment by charleskorn** [comment]
In a similar vein, if I have a base class that implements the methods and properties for `KSerializer`, but only declare the interface on the parent class, it looks like the compiler tries to generate a `descriptor` field again, even though there's a valid one on the base class. (This doesn't seem to happen for the `serialize` and `deserialize` methods.) If I move the `descriptor` field to the parent class, then the error doesn't occur.

```
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Class TaskMap have constructor parameters which are not properties and therefore it is not serializable automatically
File being compiled at position: file:///Users/charleskorn/Repositories/Personal/batect/app/src/main/kotlin/batect/config/TaskMap.kt
The root cause was thrown at: SerializerCodegen.kt:39
        at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
        at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:455)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:154)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:159)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:357)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:99)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:222)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:37)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:88)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:100)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:590)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:455)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1013)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1055)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1012)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:454)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Class TaskMap have constructor parameters which are not properties and therefore it is not serializable automatically
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.checkSerializability(SerializerCodegen.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generateSerializableClassPropertyIfNeeded(SerializerCodegen.kt:107)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generate(SerializerCodegen.kt:45)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl$Companion.generateSerializerExtensions(SerializerCodegenImpl.kt:49)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationCodegenExtension.generateClassSyntheticParts(SerializationCodegenExtension.kt:30)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:435)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:132)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:312)
        at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:102)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:129)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:161)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:119)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
        ... 43 more
```

This is with runtime version 0.10.0 and Kotlin 1.3.20.

**Comment by sandwwraith** [comment]
For your first problem, I can say that since you're trying to implement a serializer for a generic class (`List`), then it should have one constructor parameter: a serializer for list elements (`List` has one generic argument, therefore one constructor parameter in serializer).

**Comment by sandwwraith** [comment]
For the second thing, am I right that you're trying to implement serializer inheritance? Since the error tells `Class TaskMap have constructor parameters which are not properties and therefore it is not serializable automatically` and it is not completely related to it, it is more like #317

**Comment by charleskorn** [comment]
> For your first problem, I can say that since you're trying to implement a serializer for a generic class (`List`), then it should have one constructor parameter: a serializer for list elements (`List` has one generic argument, therefore one constructor parameter in serializer).

I don't understand why this is relevant here - if I have no inheritance for the serializer (so `UniqueStringCollectionDeserializer` is merged into `PrerequisiteListDeserializer`), everything works correctly, but if I split the serializer into a base class and the parent class, then I get the error. 

> For the second thing, am I right that you're trying to implement serializer inheritance? Since the error tells `Class TaskMap have constructor parameters which are not properties and therefore it is not serializable automatically` and it is not completely related to it, it is more like #317

#317 does sound related, but again, I only have this issue when inheritance is involved - if the `descriptor` field is on the parent class, I don't see the error.

**Comment by fluidsonic** [comment]
I also ran into the second issue.

Repro:
```kt
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*


class Foo(value: String) {

    val value = value
}

@Serializer(forClass = Foo::class)
object FooSerializer : AbstractFooSerializer()

abstract class AbstractFooSerializer : KSerializer<Foo> {

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Foo", PrimitiveKind.STRING)


    override fun deserialize(decoder: Decoder): Foo =
        Foo(decoder.decodeString())


    override fun serialize(encoder: Encoder, value: Foo) {
        encoder.encodeString(value.value)
    }
}
```

```
java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation
File being compiled: file:///Users/marc/Documents/kotlin-test-gradle/src/main/kotlin/Main.kt
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.checkSerializability(SerializerCodegen.kt:26)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:78)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:647)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:210)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:162)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:371)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:249)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:89)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:602)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1644)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Class Foo have constructor parameters which are not properties and therefore it is not serializable automatically
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.checkSerializability(SerializerCodegen.kt:26)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generateSerializableClassPropertyIfNeeded(SerializerCodegen.kt:99)
	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generate(SerializerCodegen.kt:32)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl$Companion.generateSerializerExtensions(SerializerCodegenImpl.kt:44)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationCodegenExtension.generateClassSyntheticParts(SerializationCodegenExtension.kt:30)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:440)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:132)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:119)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:138)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:70)
	... 35 more
```

**Comment by pdvrieze** [comment]
@fluidsonic The problem you have is that the code generation generates serialization code unless it is specified in the particular class. It doesn't look at the parent. The workaround would be to specify the concrete serializer to explicity call the parent.

**Comment by fluidsonic** [comment]
@pdvrieze I understand that. But that would mean hundreds of otherwise useless overrides which shouldn't be needed. Way too much boilerplate and in my case not even good as a workaround. Is there already a distinct issue tracking that problem?

**Comment by pdvrieze** [comment]
Actually there is, don't use the `@Serializer` annotation and no code will be generated. It will still work (and if you annotate the type with `@Serializable` even found automatically).

**Comment by shanshin** [comment]
Not reproduced in 1.5.31 version for IR backend
