### ISSUE TITLE
Android application using multiplatform lib gets a lot of ClassNotFoundException with kotlinx.serialization

### ISSUE THREAD

**Issue by Syrou** [Kotlin/kotlinx.serialization#322]
So I have created a multiplatform library and a customer is using the library in his/her application.
Previously everything worked fine, but for whatever reason when we updated to kotlin version 1.3.11
and kotlin.serialization version 0.9.1 We have issues with finding classes in the library.

A few examples:
```
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.serialization.json.JSON" on path: DexPathList[[zip file "/data/app/com.adf.ss.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.adf.sd.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/lib/arm, /data/app/com.adf.sd.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

and

```
  Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.serialization.KSerializer" on path: DexPathList[[zip file "/data/app/com.adf.sd.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.adf.sd.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/lib/arm, /data/app/com.adf.sd.ff.sda-V9Kom0n7YNvyCUDOzD7WFQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void com.asd.dfg.asdf.models.ApiToken.<clinit>() (ApiToken.kt:-1)
```

What is causing this? Are there any new depedencies that the android application must add?

**Comment by sandwwraith** [comment]
Could this be a problem with missing transitive dependency on runtime? Runtime library itself didn't introduce any new dependencies

**Comment by Syrou** [comment]
@sandwwraith You are most certainly correct, i'm just confused as to why I'm seeing this when i started using the later versions of everything. I have made sure the dependencies are included in the pom-file now so that they may be found with using the transitive = true setting out in the client application.

**Comment by sandwwraith** [comment]
So this was problem with configuration, not the library?

**Comment by Syrou** [comment]
The issue can be solved by making sure that all the kotlin related code is being added to the pom-file yes.

**Comment by moeindev** [comment]
I have exactly the same problem! Is there anyway to build a fat AAR from kmm project and use it that way?
