### ISSUE TITLE
How to parse List<java.net.URL>?

### ISSUE THREAD

**Issue by BoxResin** [Kotlin/kotlinx.serialization#366]
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.JSON
import java.net.URL

fun main() {
    val json = """
        {
            "urls": [
                "https://github.com",
                "https://stackoverflow.com",
                "https://kotlinlang.org/"
            ]
        }
    """.trimIndent()

    val dummy = JSON.parse(Dummy.serializer(), json)
    println(dummy)
}

@Serializable
data class Dummy(
    @Serializable(with = URLSerializer::class)
    val urls: List<URL>
)

@Serializer(forClass = URL::class)
object URLSerializer : KSerializer<URL> {
    override fun deserialize(input: Decoder): URL {
        return URL(input.decodeString())
    }

    override fun serialize(output: Encoder, obj: URL) {
        output.encodeString(obj.toString())
    }
}
```

It throws
```
Exception in thread "main" kotlinx.serialization.json.JsonParsingException: Invalid JSON at 14: Expected string or non-null literal
	at kotlinx.serialization.json.Parser.takeStr(JsonParser.kt:329)
	at kotlinx.serialization.json.JSON$JsonInput.decodeString(JSON.kt:337)
	at com.buzzni.android.subapp.shoppingmoa.URLSerializer.deserialize(AnyKotlinTest.kt:43)
	at com.buzzni.android.subapp.shoppingmoa.URLSerializer.deserialize(AnyKotlinTest.kt:41)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:92)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:141)
	at com.buzzni.android.subapp.shoppingmoa.Dummy$$serializer.deserialize(AnyKotlinTest.kt)
	at com.buzzni.android.subapp.shoppingmoa.Dummy$$serializer.deserialize(AnyKotlinTest.kt:35)
	at kotlinx.serialization.CoreKt.decode(Core.kt:84)
	at kotlinx.serialization.json.JSON.parse(JSON.kt:43)
	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:60)
	at com.buzzni.android.subapp.shoppingmoa.AnyKotlinTestKt.main(AnyKotlinTest.kt:19)
	at com.buzzni.android.subapp.shoppingmoa.AnyKotlinTestKt.main(AnyKotlinTest.kt)
```

**Comment by sandwwraith** [comment]
`@Serializable(with)` affects whole property type, i.e. `List<URL>`, not only `URL`. You can use `@file:UseSerializer(URLSerializer::class)` to substitute serializer everywhere

**Comment by BoxResin** [comment]
@sandwwraith 
Thank you! It works.
