### ISSUE TITLE
is there a way to import kotlin serialization only on library project?

### ISSUE THREAD

**Issue by leohsmedeiros** [Kotlin/kotlinx.serialization#371]
Hi, That is my first project with multplatform library on Kotlin.
So I have this library in kotlin to share DTO and domain classes between server and clients (Android and iOS). But on Android and on Server (Java maven) I must include "kotlinx-serialization-runtime" to avoid the exception "java.lang.NoClassDefFoundError: kotlinx.serialization.CompositeEncoder". Is there a way to import "kotlinx-serialization-runtime" only on library project and it comes on generated .jar ?

Here is the error on Android:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.irvem, PID: 30982
    java.lang.NoClassDefFoundError: kotlinx.serialization.CompositeEncoder
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:476)
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
        at java.lang.reflect.Method.getParameterTypes(Method.java:170)
        at java.lang.Class.getDeclaredMethods(Class.java:673)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.<init>(com.google.firebase:firebase-database@@16.0.4:486)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.loadOrCreateBeanMapperForClass(com.google.firebase:firebase-database@@16.0.4:317)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertBean(com.google.firebase:firebase-database@@16.0.4:418)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(com.google.firebase:firebase-database@@16.0.4:214)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToCustomClass(com.google.firebase:firebase-database@@16.0.4:79)
        at com.google.firebase.database.DataSnapshot.getValue(com.google.firebase:firebase-database@@16.0.4:212)
        at com.irvem.data.UserObservableHolder$1.onDataChange(UserObservableHolder.java:19)
        at com.google.firebase.database.Query$1.onDataChange(com.google.firebase:firebase-database@@16.0.4:183)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.4:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.4:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.4:55)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5472)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.serialization.CompositeEncoder" on path: DexPathList[[zip file "/data/app/com.irvem-1/base.apk"],nativeLibraryDirectories=[/data/app/com.irvem-1/lib/arm, /data/app/com.irvem-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:476) 
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:170) 
        at java.lang.Class.getDeclaredMethods(Class.java:673) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.<init>(com.google.firebase:firebase-database@@16.0.4:486) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.loadOrCreateBeanMapperForClass(com.google.firebase:firebase-database@@16.0.4:317) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertBean(com.google.firebase:firebase-database@@16.0.4:418) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(com.google.firebase:firebase-database@@16.0.4:214) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToCustomClass(com.google.firebase:firebase-database@@16.0.4:79) 
        at com.google.firebase.database.DataSnapshot.getValue(com.google.firebase:firebase-database@@16.0.4:212) 
        at com.irvem.data.UserObservableHolder$1.onDataChange(UserObservableHolder.java:19) 
        at com.google.firebase.database.Query$1.onDataChange(com.google.firebase:firebase-database@@16.0.4:183) 
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.4:75) 
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.4:63) 
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.4:55) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:153) 
        at android.app.ActivityThread.main(ActivityThread.java:5472) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: kotlinx.serialization.CompositeEncoder
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 24 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by sandwwraith** [comment]
Probably you should use `api` dependency on kotlinx.serialization in your library instead of `implementation`

**Comment by leohsmedeiros** [comment]
Thanks for reply @sandwwraith !
I did the change but I'm still getting the error. Here is my gradle scripts:

```
plugins {
    id 'kotlin-multiplatform' version '1.3.21'
    id 'kotlinx-serialization' version '1.3.21'
}

repositories {
    mavenCentral()
 
    maven { url "https://plugins.gradle.org/m2/" }
    maven { url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies" }
    maven { url "https://kotlin.bintray.com/kotlinx" }

    maven { url "https://dl.bintray.com/soywiz/soywiz" }
    maven { url "http://kotlin.bintray.com/kotlin-eap" }
    maven { url "http://kotlin.bintray.com/kotlin-dev" }
    maven { url "https://dl.bintray.com/sargunster/maven" }
    maven { url "https://dl.bintray.com/kotlin/squash" }
    maven { url "https://dl.bintray.com/russhwolf/multiplatform-settings" }

    jcenter()
}

group 'com.irvem'
version '0.0.1'

apply plugin: 'maven-publish'

ext {
    serialization_version = '0.10.0'
}

kotlin {
    targets {        
        fromPreset(presets.jvm, 'jvm')

        fromPreset(project.hasProperty('iosDevice') ? presets.iosArm64 : presets.iosX64, 'ios') {
            compilations.main.outputKinds('FRAMEWORK')
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
                api "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
            }
        }
        commonTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test-common'
                implementation 'org.jetbrains.kotlin:kotlin-test-annotations-common'
            }
        }
        jvmMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
                api "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
            }
        }
        jvmTest {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-test'
                implementation 'org.jetbrains.kotlin:kotlin-test-junit'
            }
        }
        iosMain {
            dependencies {
                api "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
            }
        }
        iosTest {}
    }
}

configurations {
    compileClasspath
}

```

And settings.gradle:

```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlin-multiplatform") {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
            }
            if (requested.id.id == "kotlinx-serialization") {
                useModule("org.jetbrains.kotlin:kotlin-serialization:${requested.version}")
            }
        }
    }
}

rootProject.name = 'sharedlib'

enableFeaturePreview('GRADLE_METADATA')

```

**Comment by sandwwraith** [comment]
Closing as obsolete, please re-open if you still have issues or questions
