### ISSUE TITLE
NoClassDefFoundError exception occurred for latest Kotlin version

### ISSUE THREAD

**Issue by zhewang2** [Kotlin/kotlinx.serialization#423]
NoClassDefFoundError exception occurred in running timing when deserialize the JSON response from retrofit converter.

```
[04-04-19 13:29:02.237] [3ca80f36b487d712_MOBORCH-1JY8J7L13SWEOLSXU26QS32BPO0_ANDROIDNEG] ERROR  c.p.m.o.r.s.h.HotelRetailDetailsServiceImpl - java.lang.NoClassDefFoundError: kotlinx/serialization/ResolvingKt
java.lang.NoClassDefFoundError: kotlinx/serialization/ResolvingKt
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Factory.responseBodyConverter(Factory.kt:23) ~[retrofit2-kotlinx-serialization-converter-0.3.0.jar:na]
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:328) ~[retrofit-2.5.0.jar:na]
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:311) ~[retrofit-2.5.0.jar:na]
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:68) ~[retrofit-2.5.0.jar:na]
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:46) ~[retrofit-2.5.0.jar:na]
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:36) ~[retrofit-2.5.0.jar:na]
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:168) ~[retrofit-2.5.0.jar:na]
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147) ~[retrofit-2.5.0.jar:na]
	at com.sun.proxy.$Proxy150.retail(Unknown Source) ~[na:na]
	at HotelRetailDetailsServiceImpl.retail(HotelRetailDetailsServiceImpl.kt:31) ~[classes/:na]
```
Here is the details:
```
        <kotlin.version>1.3.30-eap-125</kotlin.version>
        <kotlinx-coroutines-core.verion>1.1.1</kotlinx-coroutines-core.verion>
        <kotlin-serialization.version>0.11.0-1.3.30-eap-125</kotlin-serialization.version>
```
It appears the file was renamed which contained a top-level function that this library uses ( https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter). Would you mind maintaining binary compatibility by specifying @file:JvmName("ResolvingKt")?

**Comment by zhewang2** [comment]
Any update available?

**Comment by sandwwraith** [comment]
Sorry, but we are more focused now on developing core API and features of the library. This is emphasised by 'experimental' status of project and its `0.x.y` versions. 
While there are migration aids to maintain source backwards compatibility (like @Deprecated annotations), binary compatibility is a _non-goal_ for now, until 1.0 API is stabilised.

Retrofit converter usually updates very quick after non-eap artifact is released. Meanwhile, you can try to build it yourself with eap version, this shouldn't be hard.

**Comment by zhewang2** [comment]
Yes, 1.3.30 has no issue. Thank you for your explanation!
