### ISSUE TITLE
How i can serialize a Map to a JsonObject

### ISSUE THREAD

**Issue by LartyHD** [Kotlin/kotlinx.serialization#425]
My Code:
```
/* Main */
        private val kSerializer = (UUIDSerializer to Json.context.getOrDefault(Action::class).list).map
        val configData: ConfigData = ConfigData(directory, config.files.actions)


        /* Values */
        fun load(configData: ConfigData = this.configData): MutableMap<UUID, MutableList<Action>> =
            Json.parse(kSerializer, configData.file.readText()).map {
                it.key to it.value.toMutableList()
            }.toMap().toMutableMap()

        fun save(input: MutableMap<UUID, MutableList<Action>>, configData: ConfigData = this.configData) =
            GsonService.save(configData, Json.indented.stringify(kSerializer, input))
```

Expected:
https://gist.github.com/LartyHD/cad7bca6f94be7eb9a52b8e340f2abd9

Result:
https://gist.github.com/LartyHD/3b5996c211c99189068704a02a91d2c2

Thanks for helping

**Comment by sandwwraith** [comment]
This happens because `UUID` seems to be a _complex_ structure. Json standard says that map keys should be strings, and this implementation fallbacks to the array of key-value pairs if map key type cannot be represented as string. Did you implement `UUIDSerializer` yourself? If so, you need to use descriptor with a correct kind, since there is a check in the json implementation: https://github.com/kotlin/kotlinx.serialization/blob/2cbb228e81436a901e13148d8e57af6294507f68/runtime/common/src/main/kotlin/kotlinx/serialization/json/internal/WriteMode.kt#L22
The straightforward way to do it is to use e.g. `StringSerializer.withName(...)`.

**Comment by LartyHD** [comment]
@sandwwraith 
My UUIDSerializer:
```
/**
 * @author Lars Artmann | LartyHD
 * Created by Lars Artmann | LartyHD on 04.04.2019 20:55.
 * Current Version: 1.0 (04.04.2019 - 06.04.2019)
 */
@Serializer(forClass = UUID::class)
object UUIDSerializer : KSerializer<UUID> {

    override val descriptor: SerialDescriptor =
        object : SerialClassDescImpl(javaClass.simpleName.replace("Serializer", "")) {}

    override fun serialize(encoder: Encoder, obj: UUID): Unit = encoder.encodeString(obj.toString())

    override fun deserialize(decoder: Decoder): UUID = UUID.fromString(decoder.decodeString())

}
```

**Comment by LartyHD** [comment]
@sandwwraith But UUIDs are not my problem.
I need a JsonObject a result and not the JsonArray with an UUID than the Action object and this in repetition

**Comment by LartyHD** [comment]
@sandwwraith i had a mistake in the expected gist (i need a JsonArray of Actions), i fixed it (only in the gist)

**Comment by sandwwraith** [comment]
Try to use `override val descriptor = StringDescriptor.withName("UUID")` as here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#representing-classes-as-a-single-value

**Comment by LartyHD** [comment]
@sandwwraith this changed nothing

**Comment by LartyHD** [comment]
The Expeption:
```
kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class kotlin.collections.Map. For generic classes, such as lists, please provide serializer explicitly.
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:28) ~[?:?]
	at de.astride.data.ActionsSerializer.deserialize(Serializer.kt:403) ~[?:?]
	at de.astride.data.ActionsSerializer.deserialize(Serializer.kt:34) ~[?:?]
	at kotlinx.serialization.CoreKt.decode(Core.kt:85) ~[?:?]
	at kotlinx.serialization.json.Json.parse(Json.kt:121) ~[?:?]
	at kotlinx.serialization.json.Json$Companion.parse(Json.kt:161) ~[?:?]
	at de.astride.gungame.services.ConfigService$Actions.load(ConfigService.kt:388) ~[?:?]
	at de.astride.gungame.services.ConfigService$Actions.load$default(ConfigService.kt:387) ~[?:?]
	at de.astride.gungame.GunGame$onEnable$1.invoke(GunGame.kt:63) ~[?:?]
	at de.astride.gungame.GunGame$onEnable$1.invoke(GunGame.kt:32) ~[?:?]
	at net.darkdevelopers.darkbedrock.darkness.general.plugin.interfaces.DarkPlugin$DefaultImpls.sendPluginInfos(DarkPlugin.kt:54) ~[?:?]
	at net.darkdevelopers.darkbedrock.darkness.general.plugin.interfaces.DarkPlugin$DefaultImpls.onEnable(DarkPlugin.kt:29) ~[?:?]
	at net.darkdevelopers.darkbedrock.darkness.spigot.plugin.DarkPlugin.onEnable(DarkPlugin.kt:16) ~[?:?]
	at de.astride.gungame.GunGame.onEnable(GunGame.kt:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by LartyHD** [comment]
It is fixed! Thx or in german: Danke 👍 😄

**Comment by LartyHD** [comment]
My Code:

http://prntscr.com/nabrpu
http://prntscr.com/nabs65
```
inner class Actions internal constructor() {

        /* Main */
        val configData: ConfigData = ConfigData(directory, config.files.actions)
        private val kSerializer: KSerializer<Map<UUID, List<Action>>> =
            (UUIDSerializer to Json.context.getOrDefault(Action::class).list).map

        /* Values */
        fun load(configData: ConfigData = this.configData): MutableMap<UUID, MutableList<Action>> {
            val string = configData.file.readText()
            return if (string.isEmpty()) mutableMapOf() else Json.parse(
                kSerializer,
                string
            ).map { it.key to it.value.toMutableList() }.toMap().toMutableMap()
        }

        fun save(input: MutableMap<UUID, MutableList<Action>>, configData: ConfigData = this.configData) =
            GsonService.save(configData, Json.indented.stringify(kSerializer, input))

    }
```
```
@Serializer(forClass = UUID::class)
object UUIDSerializer : KSerializer<UUID> {

    override val descriptor: SerialDescriptor = StringDescriptor.withName("UUID")

    override fun serialize(encoder: Encoder, obj: UUID): Unit = encoder.encodeString(obj.toString())

    override fun deserialize(decoder: Decoder): UUID = UUID.fromString(decoder.decodeString())

}
```
