### ISSUE TITLE
@Transient property generates "Internal error: Serializer for element of type X has not been found"

### ISSUE THREAD

**Issue by valeriyo** [Kotlin/kotlinx.serialization#493]
**Describe the bug**
A `@Transient` property, which "is not part of the default serialized form of the object" generates an "Internal error: Serializer for element of type X has not been found" nonetheless.

**To Reproduce**
```
import kotlinx.serialization.Serializable

@Serializable
class Apricot(
  @Transient val throwable: Throwable
)
```

Error:

```
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type Throwable has not been found.
To use context serializer as fallback, explicitly annotate element with @ContextualSerialization
File being compiled at position: (7,3) in Apricot.kt

	at org.jetbrains.kotlinx.serialization.compiler.backend.common.TypeUtilKt.findTypeSerializerOrContext(TypeUtil.kt:119)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt.getSerialTypeInfo(JVMCodegenUtil.kt:382)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl$generateLoad$1.invoke(SerializerCodegenImpl.kt:365)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl$generateLoad$1.invoke(SerializerCodegenImpl.kt:32)
	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt$generateMethod$1.doGenerateBody(JVMCodegenUtil.kt:153)
```

Same error occurs for `Throwable?` and `Throwable? = null`

**Expected behavior**
Should just work.

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.0
 - Kotlin platforms: JVM
 - Gradle version: 5.4.1
 - IDE version: Android Studio 3.4.1

**Comment by sandwwraith** [comment]
It seems that you're using `kotlin.jvm.Transient` instead of `kotlinx.serialization.Transient`

**Comment by valeriyo** [comment]
That's it. Could it be a warning of some kind? Thanks.
