### ISSUE TITLE
java.lang.StackOverflowError with huge Serializable class

### ISSUE THREAD

**Issue by 4face-studi0** [Kotlin/kotlinx.serialization#496]
**Describe the bug**
After adding serialisation to my small project, the build throw a `StackOverflowError` after being hanged for 11+ minutes - [full stack trace in Gist](https://gist.github.com/4face-studi0/a45cbd2b6c756a446e53302b2262f742)

I have a single `Serializable` class with something like 700 fields, seems the problem to resides there. Alfter removing the fields, compilation succeed - [file in Gist](https://gist.github.com/4face-studi0/a60edda92cf411df4724a489153a6ab9)

**Expected behaviour**
Build passing

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.1
 - Kotlin platforms: JVM
 - Gradle version: 5.4.1
 - IDE version: Android Studio [3.4, 3.5 beta and 3.6 canary]

**Comment by 4face-studi0** [comment]
Added details

**Comment by sandwwraith** [comment]
I see in the stacktrace:

```
Caused by: java.lang.StackOverflowError
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
	at java.util.Collections$UnmodifiableRandomAccessList.<init>(Collections.java:1395)
	at java.util.Collections.unmodifiableList(Collections.java:1287)
	at com.android.tools.r8.ir.code.BasicBlock.getPredecessors(:1)
	at com.android.tools.r8.ir.code.Phi.a(:2)
	at com.android.tools.r8.ir.conversion.IRBuilder.a(:849)
	at com.android.tools.r8.ir.code.Phi.a(:10)
	at com.android.tools.r8.ir.conversion.IRBuilder.a(:849)
	at com.android.tools.r8.ir.code.Phi.a(:10)
	at com.android.tools.r8.ir.conversion.IRBuilder.a(:849)
	at com.android.tools.r8.ir.code.Phi.a(:10)
	at com.android.tools.r8.ir.conversion.IRBuilder.a(:849)
```

You sure this is connected to the serialization plugin, not the R8 Android tooling?

**Comment by 4face-studi0** [comment]
Well, it could be. Now the problem is solved trimming many usuless fields from my module.

**Comment by sandwwraith** [comment]
Probably it is worth reporting to their tracker and take a look at what they respond
