### ISSUE TITLE
Error with implementation by delegation

### ISSUE THREAD

**Issue by luistrigueiros** [Kotlin/kotlinx.serialization#5]
Given the following domain layer objects:
```
@Serializable
enum class AvailabilityQuotation {
    GUARANTEEDAVAILABLE,
    ONREQUEST,
    UNKNOWN,
    UNAVAILABLE
}

@Serializable
data class Fee(val id: String, val amount: MonetaryAmount)
@Serializable
data class OptionalExtra(val id: String, val quantity: Int = 0, val price: MonetaryAmount)

@Serializable
interface Offer {
    val id: String
    val image: String
    val basePrice: MonetaryAmount
    val totalPrice: MonetaryAmount
    val availabilityQuotation: AvailabilityQuotation
    val fees: List<Fee>
    val optionalOffers: Map<String, OptionalExtra>
}

@Serializable
data class BaseOffer(
        override val id: String,
        override val image: String,
        override val basePrice: MonetaryAmount,
        override val totalPrice: MonetaryAmount,
        override val availabilityQuotation: AvailabilityQuotation,
        override val fees: List<Fee>,
        override val optionalOffers: Map<String, OptionalExtra>) : Offer
```

The compiler is failing to run when the I and @Serializable annotation to BaseOffer object.

The error is:
```
C:\work\cartrawler\git\xapp-2\domain (moving-to-kotlin-serialization)
λ gradle -Dtest.single=DomainSerializationTest test --debug-jvm
e: java.lang.IllegalArgumentException: Non-serializable parent of serializable class must have no arg constructor
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.generateSuperSerializableCall(SerializableCodegenImpl.kt:171)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.doGenerateConstructorImpl(SerializableCodegenImpl.kt:108)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.access$doGenerateConstructorImpl(SerializableCodegenImpl.kt:40)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl$generateInternalConstructor$1.invoke(SerializableCodegenImpl.kt:64)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl$generateInternalConstructor$1.invoke(SerializableCodegenImpl.kt:40)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt$generateMethod$1.doGenerateBody(JVMCodegenUtil.kt:109)
        at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:72)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:569)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:332)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:298)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:176)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.JVMCodegenUtilKt.generateMethod(JVMCodegenUtil.kt:106)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl.generateInternalConstructor(SerializableCodegenImpl.kt:64)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generateSyntheticInternalConstructor(SerializableCodegen.kt:39)
        at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializableCodegen.generate(SerializableCodegen.kt:33)
        at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializableCodegenImpl$Companion.generateSerializableExtensions(SerializableCodegenImpl.kt:51)
        at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationCodegenExtension.generateClassSyntheticParts(SerializationCodegenExtension.kt:28)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:384)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:148)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:319)
        at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:303)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassOrObject(PackageCodegenImpl.java:162)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:86)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:124)
        at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:99)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:442)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:153)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:154)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:58)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:303)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:85)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:213)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:37)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:74)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:87)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:512)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
```

**Comment by sandwwraith** [comment]
One note: you shouldn't apply `@Serializable` annotation to the interface.

**Comment by sandwwraith** [comment]
You also should remove `@Serializable` from enums - in serialization/deserialization process they are treated in special way and don't need explicit annotaion, because they can be saved and restored by default.

With `@Serializable` only on data classes plugin seems to work fine without exceptions.

**Comment by sandwwraith** [comment]
However, I can say that `MonetaryAmount` class in your example is not serializable, so there are likely to be errors in runtime.

**Comment by luistrigueiros** [comment]
Hi Leonid,

Thank you can you advice how to make the MonetaryAmount serializable ?

Kindly
  Luis Oscar

**Comment by sandwwraith** [comment]
We plan to add possibility to define custom external serializers for existing Kotlin and Java classes. However, at this moment creating fully-customized serializer for library Java class is not possible due to a bug (#10)

**Comment by luistrigueiros** [comment]
Can't wait for a fix to this one, :-) to test it.
