### ISSUE TITLE
Trying to parse any map with duplicate keys (sometimes) results in a non-helpful exception

### ISSUE THREAD

**Issue by belyaev-mikhail** [Kotlin/kotlinx.serialization#51]
Let's take the following code:
``` kotlin
@Serializable
data class WrappedMap(val mp: Map<String, Int>)
...
println(run<WrappedMap>{ JSON.parse("""{"mp": { "x" : 23, "x" : 42, "y": 4 }}""") })
```

This results in a following exception:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Elements should be in order, unexpected index 3
	at kotlinx.serialization.internal.ListLikeSerializer.load(CollectionSerializers.kt:74)
	at kotlinx.serialization.KInput.readSerializableValue(Serialization.kt:240)
	at kotlinx.serialization.ElementValueInput.readSerializableElementValue(Serialization.kt:402)
	at ru.spbstu.competition.WrappedMap$$serializer.load(Main.kt)
	at ru.spbstu.competition.WrappedMap$$serializer.load(Main.kt:73)
	at kotlinx.serialization.KInput.read(Serialization.kt:206)
	at kotlinx.serialization.json.JSON.parse(JSON.kt:46)
        <...my code...>

```

This is not specific to JSON and is somehow related to the way `Map`s are deserialized from any input type where duplicate keys are possible. 

You should either be exact about whether you support duplicate keys in such formats or at least provide a better exception, 'cos this is not helpful at all. Even more, if you remove `y` from the data, it is parsed successfully with the value of `x` being `42`.

**Comment by belyaev-mikhail** [comment]
Btw, having duplicate keys in JSON is kinda semi-valid according to [this SO answer](https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object/23195243#23195243), which has all further links.

**Comment by belyaev-mikhail** [comment]
I think I know how to fix this, do you accept pull requests for runtime?

I have a very weird use case where this bug is critically important)

**Comment by elizarov** [comment]
PRs are welcome.
