### ISSUE TITLE
SerialKind.toString() invokes KClass.simpleName which is not available on JVM without kotlin-reflect.jar

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#549]
**Describe the bug**
```
kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath

    at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:79)
    at kotlin.jvm.internal.ClassReference.getSimpleName(ClassReference.kt:12)
    at kotlinx.serialization.SerialKind.toString(Descriptors.kt:11)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:39)
```

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.12.0
 - Kotlin platforms: JVM

**Comment by sandwwraith** [comment]
https://youtrack.jetbrains.com/issue/KT-33646
