### ISSUE TITLE
`IndexOutOfBoundsException` when upgrading to 0.12.0

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#552]
**Describe the bug**
I have a working project which uses Kotlin `1.3.41` and serialization `0.11.1`. When upgrading to Kotlin `1.3.50` and serialization `0.12.0` I receive an error during compilation for `compileKotlinJs`:

> e: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
> 	at java.base/java.util.Objects.checkIndex(Objects.java:372)
> 	at java.base/java.util.ArrayList.get(ArrayList.java:458)
> 	at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.checkTypeArguments(SerializationPluginDeclarationChecker.kt:167)
> 	at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.checkType(SerializationPluginDeclarationChecker.kt:188)
> 	at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.checkTypeArguments(SerializationPluginDeclarationChecker.kt:167)
> 	at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.analyzePropertiesSerializers(SerializationPluginDeclarationChecker.kt:153)
> 	at org.jetbrains.kotlinx.serialization.compiler.diagnostic.SerializationPluginDeclarationChecker.check(SerializationPluginDeclarationChecker.kt:44)
> 	at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.runDeclarationCheckers(ModifiersChecker.java:272)
> 	at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifierListCommon(ModifiersChecker.java:213)
> 	at org.jetbrains.kotlin.resolve.ModifiersChecker$ModifiersCheckingProcedure.checkModifiersForDeclaration(ModifiersChecker.java:172)
> 	at org.jetbrains.kotlin.resolve.DeclarationsChecker.process(DeclarationsChecker.kt:91)
> 	at org.jetbrains.kotlin.resolve.BodyResolver.resolveBodies(BodyResolver.java:245)
> 	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:225)
> 	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:60)
> 	at org.jetbrains.kotlin.js.analyze.TopDownAnalyzerFacadeForJS.analyzeFilesWithGivenTrace(TopDownAnalyzerFacadeForJS.kt:119)
> 	at org.jetbrains.kotlin.js.analyze.TopDownAnalyzerFacadeForJS.analyzeFiles(TopDownAnalyzerFacadeForJS.kt:87)
> 	at org.jetbrains.kotlin.js.analyze.TopDownAnalyzerFacadeForJS.analyzeFiles$default(TopDownAnalyzerFacadeForJS.kt:53)
> 	at org.jetbrains.kotlin.js.analyze.TopDownAnalyzerFacadeForJS.analyzeFiles(TopDownAnalyzerFacadeForJS.kt:43)
> 	at org.jetbrains.kotlin.cli.js.K2JSCompiler.lambda$doExecute$1(K2JSCompiler.java:261)
> 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
> 	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:261)
> 	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:85)
> 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
> 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
> 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
> 	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:158)
> 	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:64)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:237)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:37)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:79)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:91)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:551)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:99)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1739)
> 	at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
> 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
> 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:688)
> 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:835)

**To Reproduce**
In the process of identifying the cause. Will update in case I find the specific class which is causing this. [This is the library I am updating](https://github.com/cph-cachet/carp.core-kotlin).

**Expected behavior**
Compile? :)

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.12.0
 - Kotlin platforms: MP (JVM & JS)
 - Gradle version: 5.5
 - IDE version: IntelliJ 2019.2.1

**Comment by Whathecode** [comment]
Potential duplicate of https://github.com/Kotlin/kotlinx.serialization/issues/527
