### ISSUE TITLE
Nested generic information lost

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx.serialization#578]
**Describe the bug**
I have 2 nested generic classes and their default serializers. When parsing a json, the library does not recognize any of the keys.  Gson works like a charm tho :(

<details>
    <summary>Error stacktrace</summary>

```text
Exception in thread "main" kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 97: Encountered an unknown key Abilities11
	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
	at kotlinx.serialization.json.internal.JsonReader.fail$default(JsonReader.kt:292)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeObjectIndex(StreamingJsonInput.kt:123)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeElementIndex(StreamingJsonInput.kt:88)
	at com.github.lamba92.dragalia.rawresponses.NestedTitleJSON$$serializer.deserialize(NestedTitleJSON.kt)
	at com.github.lamba92.dragalia.rawresponses.NestedTitleJSON$$serializer.deserialize(NestedTitleJSON.kt:6)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at com.github.lamba92.dragalia.rawresponses.NestedTitleJSON$$serializer.deserialize(NestedTitleJSON.kt)
	at com.github.lamba92.dragalia.rawresponses.NestedTitleJSON$$serializer.deserialize(NestedTitleJSON.kt:6)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:58)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:39)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at com.github.lamba92.dragalia.rawresponses.CargoJSON$$serializer.deserialize(CargoJSON.kt)
	at com.github.lamba92.dragalia.rawresponses.CargoJSON$$serializer.deserialize(CargoJSON.kt:6)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.Json.parse(Json.kt:126)
	at kotlinx.serialization.json.Json$Companion.parse(Json.kt:178)
	at com.github.lamba92.dragalia.MainKt.main(Main.kt:200)
	at com.github.lamba92.dragalia.MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at com.github.lamba92.dragalia.MainKt.main(Main.kt)
```
</details>

**To Reproduce**
```kotlin
@Serializable
data class CargoJSON<T>(val cargoquery: List<NestedTitleJSON<T>>)

@Serializable
data class NestedTitleJSON<T>(val title: T)
```
<details>
    <summary>Very long class used as T</summary>

```kotlin
@Serializable
data class AdventurerJSON(
    val Abilities11: String,
    val Abilities12: String,
    val Abilities13: String,
    val Abilities14: String,
    val Abilities21: String,
    val Abilities22: String,
    val Abilities23: String,
    val Abilities24: String,
    val Abilities31: String,
    val Abilities32: String,
    val Abilities33: String,
    val Abilities34: String,
    val Availability: String,
    val CharaType: String,
    val DefCoef: String,
    val Description: String,
    val ElementalType: String,
    val ElementalTypeId: String,
    val EnglishCV: String,
    val ExAbilityData1: String,
    val ExAbilityData2: String,
    val ExAbilityData3: String,
    val ExAbilityData4: String,
    val ExAbilityData5: String,
    val FullName: String,
    val Gender: String,
    val Id: String,
    val IdLong: String,
    val IsPlayable: String,
    val JapaneseCV: String,
    val ManaCircleName: String,
    val MaxAtk: String,
    val MaxFriendshipPoint: String,
    val MaxHp: String,
    val McFullBonusAtk5: String,
    val McFullBonusHp5: String,
    val MinAtk3: String,
    val MinAtk4: String,
    val MinAtk5: String,
    val MinDef: String,
    val MinHp3: String,
    val MinHp4: String,
    val MinHp5: String,
    val Name: String,
    val NameJP: String,
    val NameSC: String,
    val NameTC: String,
    val Obtain: String,
    val PlusAtk0: String,
    val PlusAtk1: String,
    val PlusAtk2: String,
    val PlusAtk3: String,
    val PlusAtk4: String,
    val PlusHp0: String,
    val PlusHp1: String,
    val PlusHp2: String,
    val PlusHp3: String,
    val PlusHp4: String,
    val Race: String,
    val Rarity: String,
    val ReleaseDate: String,
    val ReleaseDate__precision: String,
    @SerialName("ReleaseDate  precision") val ReleaseDate__precision2: String? = null,
    val Skill1Name: String,
    val Skill2Name: String,
    val Title: String,
    val TitleJP: String,
    val TitleSC: String,
    val TitleTC: String,
    val VariationId: String,
    val WeaponType: String,
    val WeaponTypeId: String
) : CargoQueryable
````
</details>

<details>
    <summary>The JSON text</summary>

```json
{
    "cargoquery": [
        {
            "title": {
                "Abilities11": "110010403",
                "Abilities12": "110010404",
                "Abilities13": "0",
                "Abilities14": "0",
                "Abilities21": "110020603",
                "Abilities22": "110020604",
                "Abilities23": "0",
                "Abilities24": "0",
                "Abilities31": "110020603",
                "Abilities32": "0",
                "Abilities33": "0",
                "Abilities34": "0",
                "Availability": "Permanent",
                "CharaType": "Defense",
                "DefCoef": "10",
                "Description": "The self-proclaimed &quot;ultimate treasure hunter.&quot; His exploration skills are unmatched, and he's never been duped by a trap. His dream is to open a museum with the numerous treasures he's found and bring happiness to everyone.",
                "ElementalType": "Flame",
                "ElementalTypeId": "1",
                "EnglishCV": "Daniel Doheny",
                "ExAbilityData1": "101050001",
                "ExAbilityData2": "101050003",
                "ExAbilityData3": "101050005",
                "ExAbilityData4": "101050007",
                "ExAbilityData5": "101050010",
                "FullName": "Marty",
                "Gender": "Male",
                "Id": "110261",
                "IdLong": "10130102",
                "IsPlayable": "1",
                "JapaneseCV": "Makoto Furukawa",
                "ManaCircleName": "MC_0301",
                "MaxAtk": "259",
                "MaxFriendshipPoint": "0",
                "MaxHp": "474",
                "McFullBonusAtk5": "17",
                "McFullBonusHp5": "26",
                "MinAtk3": "25",
                "MinAtk4": "31",
                "MinAtk5": "36",
                "MinDef": "10",
                "MinHp3": "46",
                "MinHp4": "57",
                "MinHp5": "67",
                "Name": "Marty",
                "NameJP": "マーティ",
                "NameSC": "",
                "NameTC": "馬汀",
                "Obtain": "Summoning",
                "PlusAtk0": "30",
                "PlusAtk1": "35",
                "PlusAtk2": "41",
                "PlusAtk3": "35",
                "PlusAtk4": "17",
                "PlusHp0": "55",
                "PlusHp1": "64",
                "PlusHp2": "76",
                "PlusHp3": "64",
                "PlusHp4": "32",
                "Race": "Human",
                "Rarity": "3",
                "ReleaseDate": "2019-01-15 06:00:00",
                "Skill1Name": "Spiral Hunter",
                "Skill2Name": "Safeguard Surge",
                "Title": "Top Ruin Explorer",
                "TitleJP": "&lt;ruby class=&quot;rubytext ruby-ja&quot; lang=&quot;ja&quot;&gt;&lt;rb&gt;遺跡探索の達人&lt;/rb&gt;&lt;rp&gt;（&lt;/rp&gt;&lt;rt&gt;エキスパートハンター&lt;/rt&gt;&lt;rp&gt;）&lt;/rp&gt;&lt;/ruby&gt;",
                "TitleSC": "",
                "TitleTC": "遺蹟探索達人",
                "VariationId": "1",
                "WeaponType": "Sword",
                "WeaponTypeId": "1",
                "ReleaseDate__precision": "0"
            }
        },
        {
            "title": {
                "Abilities11": "110010405",
                "Abilities12": "110010406",
                "Abilities13": "0",
                "Abilities14": "0",
                "Abilities21": "110020904",
                "Abilities22": "110020906",
                "Abilities23": "0",
                "Abilities24": "0",
                "Abilities31": "210000605",
                "Abilities32": "210000606",
                "Abilities33": "0",
                "Abilities34": "0",
                "Availability": "Permanent",
                "CharaType": "Support",
                "DefCoef": "10",
                "Description": "The mighty Paladyn dons a white wedding dress and takes up her place at the front line to secure peace and victory for her land—as well as to remain with the man she secretly loves.",
                "ElementalType": "Wind",
                "ElementalTypeId": "3",
                "EnglishCV": "Ava Lindstrom",
                "ExAbilityData1": "101050005",
                "ExAbilityData2": "101050006",
                "ExAbilityData3": "101050007",
                "ExAbilityData4": "101050008",
                "ExAbilityData5": "101050010",
                "FullName": "Wedding Elisanne",
                "Gender": "Female",
                "Id": "100002",
                "IdLong": "10150302",
                "IsPlayable": "1",
                "JapaneseCV": "Saori Hayami",
                "ManaCircleName": "MC_0501",
                "MaxAtk": "287",
                "MaxFriendshipPoint": "0",
                "MaxHp": "476",
                "McFullBonusAtk5": "17",
                "McFullBonusHp5": "28",
                "MinAtk3": "28",
                "MinAtk4": "35",
                "MinAtk5": "40",
                "MinDef": "10",
                "MinHp3": "46",
                "MinHp4": "58",
                "MinHp5": "67",
                "Name": "Elisanne",
                "NameJP": "エルフィリス",
                "NameSC": "",
                "NameTC": "",
                "Obtain": "Summoning",
                "PlusAtk0": "33",
                "PlusAtk1": "39",
                "PlusAtk2": "46",
                "PlusAtk3": "39",
                "PlusAtk4": "19",
                "PlusHp0": "55",
                "PlusHp1": "64",
                "PlusHp2": "76",
                "PlusHp3": "64",
                "PlusHp4": "32",
                "Race": "Human",
                "Rarity": "5",
                "ReleaseDate": "2019-06-20 06:00:00",
                "Skill1Name": "Sacred Union",
                "Skill2Name": "Wedding Bell",
                "Title": "Battling Bride",
                "TitleJP": "&lt;ruby class=&quot;rubytext ruby-ja&quot; lang=&quot;ja&quot;&gt;&lt;rb&gt;麗しき戦花嫁&lt;/rb&gt;&lt;rp&gt;（&lt;/rp&gt;&lt;rt&gt;ブライドヴァルキリー&lt;/rt&gt;&lt;rp&gt;）&lt;/rp&gt;&lt;/ruby&gt;",
                "TitleSC": "",
                "TitleTC": "",
                "VariationId": "6",
                "WeaponType": "Sword",
                "WeaponTypeId": "1",
                "ReleaseDate__precision": "0"
            }
        }
    ]
}
```
</details>

```kotlin
val deserializer = CargoJSON.serializer(NestedTitleJSON.serializer(AdventurerJSON.serializer()))
val e = Json.parse(deserializer, json)
```

**Expected behavior**
Deserialize I guess?

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.13.0
 - Kotlin platforms: JVM
 - Gradle version: 5.2.6
 - Other relevant context: Windows 10

**Comment by sandwwraith** [comment]
I guess you want `CargoJSON.serializer(AdventurerJSON.serializer())`?

`CargoJSON.serializer(NestedTitleJSON.serializer(AdventurerJSON.serializer()))` produces `KSerializer<CargoJson<NestedTitleJson<AdventurerJson>>>` which is for (after all substitutions) `class CargoJSON(val cargoquery: List<NestedTitleJSON<NestedTitleJSON<AdventurerJSON>>>)`

**Comment by lamba92** [comment]
Oh, well it makes sense! The list has't a generic, only `NestedTitleJSON` has, so the argument for the serializer should be `AdventurerJSON`.  It works like a charm now :) Thank you!
