### ISSUE TITLE
Handle @SerialName collision of polymorphic classes when building the JsonConfiguration

### ISSUE THREAD

**Issue by NorbertSandor** [Kotlin/kotlinx.serialization#589]
**Describe the bug**

Currently it throws an exception only in runtime.

```
kotlinx.serialization.json.JsonDecodingException: Invalid JSON at -1: Strict JSON encountered unknown key: a
You can disable strict mode to skip unknown keys

	at kotlinx.serialization.json.JsonExceptionHelpersKt.jsonUnknownKeyException(JsonExceptionHelpers.kt:22)
	at kotlinx.serialization.json.internal.JsonTreeInput.endStructure(TreeJsonInput.kt:133)
	at test.KotlinSerializationIssueTest$B$$serializer.deserialize(KotlinSerializationIssueTest.kt)
	at test.KotlinSerializationIssueTest$B$$serializer.deserialize(KotlinSerializationIssueTest.kt:19)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:42)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:21)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:41)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at test.KotlinSerializationIssueTest$Container$$serializer.deserialize(KotlinSerializationIssueTest.kt)
	at test.KotlinSerializationIssueTest$Container$$serializer.deserialize(KotlinSerializationIssueTest.kt:22)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.Json.parse(Json.kt:126)
	at test.KotlinSerializationIssueTest.test(KotlinSerializationIssueTest.kt:36)
```

**To Reproduce**

```
class KotlinSerializationIssueTest  {
    interface I

    @Serializable
    @SerialName("A")
    data class A(val a: String = "a"): I

    @Serializable
    @SerialName("A") // By replacing with "B" the test will succeed
    data class B(val b: String = "b"): I

    @Serializable
    data class Container(val i: I)

    @Test
    fun test() {
        val json = Json(context = SerializersModule {
            polymorphic(I::class) {
                A::class with A.serializer()
                B::class with B.serializer()
            }
        })

        val c = Container(A())
        val serialized = json.stringify(Container.serializer(), c)
        assertEquals("""{"i":{"type":"A","a":"a"}}""", serialized)
        assertEquals(c, json.parse(Container.serializer(), serialized))
    }
}
```

**Expected**

It sould throw an exception in configuration time.

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.13.0
 - Kotlin platforms: JVM
 - Gradle version: 5.6.3

**Comment by pdvrieze** [comment]
If I understand it correctly you want to change the function semantics. Currently it is possible to repeatedly set a serializer for the same name (and same base class), but the last one wins. Instead you argue modification should be disallowed.

I can see the point, but remember that consistency with the contextualserializer as well (which I don't think has the uniqueness requirement either) as module merging (adding one module to another) should ideally be present.

Btw. The exception is merely that the wrong deserializer was used. It is not always invalid to change the assigned deserializer for a given name. Perhaps an option would be to have an optional (strict/relaxed) parameter on the module creation function.

**Comment by NorbertSandor** [comment]
> Perhaps an option would be to have an optional (strict/relaxed) parameter on the module creation function.

Maybe this would be sufficient if the "strict" mode would be the default.
My point is that the current behaviour is not "safe/intuitive".

**Comment by sandwwraith** [comment]
It's already in the 'strict' mode, so it is impossible to register two different serializers for one class without the`allowOverwrite` flag: https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/commonMain/src/kotlinx/serialization/modules/SerialModuleImpl.kt#L44

 However, only `KClass` is checked there. Serial name from descriptor should be checked, too.
