### ISSUE TITLE
Serial Context does not seem to always be used

### ISSUE THREAD

**Issue by mayaswrath** [Kotlin/kotlinx.serialization#61]
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.cbor.CBOR
import kotlinx.serialization.json.JSON
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter


@Serializer(forClass = LocalDateTime::class)
object LocalDateTimeSerializer : KSerializer<LocalDateTime> {
    override fun load(input: KInput): LocalDateTime {
        return LocalDateTime.parse(input.readStringValue(), DateTimeFormatter.ISO_DATE_TIME)
    }

    override fun save(output: KOutput, obj: LocalDateTime) {
        output.writeStringValue(obj.format(DateTimeFormatter.ISO_DATE_TIME))
    }

}

@Serializable
class Sample(val map: Map<String, Any>)


fun main(args: Array<String>){

    val context = SerialContext().apply { registerSerializer(LocalDateTime::class, LocalDateTimeSerializer) }


    val cbor = CBOR(context)
    println(cbor.dumps(LocalDateTime.now())) // Works

    val map = mapOf<String, Any>("id" to LocalDateTime.now())
    val sample = Sample(map)

    println(cbor.dumps(sample)) // Fails



    val json = JSON(context = context)
    println(json.stringify(LocalDateTime.now())) // Fails



}
```

In the above sample serializing a LocalDateTime object works when using CBOR. If the value of a map entry is a LocalDateTime object it fails with the following

> Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate companion serializer for class class java.time.LocalDateTime
	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:25)
	at kotlinx.serialization.internal.SerialCache.lookupSerializer$kotlinx_serialization_runtime(Polymorphic.kt:81)
	at kotlinx.serialization.ResolvingKt.serializerByClass(Resolving.kt:38)
	at kotlinx.serialization.ResolvingKt.serializerByValue(Resolving.kt:33)
	at kotlinx.serialization.PolymorphicSerializer.save(PolymorphicSerializer.kt:27)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:143)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:188)
	at kotlinx.serialization.internal.KeyValueSerializer.save(CollectionSerializers.kt:192)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:143)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:188)
	at kotlinx.serialization.internal.ListLikeSerializer.save(CollectionSerializers.kt:49)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:143)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:188)
	at com.segmint.eclipso.Sample.write$Self(Test.kt)
	at com.segmint.eclipso.Sample$$serializer.save(Test.kt)
	at com.segmint.eclipso.Sample$$serializer.save(Test.kt:23)
	at kotlinx.serialization.KOutput.write(Serialization.kt:96)
	at kotlinx.serialization.cbor.CBOR.dump(CBOR.kt:388)

When serializing a LocalDateTime object directly with json it fails. The stringify method appears to  never look at the SerialContext.

**Comment by sandwwraith** [comment]
Fixed in 0.4
