### ISSUE TITLE
Failed to implement KSerializer with inheritance

### ISSUE THREAD

**Issue by rj-hwang** [Kotlin/kotlinx.serialization#619]
**Describe the bug**

Failed to implement KSerializer with inheritance. 

See bellow code: `IsoLocalDateSerializer` inherits from `LocalDateSerializer`. And  `LocalDateSerializer` implements `KSerializer`.

**To Reproduce**

```
package tech.simter.kotlin.serialization

import kotlinx.serialization.*
import kotlinx.serialization.internal.StringDescriptor
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonConfiguration.Companion.Stable
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import java.time.LocalDate
import java.time.format.DateTimeFormatter

/**
 * @author RJ
 */
class KSerializerInheritanceTest {
  private val stableJson = Json(Stable)

  @Serializable
  data class Bean(
    @Serializable(with = IsoLocalDateSerializer::class)
    val p: LocalDate
  )

  @Test
  fun test() {
    val str = """{
      "p": "2019-12-01"
    }"""
    val b = stableJson.parse(Bean.serializer(), str)
    assertThat(b.p).isEqualTo(LocalDate.of(2019, 12, 1))
  }
}

@Serializer(forClass = LocalDate::class)
object IsoLocalDateSerializer : LocalDateSerializer(DateTimeFormatter.ISO_DATE)

open class LocalDateSerializer(private val formatter: DateTimeFormatter) : KSerializer<LocalDate> {
  override val descriptor: SerialDescriptor = StringDescriptor.withName("java.time.LocalDate")
  override fun deserialize(decoder: Decoder): LocalDate {
    return LocalDate.parse(decoder.decodeString(), formatter)
  }

  override fun serialize(encoder: Encoder, obj: LocalDate) {
    encoder.encodeString(obj.format(formatter))
  }
}
```

**Unit test error**

```
[INFO] Running tech.simter.kotlin.serialization.KSerializerInheritanceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in tech.simter.kotlin.serialization.KSerializerInheritanceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in tech.simter.kotlin.serialization.KSerializerInheritanceTest
test  Time elapsed: 0.01 s  <<< ERROR!

kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 13: Expected '{, kind: CLASS'

  at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
  at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:39)
  at tech.simter.kotlin.serialization.IsoLocalDateSerializer.deserialize(KSerializerInheritanceTest.kt)
  at tech.simter.kotlin.serialization.IsoLocalDateSerializer.deserialize(KSerializerInheritanceTest.kt:35)
  at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
  at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
  at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
  at tech.simter.kotlin.serialization.KSerializerInheritanceTest$Bean$$serializer.deserialize(KSerializerInheritanceTest.kt)
  at tech.simter.kotlin.serialization.KSerializerInheritanceTest$Bean$$serializer.deserialize(KSerializerInheritanceTest.kt:19)
  at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
  at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
  at kotlinx.serialization.CoreKt.decode(Core.kt:80)
  at kotlinx.serialization.json.Json.parse(Json.kt:126)
  at tech.simter.kotlin.serialization.KSerializerInheritanceTest.Failed to implement KSerializer with inheritance(KSerializerInheritanceTest.kt:29)
```

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM

**Comment by pdvrieze** [comment]
@rj-hwang It would be very useful to give the actual error message. In this case however one of the errors is that December 2nd is not the same date as December 1st.

**Comment by sandwwraith** [comment]
I believe the reason it fails is that `object IsoLocalDateSerializer` have auto-generated `serialize/deserialize` since it is annotated with `@Serializer(forClass = ...)`. Try to remove annotation `@Serializer` (but leave `@Serializable` on `val p: LocalDate`).

Also see #154 and https://github.com/Kotlin/kotlinx.serialization/issues/154#issuecomment-400402375

**Comment by rj-hwang** [comment]
@pdvrieze Thank you for your reminding. Amend to 2019-12-01 and add the missing error message.

**Comment by rj-hwang** [comment]
@sandwwraith Resolved by remove `@Serializer` on `IsoLocalDateSerializer`  and keep `@Serializable` on `val p: LocalDate`. Thanks!
