### ISSUE TITLE
InstantiationError - HashMap crashes

### ISSUE THREAD

**Issue by geertberkers** [Kotlin/kotlinx.serialization#623]
**Describe the bug**
I'm getting the following error:
```
2019-12-10 17:11:11.738 3728-3728/nl.zorgkluis.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.zorgkluis.demo, PID: 3728
    java.lang.InstantiationError: kotlinx.serialization.KSerializer
        at nl.zorgkluis.demo.MainActivity$Data$$serializer.serialize(MainActivity.kt:22)
        at nl.zorgkluis.demo.MainActivity$Data$$serializer.serialize(Unknown Source:2)
        at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:228)
        at kotlinx.serialization.CoreKt.encode(Core.kt:74)
        at kotlinx.serialization.json.Json.stringify(Json.kt:95)
        at nl.zorgkluis.demo.MainActivity.onCreate(MainActivity.kt:38)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
**To Reproduce**
https://github.com/geertberkers/KotlinXSerialization

**Expected behavior**
Example from nesting. Class should be serialized.
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/examples.md

**Environment**
 - Kotlin version: [1.3.61]
 - Library version: [0.14.0]
 - Kotlin platforms: [JVM/Android]
 - Gradle version: [4.0.0-alpha5]
 - IDE version [Android Studio 4.0 Canary]
 - Other relevant context [MacOS]

**Comment by sandwwraith** [comment]
You are using Jetpack Compose, right? 

I'd say that it doesn't play well with kotlinx.serialization right now. Compose uses new experimental backend of Kotlin compiler, which hasn't been tested with kotlinx.serialization plugin well. Don't worry, we'll fix it eventually.

**Comment by geertberkers** [comment]
Yes I am using Jetpack Compose.

I just tried the exact same code in another project, and that seems to work...

Any idea's on when this will work together?

**Comment by geertberkers** [comment]
Well this is weird, because now I tried to add Jetpack Compose to this new project, and both work.

The only thing that is different is that I could not add this in build.gradle (app)
```
buildFeatures {
    compose true
}
```

But the app is compiling and running withouth any problems
