### ISSUE TITLE
String deserialization is not working

### ISSUE THREAD

**Issue by Wasabi375** [Kotlin/kotlinx.serialization#63]
I have following code 

```Kotlin
class Test(val test: String, val test2: String) {

    companion object : KSerializer<Test> {

        override val serialClassDesc = SerialClassDescImpl("Test")

        init {
            serialClassDesc.addElement("test")
            serialClassDesc.addElement("test2")
        }

        override fun load(input: KInput): Test {
            @Suppress("NAME_SHADOWING")
            val input = input.readBegin(serialClassDesc)

            val test = input.readStringElementValue(serialClassDesc, 0)
            println(test)
            val test2 = input.readStringElementValue(serialClassDesc, 1)

            input.readEnd(serialClassDesc)

            return Test(test, test2)
        }

        override fun save(output: KOutput, obj: Test) {
            @Suppress("NAME_SHADOWING")
            val output = output.writeBegin(serialClassDesc)
            output.writeStringElementValue(serialClassDesc, 0, obj.test)
            output.writeStringElementValue(serialClassDesc, 1, obj.test2)
            output.writeEnd(serialClassDesc)
        }
    }
}

fun main(args: Array<String>) {

    val json = JSON.stringify(Test, Test("hallo", "hi"))
    println(json)
    val result = JSON.parse(Test, json)
    println(result.test)
}
```

But it does not in any way work as I expect. The serialization process works fine. 
The generated json string is `{"test":"hallo","test2":"hi"}`
The parsing on the other hand is really weird. The first value gets parsed to it's name instead of hallo and the when parsing the second value `readStringElementValue´ throws an exception.

The final output of the above code is:
```
{"test":"hallo","test2":"hi"}
Exception in thread "main" java.lang.IllegalArgumentException: JSON at 8: Expected string or non-null literal
	at kotlinx.serialization.json.JSON$Companion.fail(JSON.kt:190)
	at kotlinx.serialization.json.JSON$Companion.access$fail(JSON.kt:54)
	at kotlinx.serialization.json.JSON$Parser.takeStr(JSON.kt:464)
	at kotlinx.serialization.json.JSON$JsonInput.readStringValue(JSON.kt:438)
	at kotlinx.serialization.ElementValueInput.readStringElementValue(Serialization.kt:434)
	at TestSerializer.load(main.kt:23)
	at TestSerializer.load(main.kt:8)
	at kotlinx.serialization.KInput.read(Serialization.kt:209)
	at kotlinx.serialization.json.JSON.parse(JSON.kt:47)
	at kotlinx.serialization.json.JSON$Companion.parse(JSON.kt:57)
	at MainKt.main(main.kt:43)
test
´´´

**Comment by elizarov** [comment]
You do not implement `KSerializer.load` protocol correctly. It is not your fault, since it is not documented properly yet. 

For JSON and other similar protocols that allow reordering of fields the `load` implementation must invoke `readElement` before doing `readStringXXXValue` invocation, like this:

```
        override fun load(input: KInput): Test {
            val input = input.readBegin(serialClassDesc)
            var test: String? = null
            var test2: String? = null
            loop@ while (true) {
                val index = input.readElement(serialClassDesc)
                when (index) {
                    0 -> test = input.readStringElementValue(serialClassDesc, 0)
                    1 -> test2 = input.readStringElementValue(serialClassDesc, 1)
                    KInput.READ_DONE -> break@loop
                    else -> error("Not supported $index")
                }
            }
            input.readEnd(serialClassDesc)
            return Test(test!!, test2!!)
        }
```

Disclaimer: It is not a complete implementation and it is not going to work with some efficient binary formats. In general, `save` and `load` should not be implemented by hand. They are designed to be auto-generated by serialization plugin.
