### ISSUE TITLE
ArrayIndexOutOfBoundsException while deserializing Unit from JsonObject

### ISSUE THREAD

**Issue by juggernaut0** [Kotlin/kotlinx.serialization#645]
**Describe the bug**
When attempting to deserialize Unit (using UnitSerializer) from a JsonElement with `fromJson`, the following exception is thrown:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at kotlinx.serialization.TaggedDecoder.popTag(Tagged.kt:252)
	at kotlinx.serialization.TaggedDecoder.decodeUnit(Tagged.kt:184)
	at kotlinx.serialization.internal.UnitSerializer.deserialize(Primitives.kt:38)
	at kotlinx.serialization.internal.UnitSerializer.deserialize(Primitives.kt:34)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:41)
	at kotlinx.serialization.CoreKt.decode(Core.kt:80)
	at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:20)
	at kotlinx.serialization.json.Json.fromJson(Json.kt:146)
	at UnmapperTest.unmapUnitViaJsonElement(UnmapperTest.kt:18)
...
```

**To Reproduce**
```kotlin
class UnmapperTest {
    private val json = Json(JsonConfiguration.Stable)

    @Test
    fun unmapUnitViaString() {
        assertEquals(Unit, json.parse(UnitSerializer, "{}"))
    }

    @Test
    fun unmapUnitViaJsonElement() {
        assertEquals(Unit, json.fromJson(UnitSerializer, JsonObject(emptyMap())))
    }
}
```

**Expected behavior**
Both tests should pass. Actual behavior is that `unmapUnitViaJsonElement` fails with above exception, while `unmapUnitViaString` succeeds as expected.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms:  JVM
 - Gradle version: 6.0.1

**Comment by sandwwraith** [comment]
@qwwdfsad according to https://github.com/Kotlin/kotlinx.serialization/issues/647#issuecomment-574150971 , we probably need to revise whether representing `Unit` in JSON as `{}` is really a way to go.

@juggernaut0 what's your use-case for using `Unit` in JSON?

**Comment by juggernaut0** [comment]
The use case for Unit in JSON is in generic situations where you want a type to represent "No Data" or "Empty Map". Of course it is trivial to write your own empty Serializable class and use that, but I was hoping to leverage existing stdlib classes.

For a specific example, imagine a library provides a class like this:

```kotlin
class Caller<T, R>(val url: String, val reqSer: SerializationStrategy<T>, val respSer: DeserializationStrategy<R>) {
    suspend fun call(request: T): R {
        val body = Json.stringify(reqSer, request)
        val respStr = doHttpCall(path, body)
        return Json.parse(respSer, respStr)
    }
}
```

It would be useful to reuse this one simple class when T or R needs to be Unit, rather than making 3 more classes for the special cases where T, R, or both could be Unit, or handling these cases as edge cases in code here.
