### ISSUE TITLE
IndexOutOfBoundsException while serialising an object of an inherited class.

### ISSUE THREAD

**Issue by par128** [Kotlin/kotlinx.serialization#663]
**Describe the bug**
There's Car class extending Vehicle class.
Both classes are serializable and both contain properties to serialize.
On attempt to serialize an object of Car an IndexOutOfBoundException is thrown.

The crash is elusive.
Sometimes the app runs just fine.
But build it a couple of times more and the crash appears again.

I wonder if inheritance supported in kotlinx.serialization?

**To Reproduce**

```
//The classes
@Serializable
open class Vehicle {
    @JvmField
    var name: String? = null
    @JvmField
    var color: String? = null
}

@Serializable
open class Car : Vehicle() {
    var maxSpeed = 100f
}

// Serialization code

val json = Json(
	JsonConfiguration.Stable
)

val car = Car()
car.maxSpeed = 100f
car.name = "ford"
var s:String? = json.stringify(Car.serializer(), car)
```

```
//The crash
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at kotlinx.serialization.internal.SerialClassDescImpl.getElementName(SerialClassDescImpl.kt:65)
        at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeElement(StreamingJsonOutput.kt:119)
        at kotlinx.serialization.ElementValueEncoder.encodeNullableSerializableElement(ElementWise.kt:75)
        at yo.lib.model.yodata.Vehicle.write$Self(Vehicle.kt:12)
        at yo.lib.model.yodata.Car.write$Self(Unknown Source:15)
        at yo.lib.model.yodata.Car$$serializer.serialize(Unknown Source:19)
        at yo.lib.model.yodata.Car$$serializer.serialize(Car.kt:7)
        at kotlinx.serialization.json.internal.StreamingJsonOutput.encodeSerializableValue(StreamingJsonOutput.kt:228)
        at kotlinx.serialization.CoreKt.encode(Core.kt:74)
        at kotlinx.serialization.json.Json.stringify(Json.kt:95)
        at yo.activity.KotlinSerializationTest.start(KotlinSerializationTest.kt:43)

```

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM
 - Gradle version: 5.4.1
 - Other relevant context: Mac OS

**Comment by sandwwraith** [comment]
I believe that's the very similar issue that in #378 and #652 that appears when classes are located in different source sets

**Comment by par128** [comment]
This bug is a deal breaker for our project. We have a substantial hierarchy of classes to persist to json.
I wonder if you have any estimations or a workaround?

**Comment by par128** [comment]
Any chance for this to be fixed?

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060
