### ISSUE TITLE
How to test my customSerializer

### ISSUE THREAD

**Issue by yoobi** [Kotlin/kotlinx.serialization#699]
**What is your use-case and why do you need this feature?**
It's more a question than a feature.

I'm trying to implement test for my custom serializer

```kotlin
@Serializer(forClass = String::class)
object PasswordParser : KSerializer<String> {

    override fun serialize(encoder: Encoder, obj: String) {
        encoder.encodeString(obj)
    }

    override fun deserialize(decoder: Decoder): String {
        val password = if(isValidPwd(decoder.decodeString()) decoder.decodeString() else throw Error("Invalid password")
        return toHash(password)
    }
}
```

Here is the test I wrote:

```kotlin
@Serializable
data class PasswordTest(@Serializable(with = PasswordParser::class) var password: String)

@Test
fun isPasswordValid() {
    arrValidPwd.forEach {
        val o = Json.stringify(PasswordTest.serializer(), PasswordTest(it)) //should be : Password("123456789Abcdef")
        val p = Json.parse(PasswordTest.serializer(), o) // should be : "{"password":"123456789Abcdef"}
        assertTrue(it.isHashEquals(p.password), "$it should be true")
    }
}
```

However I got this error:

```
kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 46: Expected string or non-null literal
	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
	at kotlinx.serialization.json.internal.JsonReader.takeString(JsonReader.kt:142)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeString(StreamingJsonInput.kt:154)
	at org.ybservices.module.parser.PasswordParser.deserialize(PasswordParser.kt:22)
	at org.ybservices.module.parser.PasswordParser.deserialize(PasswordParser.kt:10)
```

**Comment by yoobi** [comment]
Solved, because I'm guessing once the `decoder.decodeString()` is used you can't access it anymore.

```
override fun deserialize(decoder: Decoder): String {
        val decoded = decoder.decodeString()
        val password = if(isValidPwd(decoded) decoded else throw Error("Invalid password")
        return toHash(password)
    }
```
