### ISSUE TITLE
Could not find class across modules: kotlinx.serialization.json/Json.Companion [v0.20.0]

### ISSUE THREAD

**Issue by joren-vl** [Kotlin/kotlinx.serialization#752]
**Describe the bug**

After updating our project to Kotlin 1.3.70 and kotlinx.serialization 0.20.0, the project fails to build due to a problem with the c-interop Gradle task. The JVM target compiles, while the iOS target encounters this problem.

However, with Kotlin 1.3.70 and kotlinx.serialization 0.14.0-1.3.70-eap-42, the build succeeds.

We're using the interop for [this Base64 library](https://github.com/ekscrypto/Base64).

```
> Task :mybase:cinteropBase64IosX64
e: Compilation failed: Could not find class across modules: kotlinx.serialization.json/Json.Companion

 * Source files: Base64.kt
 * Compiler version info: Konan: 1.3.70 / Kotlin: 1.3.70
 * Output kind: LIBRARY

e: java.lang.IllegalStateException: Could not find class across modules: kotlinx.serialization.json/Json.Companion
        at org.jetbrains.kotlin.backend.common.serialization.DescriptorReferenceDeserializer.deserializeDescriptorReference(DeserializeDescriptorReference.kt:124)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeDescriptorReference(KotlinIrLinker.kt:364)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeIrSymbolData(KotlinIrLinker.kt:334)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeIrSymbol(KotlinIrLinker.kt:374)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeCall(IrFileDeserializer.kt:361)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeOperation(IrFileDeserializer.kt:844)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeExpression(IrFileDeserializer.kt:882)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeExpressionBody(KotlinIrLinker.kt:391)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrValueParameter(IrFileDeserializer.kt:956)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.access$deserializeIrValueParameter(IrFileDeserializer.kt:128)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrConstructor(IrFileDeserializer.kt:1499)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1280)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrClass(IrFileDeserializer.kt:986)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1282)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1301)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeDeclaration-Yzffb84(KotlinIrLinker.kt:164)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile$deserializeAllFileReachableTopLevel$1.invoke(KotlinIrLinker.kt:417)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile$deserializeAllFileReachableTopLevel$1.invoke(KotlinIrLinker.kt:142)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$DeserializationState$SimpleDeserializationState.processPendingDeclarations(KotlinIrLinker.kt:104)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$IrDeserializerForFile.deserializeAllFileReachableTopLevel(KotlinIrLinker.kt:416)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$deserializeAllModuleReachableTopLevels$1.invoke(KotlinIrLinker.kt:483)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer$deserializeAllModuleReachableTopLevels$1.invoke(KotlinIrLinker.kt:124)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$DeserializationState$ModuleDeserializationState.processPendingDeclarations(KotlinIrLinker.kt:85)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrModuleDeserializer.deserializeAllModuleReachableTopLevels(KotlinIrLinker.kt:481)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeAllReachableTopLevels(KotlinIrLinker.kt:543)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.findDeserializedDeclarationForDescriptor(KotlinIrLinker.kt:574)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.getDeclaration(KotlinIrLinker.kt:581)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGeneratorKt.getDeclaration(ExternalDependenciesGenerator.kt:67)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:41)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:58)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:81)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt:215)
        at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$psiToIrPhase$1.invoke(ToplevelPhases.kt)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:149)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:147)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:30)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
        at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:28)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:77)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:85)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:82)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:50)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:215)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:207)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:241)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:238)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:240)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:375)
        at org.jetbrains.kotlin.cli.utilities.MainKt$main$1.invoke(main.kt:37)
        at org.jetbrains.kotlin.cli.utilities.MainKt$main$1.invoke(main.kt)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:20)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)
```

**To Reproduce**
/

**Expected behavior**
Compilation succeeds.

**Environment**
 - Kotlin version: 1.3.70
 - Library version: 0.20.0
 - Kotlin platforms: JVM, Native
 - Gradle version: 5.6.4

**Comment by sandwwraith** [comment]
Hi, do you use ktor-client or other serialization-dependent libraries? `Json.Companion` was renamed to `Json.Default` in 0.20.0, so this is looks like a binary incompatibility issue from 3rd party dep to me.

**Comment by joren-vl** [comment]
@sandwwraith We are indeed using ktor-client. You're probably right that this is the cause.
According to [this issue](https://github.com/ktorio/ktor/issues/1699), the next Ktor release (1.3.2) should solve my problem. Thanks for pointing this out to me!
