### ISSUE TITLE
No Direct Method GeneratedSerializer

### ISSUE THREAD

**Issue by Krondo** [Kotlin/kotlinx.serialization#763]
**Describe the bug**
I was in the same boat as this issue found here https://github.com/Kotlin/kotlinx.serialization/issues/576
After bumping library version to 0.20.0 I am now getting the following stacktrace. 

```
No direct method <init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;)V in class Lkotlinx/serialization/internal/SerialClassDescImpl; or its super classes (declaration of 'kotlinx.serialization.internal.SerialClassDescImpl'
```
It seems the serializer is not auto generated for the data classes companion object?

I am not sure why I am getting this now. The code is fairly straightforward. It is a Serializable data class with 4 values.  parse on the json I create is what is throwing this. 
```kotlin
Json(configuration = JsonConfiguration.Stable.copy())
                    .parse(MyDataClass.serializer(), record)
```
where record is a json string.

The only thing interesting to note here is the model is in a different module than the code snippet posted above. Not sure if this is specifically a multi module project problem. 

for reference my data class (with field names replaced for example) looks like this:
```kotlin
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MyDataClass(
    @SerialName(FIELD1) val field1: String? = null,
    @SerialName(FIELD2) val field2: String? = null,
    @SerialName(FIELD3) val field3: String? = null,
    @SerialName(FIELD4) val field4: String? = null,
)
```

It seems my issue is similar to this issue https://github.com/Kotlin/kotlinx.serialization/issues/736 but I am not seeing successful results. I have cleaned and rebuilt as well just to make sure nothing funky was happening there.

**Environment**
 - Kotlin version: [1.3.70]
 - Library version: [0.20.0]
 - Gradle version: [4.8.1]
-  Kotlin platforms: [JVM]
 - IDE version [Android Studio 3.5.3]

**Comment by sandwwraith** [comment]
By the look of the method signature, I can suggest that your serialization plugin is still of 1.3.61 or earlier version. Maybe you have updated Kotlin, but forgot to update the plugin?

**Comment by Krondo** [comment]
> By the look of the method signature, I can suggest that your serialization plugin is still of 1.3.61 or earlier version. Maybe you have updated Kotlin, but forgot to update the plugin?

ugh, you are 100% correct. Such a long day. Tsunami of apologies! Thanks for the quick reply, appreciate it!

**Comment by Arushi129** [comment]
Hi, I have the same error on my KMM project.

 java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V in class Lkotlinx/serialization/internal/SerialClassDescImpl; or its super classes (declaration of 'kotlinx.serialization.internal.SerialClassDescImpl' appears in /data/app/com.example.mykmmclient12april-eQ9TG4Mg_9sDGC-WYU26Eg==/base.apk)
        at org.openapitools.client.models.Order$$serializer.<clinit>(Order.kt:28)
        at org.openapitools.client.models.Order$Companion.serializer(Unknown Source:0)
        at org.openapitools.client.infrastructure.ApiClient$Companion.setMappers(ApiClient.kt:64)
        at org.openapitools.client.infrastructure.ApiClient$Companion.access$setMappers(ApiClient.kt:57)
        at org.openapitools.client.infrastructure.ApiClient$serializer$2.invoke(ApiClient.kt:41)
        at org.openapitools.client.infrastructure.ApiClient$serializer$2.invoke(ApiClient.kt:28)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.openapitools.client.infrastructure.ApiClient.getSerializer(Unknown Source:2)
        at org.openapitools.client.infrastructure.ApiClient.jsonRequest(ApiClient.kt:148)
        at org.openapitools.client.apis.StoreApi.placeOrder(StoreApi.kt:171)
        at com.example.mykmmclient12april.MainActivity.callApi(MainActivity.kt:44)
        at com.example.mykmmclient12april.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:29)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)


Order Class - 
@Serializable
data class Order (
    @SerialName(value = "id") val id: kotlin.Long? = null,
    @SerialName(value = "petId") val petId: kotlin.Long? = null,
    @SerialName(value = "quantity") val quantity: kotlin.Int? = null,
    @SerialName(value = "shipDate") val shipDate: kotlin.String? = null,
    /* Order Status */
    @SerialName(value = "status") val status: Order.Status? = null,
    @SerialName(value = "complete") val complete: kotlin.Boolean? = null
) {

Environment:

Kotlin version: [1.3.72]
serialization plugin version:[0.12.0]
IDE version [Android Studio 4.1.1]
gradle version:[6.5]

I doesn't want to update the kotlin and plugin version as it may affect my other projects. Please help.
