### ISSUE TITLE
Mapper: null is not supported

### ISSUE THREAD

**Issue by daberni** [Kotlin/kotlinx.serialization#77]
Given the following class and test

```kotlin
@Serializable
class NullablePropertyClass {

    var nullable: String? = null
    var property: String = "Property Value"
}

@Test
fun testNullableNullProperty() {

    val derived = NullablePropertyClass()

    val map = Mapper.map(derived)
    val unmap = Mapper.unmap<NullablePropertyClass>(map)
}

```

Mapper fails with the following exception

```
kotlinx.serialization.SerializationException: null is not supported

	at kotlinx.serialization.TaggedOutput.writeTaggedNull(Tagged.kt:38)
	at kotlinx.serialization.TaggedOutput.writeNullValue(Tagged.kt:80)
	at kotlinx.serialization.KOutput.writeNullableSerializableValue(Serialization.kt:151)
	at kotlinx.serialization.KOutput.writeNullableSerializableElementValue(Serialization.kt:198)
	at NullablePropertyClass.write$Self(NullMapper.kt)
	at NullablePropertyClass$$serializer.save(NullMapper.kt)
	at NullablePropertyClass$$serializer.save(NullMapper.kt:5)
	at kotlinx.serialization.KOutput.write(Serialization.kt:99)
```

I think it is simply not yet implemented, but would be necessary for common usage

**Comment by sandwwraith** [comment]
For this case, `Mapper` object has `mapNullable/unmapNullable` methods, since regular `map` produces `Map<String, Any>` and `mapNullable` - `Map<String, Any?>`

**Comment by daberni** [comment]
I totally missed that 😱 

Would it be possible to throw a more specific exception which could point to this?
