### ISSUE TITLE
Mapper: ignoring @Optional in unmap

### ISSUE THREAD

**Issue by daberni** [Kotlin/kotlinx.serialization#79]
Given the following class:

```kotlin
@Serializable
data class SomeDataClass(
        val x: String? = "Test",

        @Optional
        val y: String? = "Class"
)
```

having default values and the `@Optional` attribute. Mapper is ignoring the `@Optional` and throwing an exception in `unmap` when key is missing in map.

```kotlin
@Test
fun unmapOptionalTest() {
    val map = mapOf(
            "x" to "some other stuff"
    )

    val data = Mapper.unmap<SomeDataClass>(map)

    Assert.assertEquals("some other stuff", data.x)
    Assert.assertEquals("Class", data.y)
}
```

```
java.util.NoSuchElementException: Key y is missing in the map.

	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:19)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:270)
	at kotlinx.serialization.Mapper$InMapper.readTaggedValue(Tagged.kt:353)
	at kotlinx.serialization.Mapper$InMapper.readTaggedValue(Tagged.kt:352)
	at kotlinx.serialization.TaggedInput.readTaggedString(Tagged.kt:220)
	at kotlinx.serialization.TaggedInput.readStringValue(Tagged.kt:240)
	at kotlinx.serialization.internal.StringSerializer.load(BuiltinSerializers.kt:98)
	at kotlinx.serialization.internal.StringSerializer.load(BuiltinSerializers.kt:94)
	at kotlinx.serialization.KInput.readSerializableValue(Serialization.kt:243)
	at kotlinx.serialization.KInput.readNullableSerializableValue(Serialization.kt:246)
	at kotlinx.serialization.TaggedInput$readNullableSerializableElementValue$1.invoke(Tagged.kt:265)
	at kotlinx.serialization.TaggedInput.tagBlock(Tagged.kt:278)
	at kotlinx.serialization.TaggedInput.readNullableSerializableElementValue(Tagged.kt:265)
	at SomeDataClass$$serializer.load(SampleTest.kt)
	at SomeDataClass$$serializer.load(SampleTest.kt:10)
	at kotlinx.serialization.KInput.read(Serialization.kt:209)
```

But the same is working with `JSON`:

```kotlin
@Test
fun jsonParseTest() {
    val json = """
        {
            "x": "some other stuff"
        }
    """

    val data = JSON.parse<SomeDataClass>(json)

    Assert.assertEquals("some other stuff", data.x)
    Assert.assertEquals("Class", data.y)
}
```

**Comment by DALDEI** [comment]
Just ran into the same problem.  I was hopping to use Mapper as a way of initializing a data class with a map of only the required fields.  This functionality is currently supported by Jackson (was hoping to replace).

**Comment by nbransby** [comment]
Still no progress here? What does it take to get this fixed?

**Comment by sandwwraith** [comment]
It requires an amount of time to be taken from other issues :( I don't think that this particular issue is hard to fix, it should have similar logic as https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/jsMain/src/kotlinx/serialization/DynamicObjectParser.kt#L32 (i.e. iterate all properties and skip missing indices instead of using READ_ALL which throws an exception). So it is a good start for a PR

**Comment by nbransby** [comment]
Yeah I've ended up writing my own Mapper implementation - its a simple fix, ill submit a PR when I get a moment

**Comment by juggernaut0** [comment]
Having this issue as well. Workaround doesn't apply as I need it in a generic situation where I can't create a default object.

@nbransby Mind sharing your implementation? Thanks.

**Comment by nbransby** [comment]
@juggernaut0 I ended up writing a custom serializer, encode and decoder implementation for JS/JVM for my specific use case (Firebase) but you are welcome to check it out:

https://github.com/TeamHubApp/firebase-kotlin-sdk/tree/new-api/firebase-common/src/commonMain/kotlin/dev/teamhub/firebase
