### ISSUE TITLE
.serializer() method returns null in companion obeject

### ISSUE THREAD

**Issue by Vlad8161** [Kotlin/kotlinx.serialization#796]
```
@Polymorphic
@Serializable
sealed class SomeClass {

    @Serializable
    @SerialName("p1")
    data class SomeClass1(val a: Int) : SomeClass()

    @Serializable
    @SerialName("p2")
    data class SomeClass2(
        val a: Int,
        val b: Int
    ) : SomeClass()

    companion object {
        val serializerModule = SerializersModule {
            polymorphic(SomeClass::class) {
                SomeClass1::class with SomeClass1.serializer()
                SomeClass2::class with SomeClass2.serializer()
            }
        }
    }
}
```

When I'm trying to instantiate SomeClass1
```
val someClass = SomeClass1(1)
```

I have an exception:
```
java.lang.ExceptionInInitializerError
	at test.TestSerialization.error(TestSerialization.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at test.SomeClass$Companion$serializerModule$1$1.invoke(SomeClass.kt:27)
	at test.SomeClass$Companion$serializerModule$1$1.invoke(SomeClass.kt:24)
	at kotlinx.serialization.modules.SerializersModuleBuilder.polymorphic(SerialModuleBuilders.kt:150)
	at test.SomeClass$Companion$serializerModule$1.invoke(SomeClass.kt:26)
	at test.SomeClass$Companion$serializerModule$1.invoke(SomeClass.kt:24)
	at kotlinx.serialization.modules.SerialModuleBuildersKt.SerializersModule(SerialModuleBuilders.kt:43)
	at test.SomeClass.<clinit>(SomeClass.kt:25)
	... 48 more
```

But initialization is success if I access SomeClass.serializerModule before creating SomeClass1

```
SomeClass.serializerModule
val someClass = SomeClass1(1)
```
https://github.com/Vlad8161/Reproduce-serialization-bug - sample project to reproduce this bug.
Tests error and success should be run separately to reproduce.

Is this a correct behavior?

**Comment by sandwwraith** [comment]
It looks like there's a cycle in classes initialization order, probably due to some generated code. It's annoying, yes, but such mistakes also can be made by hand, so no anything new here. I can look into it to see if the initialization order can be tweaked somehow.

Btw, did you know that since 0.14.0 you don't have to annotate sealed class as `@Polymorphic` and create a serial module for it?

**Comment by Vlad8161** [comment]
Ok, then I'll just move serializerModule from companion object.

> Btw, did you know that since 0.14.0 you don't have to annotate sealed class as @Polymorphic and create a serial module for it?

No, I didn't, thanks :)

**Comment by qwwdfsad** [comment]
I am closing this: the problematic pattern is fixed by the implicit `@Polymorphic` on sealed classes, but the fix of the original problem is far from being straightforward.

Let's see if we have other reports and, if so, we will fix this issue systematically without applying code-pattern specific hacks
