### ISSUE TITLE
Sealed class polymorphic "not registered" error

### ISSUE THREAD

**Issue by percula** [Kotlin/kotlinx.serialization#801]
**Describe the bug**
I have a sealed class that I am attempting to use polymorphic serialization with, but I am getting this error:

```
kotlinx.serialization.SerializationException: viewListing is not registered for polymorphic serialization in the scope of class com.myapp.models.actions.F
    at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:99)
    at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.access$throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:1)
    at kotlinx.serialization.internal.AbstractPolymorphicSerializer.findPolymorphicSerializer(AbstractPolymorphicSerializer.kt:83)
    at kotlinx.serialization.SealedClassSerializer.findPolymorphicSerializer(SealedSerializer.kt:92)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:41)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
    at com.myapp.models.FeedActivity$$serializer.deserialize(Unknown Source:179)
    at com.myapp.models.FeedActivity$$serializer.deserialize(FeedActivity.kt:9)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
    at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:58)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:39)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
    at com.myapp.models.FeedResponseData$$serializer.deserialize(Unknown Source:101)
    at com.myapp.models.FeedResponseData$$serializer.deserialize(FeedResponseData.kt:8)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
    at com.myapp.models.FeedResponse$$serializer.deserialize(Unknown Source:65)
    at com.myapp.models.FeedResponse$$serializer.deserialize(FeedResponse.kt:6)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.CoreKt.decode(Core.kt:80)
    at kotlinx.serialization.json.Json.parse(Json.kt:126)
    at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:18)
    at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
    at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
    at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
    at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
    at com.myapp.network.ActivityFeedDataSource$load$1.invokeSuspend(ActivityFeedDataSource.kt:74)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

My class:
```kotlin
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
sealed class FeedAction{

    @Serializable
    @SerialName("viewListing")
    public data class viewListing(val listing: FeedListing? = null,
                                  val contact: FeedContact? = null)

    @Serializable
    @SerialName("openContactDetail")
    public data class OpenContactDetail(val lead: FeedLead? = null)

}
```

This class is used here:
```kotlin
@Serializable
class FeedActivity(val action: FeedAction) {
    // stuff
}
```

This polymorphic class is deserialized with the Retrofit Kotlinx.Serialization converter factory.

**To Reproduce**
If you cannot reproduce using the code above, let me know and I'll create a sample project.
NOTE: I am using 0.14.0 because I'm also experiencing issue #576 

**Expected behavior**
No error

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM for Android
 - Gradle version: 5.6.4
 - IDE version: Android Studio 4.0 beta 1

Thank you for your help!

**Comment by Dominaezzz** [comment]
Your subclasses don't extend the sealed class.

**Comment by percula** [comment]
doh! 🤦  Thank you
