### ISSUE TITLE
NoSuchElementException when class discriminator is not present in JSON input (polymorphic deserialization)

### ISSUE THREAD

**Issue by AcidApeStudios** [Kotlin/kotlinx.serialization#815]
`SerializationException` should be thrown instead.

The offending line is:

```
    val type = jsonTree.getValue(json.configuration.classDiscriminator).content
```

Which results in:

```
    java.util.NoSuchElementException: Key t is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:336)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:56)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
        at kotlinx.serialization.json.Json.parse(Json.kt:131)
```

**Comment by antonianemi** [comment]
hi, i am currently having an issue related to this the error i am having 
kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')

i am not sure what is the role of the type discriminator?

**Comment by sandwwraith** [comment]
@antonianemi check out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md

**Comment by Gamakichi** [comment]
> hi, i am currently having an issue related to this the error i am having
> kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')
> 
> i am not sure what is the role of the type discriminator?

Hi @antonianemi ! Did you solve this issue? I'm facing the same problem :(
