### ISSUE TITLE
polymorphic deserialization: NoSuchMethodError in some builds, fixed by gradle clean

### ISSUE THREAD

**Issue by AcidApeStudios** [Kotlin/kotlinx.serialization#817]
There is an issue somewhere (kotlinx-serialization Gradle plugin? compiler plugin?).

Some incremental builds are broken and cause `NoSuchMethodError` when deserializing some classes. When a build is broken, the `NoSuchMethodError` exception happens 100% of the time when trying to deserialize some polymorphic class hierarchies (but not all such hierarchies).

Running `./gradlew clean` and rebuilding always seems to fix the issue.

```
    java.lang.NoSuchMethodError: No direct method <init>(ILkotlinx/serialization/SerializationConstructorMarker;)V in class Lcom/acideapestudios/acidapechess/LichessSocketConnection$Message; or its super classes (declaration of 'com.acideapestudios.acidapechess.LichessSocketConnection$Message' appears in /data/app/com.acideapestudios.acidapechess.gme-1/base.apk:classes2.dex)
        at com.acideapestudios.acidapechess.LichessGameConnection$MoveMessage.<init>(LichessGameConnection.kt)
        at com.acideapestudios.acidapechess.LichessGameConnection$MoveMessage$$serializer.deserialize(LichessGameConnection.kt)
        at com.acideapestudios.acidapechess.LichessGameConnection$MoveMessage$$serializer.deserialize(LichessGameConnection.kt:101)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
        at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
        at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
        at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:21)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
        at kotlinx.serialization.json.Json.parse(Json.kt:131)
        at com.acidapestudios.apeapp.core.serialization.JsonExtensionsKt.tryParse(JsonExtensions.kt:44)
```

**Environment**
 - Kotlin version: 1.3.71
 - Library version: 0.20.0
 - Kotlin platforms: JVM on Android
 - Gradle version: 5.6.4 (org.gradle.daemon=true, org.gradle.parallel=true)
 - IDE version: Android Studio 3.6.3

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060
