### ISSUE TITLE
Backend Internal error: Exception during file facade code generation (1.4m2)

### ISSUE THREAD

**Issue by Tvede-dk** [Kotlin/kotlinx.serialization#857]
**Describe the bug**
Serializable on a generic data class with type parameters fails to compile with the following error, with the given stacktrace
```java
e: java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation
The root cause java.util.NoSuchElementException was thrown at: kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:548)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:247)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:78)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:599)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:194)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:105)
....
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:548)
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:530)
```
**To Reproduce**
Code snippet that causes the issue:
```kotlin
@Serializable
data class serializationIssue<T>(
    val a: T,
    val b: T
)
```
**Expected behavior**
it compiles (like 1.4M1)
**Environment**
 - Kotlin version: 1.4.M2
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.5
It works in 1.4M1 so it looks like a regression

**Comment by sandwwraith** [comment]
Try `0.20.0-1.4-M2`

**Comment by Tvede-dk** [comment]
Thanks, that works (although I had a little issue where somehow it ended up caching some of the old code, such that it worked on invalid json, but after a clean it worked nicely)

**Comment by superdiazzz** [comment]
Could somebody help me to explain this? how to solve this problem?

**Comment by sandwwraith** [comment]
Use most recent Kotlin version and serialization runtime versions

**Comment by Ryggs** [comment]
Has this issue been resolved? I am currently experiencing the same. How was it fixed? Thanks

**Comment by sandwwraith** [comment]
@Ryggs Which versions do you use? Update to most recent ones
