### ISSUE TITLE
TranslationRuntimeException when compiling any Kotlin/JS with @Serializable on 1.4-M2+

### ISSUE THREAD

**Issue by Cottand** [Kotlin/kotlinx.serialization#900]
**Describe the bug**
Compiling Kotlin/JS using a `@Serializable` annotation causes the compiler to crash on Kotlin 1.4 (tested M2 and M3, **M1 does work**)

**To Reproduce**
Minimal example [here](https://github.com/Cottand/serialization-js-1.4) just do `./gradlew build` to reproduce

**Environment**
 - Kotlin version: 1.4-M2 and M3
 - Library version: 0.20.0
 - Kotlin platforms: JS
 - Gradle version: 6.5

Here is the top of the stacktrace:
```
org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: 'import kotlinx.serialization.Serializable

@Serializable
data class A(val x: Int)
' at (1,1) in /home/cottand/dev/IC/streamr/test-js/src/commonMain/kotlin/data.kt
        at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:385)
        at org.jetbrains.kotlin.js.translate.general.Translation.doGenerateAst(Translation.java:336)
        at org.jetbrains.kotlin.js.translate.general.Translation.generateAst(Translation.java:305)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.kt:162)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.kt:107)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits$default(K2JSTranslator.kt:91)
...
```

**Comment by Cottand** [comment]
I tried using
`js(IR) { ... }` or `js(LEGACY)` but no changes

**Comment by sandwwraith** [comment]
runtime `0.20.0-1.4-M2/M3` should be used instead

**Comment by Cottand** [comment]
https://repo.jfrog.org/artifactory/libs-release-bintray/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.20.0-1.4-M3/kotlinx-serialization-runtime-common-0.20.0-1.4-M3.pom?referrer returns a 404

`0.20.0-1.4-M3` is not in jcenter, unlike `0.20.0`. Are you publising EAP somewhere else?

**Comment by Cottand** [comment]
Sorry, didn't spot that they can be found [here](https://bintray.com/kotlin/kotlinx/kotlinx.serialization.runtime/0.20.0-1.4-M3) thanks!
