### ISSUE TITLE
List serialization doesn't work with protobuf

### ISSUE THREAD

**Issue by Aschraf** [Kotlin/kotlinx.serialization#93]
Serializing a list of objects succeeds in JSON and fails with Protobuf

```  kt
fun main(args: Array<String>) {
  val list = listOf(Foo("a"), Foo("b"))

  println(JSON.stringify(Foo.serializer().list, list))
  println(ProtoBuf.dump(Foo.serializer().list, list))
}

@Serializable
data class Foo(@SerialId(1) val foo: String)
```

With the following error:

```
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:341)
	at kotlinx.serialization.TaggedOutput.getCurrentTag(Tagged.kt:163)
	at kotlinx.serialization.protobuf.ProtoBuf$ProtobufWriter.writeBegin(ProtoBuf.kt:47)
	at kotlinx.serialization.KOutput.writeBegin(Serialization.kt:163)
	at kotlinx.serialization.internal.ListLikeSerializer.save(CollectionSerializers.kt:45)
	at kotlinx.serialization.KOutput.write(Serialization.kt:99)
	at kotlinx.serialization.protobuf.ProtoBuf.dump(ProtoBuf.kt:415)
	at kotlinx.serialization.protobuf.ProtoBuf$Companion.dump(ProtoBuf.kt:403)
	at MainClassKt.main(MainClass.kt:21)
```

**Comment by sandwwraith** [comment]
As far as I know, protobuf doesn't have a concept of "root-level list". There are no lists at all, just repeated objects with the same Tag. In your case, tag for `Foo` is not specified (and can't be). The easiest workaround for that is just wrap your list in some object and specify `SerialId` for it.

**Comment by JakeWharton** [comment]
Root-level lists usually refer to delimited messages which are tagless, length-prefixed messages. They're almost always used for streaming, though, and not with buffered data.

**Comment by Aschraf** [comment]
That's exactly what I'm doing for now (wrapping the list in an object). 
I misunderstood the documentation and thought the Protobuf serialization would do that for me. 
The exception was a little bit misleading as It gave me the impression of an issue with my list.
