### ISSUE TITLE
NoSuchMethodError when deserialization polymorphic class

### ISSUE THREAD

**Issue by lucmazon** [Kotlin/kotlinx.serialization#939]
**Description**
In an attempt to serialize something similar to this: https://medium.com/transferwise-engineering/how-to-master-polymorphism-and-custom-serializers-in-kotlinx-serialization-7190da0f42aa , I came up with a `java.lang.NoSuchMethodError: Fruit.<init>(ILjava/lang/String;Lkotlinx/serialization/SerializationConstructorMarker;)V`

**Reproduction**
Here is the code snippet used to reproduce the case. I made a full project available here: https://github.com/lucmazon/serialization-polymorphism

```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonInput
import kotlinx.serialization.json.JsonObject

@Serializable
abstract class Fruit(val itemType: String) {
    abstract val color: String

    @Serializer(forClass = Fruit::class)
    companion object : KSerializer<Fruit> {
        override val descriptor: SerialDescriptor = PrimitiveDescriptor("Fruit", PrimitiveKind.STRING)

        override fun serialize(encoder: Encoder, value: Fruit) {
            when (value) {
                is Apple -> encoder.encode(Apple.serializer(), value)
                is Orange -> encoder.encode(Orange.serializer(), value)
            }
        }

        override fun deserialize(decoder: Decoder): Fruit {
            val input =
                decoder as? JsonInput ?: throw SerializationException("Expected JsonInput for ${decoder::class}")
            val jsonObject = input.decodeJson() as? JsonObject
                ?: throw SerializationException("Expected JsonObject for ${input.decodeJson()::class}")

            val type = jsonObject.getPrimitive("itemType").content

            return when (type) {
                "Apple" -> decoder.json.parse(Apple.serializer(), jsonObject.toString())
                "Orange" -> decoder.json.parse(Orange.serializer(), jsonObject.toString())
                else -> throw SerializationException("Type $type not supported")
            }
        }
    }
}

@Serializable
data class Apple(
    override val color: String,
    val isSour: Boolean
) : Fruit(itemType = "Apple")

@Serializable
data class Orange(
    override val color: String,
    val numberOfSegments: Int
) : Fruit(itemType = "Orange")

fun main() {
    val stringify = Json.stringify(Fruit.serializer(), Apple("red", false))
    val deserialized = Json.parse(Fruit.serializer(), stringify)
    println(stringify)
    println(deserialized)
}
```

**Error Displayed**
```
Exception in thread "main" java.lang.NoSuchMethodError: Fruit.<init>(ILjava/lang/String;Lkotlinx/serialization/SerializationConstructorMarker;)V
	at Apple.<init>(Main.kt)
	at Apple$$serializer.deserialize(Main.kt)
	at Apple$$serializer.deserialize(Main.kt:39)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
	at kotlinx.serialization.json.Json.parse(Json.kt:131)
	at Fruit$Companion.deserialize(Main.kt:30)
	at Fruit$Companion.deserialize(Main.kt:11)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
	at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
	at kotlinx.serialization.json.Json.parse(Json.kt:131)
	at kotlinx.serialization.json.Json$Default.parse(Json.kt:210)
	at MainKt.main(Main.kt:52)
	at MainKt.main(Main.kt)
```

**Environment**
 - Kotlin version: 1.3.72
 - Runtime version: 0.20.0
 - Kotlin platforms: JVM (stdlib-jdk8)
 - Gradle version: 6.5.1

**Comment by sandwwraith** [comment]
It seems the problem is customized serializer: when it is present, the correct deserialization constructor is not generated in the parent.

You can workaround this by making your serializer implementation non-default (i.e. move it from companion to a regular kotlin `object FruitSerializer`). Then you can just use this object instead of `Fruit.serializer()`.

Btw, `JsonParametricSerializer` does exactly the same thing as your custom one. Have you tried to take a look at it?

**Comment by lucmazon** [comment]
I didn't see the `JsonParametricSerializer` part in the docs, I went straight to the custom serializers part. But it is exactly what I wanted to do, and it worked flawlessly, thank you!

**Comment by sandwwraith** [comment]
'Customized serializer via companion' feature is deprecated now
