### ISSUE TITLE
Can't locate default serializer for class <...> after upgrading from 0.4 to 0.4.2

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#95]
Did anything change to the way serializers for classes are retrieved in 0.4.2 compared to 0.4?

After upgrading to 0.4.2, serialization no longer works:
```
kotlinx.serialization.SerializationException: Can't locate default serializer for class class <...>

	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:23)
	at <...>.can't deserialize unknown types(StudyProtocolSnapshotTest.kt:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by hastebrot** [comment]
With an older version I had the opposite problem. Serialization only worked in the test runner.

Did you install the serialization plugin for IDEA? https://github.com/Kotlin/kotlinx.serialization#working-in-intellij-idea

**Comment by Whathecode** [comment]
@hastebrot This is the plugin which when I upgrade causes serialization in my tests (have not tried production) to fail.

I am thus running 0.4 more successfully with compiler version 1.2.30 than the recommended 0.4.2.

**Comment by hastebrot** [comment]
I also used 0.4 (which worked for me for production and tests). When I updated to 0.4.2 I had to ensure the serializers for my classes are still generated and added. Actually 0.4 was the first version which worked for me.

**Comment by sandwwraith** [comment]
Can anyone confirm that this is issue with IDEA plugin or gradle build?

**Comment by Whathecode** [comment]
Problem persists with Kotlin version 1.2.41 and serialization version 0.5.0.

**Comment by sandwwraith** [comment]
Can anyone provide a minimal sample project to reproduce the issue?

**Comment by Whathecode** [comment]
@sandwwraith I'll try to create one this week.

**Comment by sandwwraith** [comment]
@BorzdeG I don't think this test case is relevant here: this approach never worked. Since `ExternalData` has custom user-defined external serializer, it cannot be picked automatically by library, so you need to specify `ExternalSerializer` explicitly (see other cases)

**Comment by sandwwraith** [comment]
Regarding upgrade from `0.4` to higher versions: I've found only one commit that can affect lookup somehow (961258354f79273a4e140142f50add02de36a94e). But it should fix #68 and can't break existent lookups, until you have some very strange code in companion objects.

**Comment by BorzdeG** [comment]
@sandwwraith Has corrected the test - such form the code is correctly written? https://github.com/Kotlin/kotlinx.serialization/pull/122/commits/aa81fd9f8787825b1e622ec189f8f142dfebdb19
It also drops with an error, although the serializer is explicitly specified

**Comment by sandwwraith** [comment]
@BorzdeG still not the case. `@Serializable(with = PayloadSerializer::class)` on a class manipulates generated code, i.e. when this class is inside other serializable class. Root-level resolving can't use information from the compiler, since it happens in runtime; so it falls back to reflection where this information is unavailable.

**Comment by Whathecode** [comment]
Sorry for the delay, only got around to looking more into this issue now. The following test worked for me in v0.4 and started failing in v0.4.2 (and still is in v0.5) since as specified the default serializer cannot be found:
```
val snapshot: StudyProtocolSnapshot = createSnapshot()
val serialized: String = JSON.stringify( snapshot )
val parsed: StudyProtocolSnapshot = JSON.parse( serialized )
assertEquals( snapshot, parsed )
```

Not an independent code sample as requested, but the following _does_ work which might possibly help identifying the problem:
```
var serializer = StudyProtocolSnapshot.serializer()
val snapshot: StudyProtocolSnapshot = createSnapshot()
val serialized: String = JSON.stringify( serializer, snapshot )
val parsed: StudyProtocolSnapshot = JSON.parse( serializer, serialized )
assertEquals( snapshot, parsed )
```

When is it _not_ required to pass the serializer?

**Comment by sandwwraith** [comment]
@Whathecode Does your `StudyProtocolSnapshot` has companion object with custom name and it is not a KSerializer? I think this is the only case where trying to invoke `Companion.serializer()` via reflection can fail, while accessing field `$serializer` not. (I think this is the only change in lookup since 0.4)

**Comment by Whathecode** [comment]
@sandwwraith Exactly, it contains a `Factory` companion object. Looking at your changes for bug #68 and debugging before/after, this is the change which breaks the `JSON.stringify` and `JSON.parse` calls for me when not passing the serializer as an argument, since `this.getField( "Companion" )` throws a `NoSuchFieldException`.

Therefore, the following change might be a potential fix (taking into account my limited understanding of the expected behavior for custom serializers specified as companion objects). It works for both the code given in #68 and the bug I report here:

```
@Suppress("UNCHECKED_CAST")
internal fun <T> Class<T>.invokeSerializerGetter(vararg args: KSerializer<Any>): KSerializer<T>? {
    var serializer: KSerializer<T>? = null

    // Search for custom serializer defined using annotation on companion object.
    val companion = declaredFields.singleOrNull { it.type.declaredAnnotations.filterIsInstance<Serializer>().size == 1 }?.get(null)
    if (companion != null)
    {
        //var methods = companion.methods.find {it.name == "serializer" && it.parameterTypes.size == args.size && it.parameterTypes.all {it == KSerializer::class.java } }
        serializer = companion.javaClass.methods
            .find {it.name == "serializer" && it.parameterTypes.size == args.size && it.parameterTypes.all {it == KSerializer::class.java}}
            ?.invoke(companion, *args) as? KSerializer<T>
    }

    // Search for default serializer in case no custom companion serializer is defined.
    if (serializer == null)
    {
        serializer =
            declaredClasses.singleOrNull { it.simpleName == ("\$serializer") }
            ?.getField("INSTANCE")?.get(null) as? KSerializer<T>
    }

    return serializer?: throw SerializationException("Can't locate companion serializer for class $this")
}
```

**Comment by Whathecode** [comment]
Will try to make a PR; this apparently makes `intBoxTest` fail (`java.lang.NoSuchFieldException: INSTANCE`). All other tests pass.

**Comment by Whathecode** [comment]
Here is a suggested PR. It passes all tests, including a new one for the bug I reported on here which failed before: https://github.com/Kotlin/kotlinx.serialization/pull/130

I do not know about the specification on where the serializer is expected to be located, so this might need more than a sanity check. :) Hope it helps.
